//go:build nanollm_integration

package spine_test

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/invakid404/baml-rest/bamlutils"
	"github.com/invakid404/baml-rest/bamlutils/llmhttp"
	"github.com/invakid404/baml-rest/internal/nativespinejsonfixture"
)

// stream_integration_test.go is the M3e-A SSE fragmentation + post-claim fault matrix at
// the spine executor level, driven by a deterministic loopback provider.
//
// Every CLAIMED row proves the same three things: exactly ONE terminal outcome, exactly
// ONE provider request (no resend, no retry, no fallback, no second RoundTrip), and a
// FailedAfterClaim disposition that is never a decline. Every PRE-CLAIM row proves zero
// sockets and zero emitted events; those live in the pure-Go stream_registry_test.go.

// --- transcript fixture -----------------------------------------------------------

type transcriptDelta struct {
	Content string `json:"content"`
	Emit    bool   `json:"emit"`
	Partial string `json:"partial,omitempty"`
}

type transcriptFixture struct {
	Deltas      []transcriptDelta `json:"deltas"`
	Final       string            `json:"final"`
	Accumulated string            `json:"accumulated"`
}

// StructuredCount is how many deltas produce a structured partial event.
func (tr transcriptFixture) StructuredCount() int {
	n := 0
	for _, d := range tr.Deltas {
		if d.Emit {
			n++
		}
	}
	return n
}

// loadTranscript reads the SHARED expected transcript fixture. It is owned and
// regenerated by internal/nativespinejsonfixture (which computes it from the root-owned
// native static-stream parsers plus the emitted decoders), so this module asserts
// against the same table the booted native-only e2e does — and computes no expectation
// at runtime, and imports no BAML to do it.
func loadTranscript(t *testing.T) transcriptFixture {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	// .../nativeserve/spine/stream_integration_test.go -> repo root
	repoRoot := filepath.Clean(filepath.Join(filepath.Dir(file), "..", ".."))
	path := filepath.Join(repoRoot, "internal", "nativespinejsonfixture", "testdata", "stream_transcript.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read shared stream transcript: %v", err)
	}
	var tr transcriptFixture
	if err := json.Unmarshal(raw, &tr); err != nil {
		t.Fatalf("decode shared stream transcript: %v", err)
	}
	if len(tr.Deltas) == 0 || tr.Final == "" {
		t.Fatal("shared stream transcript is empty")
	}
	return tr
}

// --- SSE loopback -----------------------------------------------------------------

// sseChunk renders one OpenAI streaming chunk carrying an assistant content delta.
func sseChunk(content string) string {
	b, _ := json.Marshal(map[string]any{
		"choices": []any{map[string]any{"delta": map[string]any{"content": content}}},
	})
	return "data: " + string(b) + "\n\n"
}

// sseReasoningChunk renders a chunk carrying ONLY provider reasoning text.
func sseReasoningChunk(text string) string {
	b, _ := json.Marshal(map[string]any{
		"choices": []any{map[string]any{"delta": map[string]any{"reasoning_content": text}}},
	})
	return "data: " + string(b) + "\n\n"
}

// The noise frames every real provider interleaves: a role-only opening delta, an empty
// content delta, a finish-only delta, and a usage-only frame. None may produce an event.
const (
	sseRoleOnly   = `data: {"choices":[{"delta":{"role":"assistant"}}]}` + "\n\n"
	sseEmptyDelta = `data: {"choices":[{"delta":{"content":""}}]}` + "\n\n"
	sseFinishOnly = `data: {"choices":[{"delta":{},"finish_reason":"stop"}]}` + "\n\n"
	sseUsageOnly  = `data: {"choices":[],"usage":{"prompt_tokens":1,"completion_tokens":2}}` + "\n\n"
	sseDone       = "data: [DONE]\n\n"
)

// writeSSE writes body to w as an event-stream, flushing after each fragment. fragment
// <= 0 writes the whole body at once; otherwise the body is split into fragment-byte
// pieces, which deliberately splits multi-byte UTF-8 runes across writes.
func writeSSE(w http.ResponseWriter, body string, fragment int) {
	w.Header().Set("Content-Type", "text/event-stream")
	w.WriteHeader(http.StatusOK)
	flusher, _ := w.(http.Flusher)
	b := []byte(body)
	step := len(b)
	if fragment > 0 {
		step = fragment
	}
	for i := 0; i < len(b); i += step {
		end := i + step
		if end > len(b) {
			end = len(b)
		}
		_, _ = w.Write(b[i:end])
		if flusher != nil {
			flusher.Flush()
		}
	}
}

// transcriptBody renders the shared transcript's content deltas, interleaved with the
// noise frames a real provider sends, and terminated with [DONE].
func transcriptBody(tr transcriptFixture) string {
	var b strings.Builder
	b.WriteString(sseRoleOnly)
	for _, d := range tr.Deltas {
		b.WriteString(sseChunk(d.Content))
		b.WriteString(sseEmptyDelta)
	}
	b.WriteString(sseFinishOnly)
	b.WriteString(sseUsageOnly)
	b.WriteString(sseDone)
	return b.String()
}

// --- executor + drive helpers ------------------------------------------------------

// collectedEvent is one public event the executor delivered.
type collectedEvent struct {
	hasPartial bool
	partial    string
	raw        string
	reasoning  string
}

// collector records events and can inject an emit failure or panic at a chosen index.
type collector struct {
	mu       sync.Mutex
	events   []collectedEvent
	failAt   int // 1-based; 0 disables
	panicAt  int // 1-based; 0 disables
	failWith error
}

func (c *collector) emit(ev bamlutils.NativeSpineStreamEvent) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	n := len(c.events) + 1
	if c.panicAt == n {
		panic("forced emit panic")
	}
	if c.failAt == n {
		return c.failWith
	}
	e := collectedEvent{hasPartial: ev.HasPartial, raw: ev.Raw, reasoning: ev.Reasoning}
	if ev.HasPartial {
		b, err := json.Marshal(ev.Partial)
		if err != nil {
			return fmt.Errorf("marshal partial: %w", err)
		}
		e.partial = string(b)
	}
	c.events = append(c.events, e)
	return nil
}

func (c *collector) snapshot() []collectedEvent {
	c.mu.Lock()
	defer c.mu.Unlock()
	out := make([]collectedEvent, len(c.events))
	copy(out, c.events)
	return out
}

func streamAdapterFor(mode bamlutils.StreamMode, reasoning bool) *testAdapter {
	a := newTestAdapter()
	a.SetStreamMode(mode)
	a.SetIncludeReasoning(reasoning)
	return a
}

func jsonInput() *nativespinejsonfixture.StaticRecursiveAliasJsonInput {
	return &nativespinejsonfixture.StaticRecursiveAliasJsonInput{Topic: "weather"}
}

// assertTerminal asserts a claimed row's shape: FailedAfterClaim, a typed error, and
// exactly one provider request.
func assertTerminal(t *testing.T, res bamlutils.NativeSpineStreamResult, lb *loopback, wantHits int64) {
	t.Helper()
	if res.Disposition != bamlutils.NativeSpineStreamFailedAfterClaim {
		t.Fatalf("disposition = %v (stage %q reason %q err %v), want failed_after_claim", res.Disposition, res.Stage, res.Reason, res.Err)
	}
	if res.Err == nil {
		t.Fatal("a failed-after-claim result carries no typed error")
	}
	if res.Final != nil {
		t.Fatal("a failed-after-claim result carries a final value")
	}
	if got := lb.count(); got != wantHits {
		t.Fatalf("provider request count = %d, want exactly %d (no resend, no retry, no fallback)", got, wantHits)
	}
}

// --- the success transcript --------------------------------------------------------

// TestStreamServesTheSharedTranscript is the acceptance row for both real stream modes:
// the public event sequence equals the SHARED expected transcript exactly — emit/no-emit
// decisions, partial bytes, order, and the final — with exactly one provider request.
func TestStreamServesTheSharedTranscript(t *testing.T) {
	tr := loadTranscript(t)

	for _, tc := range []struct {
		name     string
		mode     bamlutils.StreamMode
		needsRaw bool
	}{
		{"stream", bamlutils.StreamModeStream, false},
		{"stream_with_raw", bamlutils.StreamModeStreamWithRaw, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) {
				writeSSE(w, transcriptBody(tr), 0)
			})
			e := newJSONStreamExec(t, lb.baseURL(), nil)
			c := &collector{}
			res := e.Stream(streamAdapterFor(tc.mode, false), jsonAliasMethod, jsonInput(), c.emit)

			if res.Disposition != bamlutils.NativeSpineStreamSucceeded {
				t.Fatalf("disposition = %v (stage %q reason %q err %v), want succeeded", res.Disposition, res.Stage, res.Reason, res.Err)
			}
			if lb.count() != 1 {
				t.Fatalf("provider request count = %d, want exactly 1", lb.count())
			}

			// The FINAL is the value carrier and marshals to the expected bytes.
			finalBytes, err := json.Marshal(res.Final)
			if err != nil {
				t.Fatalf("marshal final: %v", err)
			}
			if string(finalBytes) != tr.Final {
				t.Fatalf("final = %s, want %s", finalBytes, tr.Final)
			}
			if _, ok := res.Final.(nativespinejsonfixture.OutputJson); !ok {
				t.Fatalf("final has Go type %T, want the FINAL value carrier OutputJson", res.Final)
			}

			// The STRUCTURED events, in order, are exactly the transcript's emitting
			// deltas. Raw-only frames appear on /stream-with-raw only and are checked
			// separately below, so filter them here.
			var structured []collectedEvent
			var rawOnly int
			for _, ev := range c.snapshot() {
				if ev.hasPartial {
					structured = append(structured, ev)
					continue
				}
				rawOnly++
			}
			var want []string
			for _, d := range tr.Deltas {
				if d.Emit {
					want = append(want, d.Partial)
				}
			}
			if len(structured) != len(want) {
				t.Fatalf("got %d structured partial(s), want %d", len(structured), len(want))
			}
			for i := range want {
				if structured[i].partial != want[i] {
					t.Fatalf("structured partial %d = %s, want %s", i, structured[i].partial, want[i])
				}
			}

			if tc.needsRaw {
				// /stream-with-raw: raw rides every event and the final carries the
				// accumulated text; the no-emit delta surfaces as a raw-only frame.
				if rawOnly == 0 {
					t.Fatal("/stream-with-raw produced no raw-only frame for the no-partial delta")
				}
				var raw strings.Builder
				for _, ev := range c.snapshot() {
					raw.WriteString(ev.raw)
				}
				if raw.String() != tr.Accumulated {
					t.Fatalf("accumulated per-delta raw = %q, want %q", raw.String(), tr.Accumulated)
				}
				if res.Raw != tr.Accumulated {
					t.Fatalf("final raw = %q, want %q", res.Raw, tr.Accumulated)
				}
			} else {
				// A plain /stream carries NO raw or reasoning anywhere.
				for i, ev := range c.snapshot() {
					if ev.raw != "" || ev.reasoning != "" {
						t.Fatalf("event %d on /stream carries raw=%q reasoning=%q; both must stay empty", i, ev.raw, ev.reasoning)
					}
				}
				if rawOnly != 0 {
					t.Fatalf("/stream produced %d raw-only frame(s), want 0 (the no-partial delta yields no event)", rawOnly)
				}
				if res.Raw != "" || res.Reasoning != "" {
					t.Fatalf("final raw/reasoning = (%q, %q) on /stream; both must stay empty", res.Raw, res.Reasoning)
				}
			}

			if snap := e.Metrics().Snapshot(); snap.Claims != 1 || snap.Sockets != 1 || snap.Successes != 1 || snap.Failures != 0 || snap.Declines != 0 {
				t.Fatalf("metrics = %+v, want exactly one claim/socket/success", snap)
			}
		})
	}
}

// TestStreamWithRawCarriesReasoningInOrder proves reasoning-only chunks reach the public
// transcript in their original order on /stream-with-raw when the adapter opted in, and
// are suppressed when it did not.
func TestStreamWithRawCarriesReasoningInOrder(t *testing.T) {
	body := sseRoleOnly +
		sseReasoningChunk("thinking a") +
		sseChunk(`{"k":1`) +
		sseReasoningChunk("thinking b") +
		sseChunk(`}`) +
		sseDone

	for _, tc := range []struct {
		name          string
		includeReason bool
		wantReasoning string
	}{
		{"include_reasoning", true, "thinking athinking b"},
		{"reasoning_off", false, ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) { writeSSE(w, body, 0) })
			e := newJSONStreamExec(t, lb.baseURL(), nil)
			c := &collector{}
			res := e.Stream(streamAdapterFor(bamlutils.StreamModeStreamWithRaw, tc.includeReason), jsonAliasMethod, jsonInput(), c.emit)
			if res.Disposition != bamlutils.NativeSpineStreamSucceeded {
				t.Fatalf("disposition = %v (err %v), want succeeded", res.Disposition, res.Err)
			}
			var reasoning strings.Builder
			for _, ev := range c.snapshot() {
				reasoning.WriteString(ev.reasoning)
			}
			if reasoning.String() != tc.wantReasoning {
				t.Fatalf("per-event reasoning = %q, want %q", reasoning.String(), tc.wantReasoning)
			}
			if res.Reasoning != tc.wantReasoning {
				t.Fatalf("final reasoning = %q, want %q", res.Reasoning, tc.wantReasoning)
			}
			if lb.count() != 1 {
				t.Fatalf("provider request count = %d, want exactly 1", lb.count())
			}
		})
	}
}

// TestStreamSurvivesArbitraryFragmentation proves the transport is byte-fragmentation
// independent, INCLUDING splits inside a multi-byte UTF-8 rune: the same body delivered
// one byte at a time yields the same final.
func TestStreamSurvivesArbitraryFragmentation(t *testing.T) {
	const content = `{"k":"héllo→ok"}`
	body := sseRoleOnly + sseChunk(content) + sseDone
	if len([]rune(content)) == len(content) {
		t.Fatal("the fragmentation fixture has no multi-byte rune, so it cannot split one")
	}

	for _, fragment := range []int{1, 3, 7} {
		t.Run(fmt.Sprintf("fragment_%d", fragment), func(t *testing.T) {
			lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) { writeSSE(w, body, fragment) })
			e := newJSONStreamExec(t, lb.baseURL(), nil)
			c := &collector{}
			res := e.Stream(streamAdapterFor(bamlutils.StreamModeStream, false), jsonAliasMethod, jsonInput(), c.emit)
			if res.Disposition != bamlutils.NativeSpineStreamSucceeded {
				t.Fatalf("disposition = %v (err %v), want succeeded", res.Disposition, res.Err)
			}
			b, err := json.Marshal(res.Final)
			if err != nil {
				t.Fatalf("marshal final: %v", err)
			}
			if string(b) != content {
				t.Fatalf("final = %s, want %s", b, content)
			}
			if lb.count() != 1 {
				t.Fatalf("provider request count = %d, want exactly 1", lb.count())
			}
		})
	}
}

// TestStreamNoiseFramesProduceNoEvent proves the cadence's no-event rules at the
// transport level: a stream of ONLY role/empty/finish/usage frames delivers zero public
// events, and the final parse then runs over an empty accumulation (a terminal parse
// failure — never a silent success).
func TestStreamNoiseFramesProduceNoEvent(t *testing.T) {
	body := sseRoleOnly + sseEmptyDelta + sseFinishOnly + sseUsageOnly + sseDone
	lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) { writeSSE(w, body, 0) })
	e := newJSONStreamExec(t, lb.baseURL(), nil)
	c := &collector{}
	res := e.Stream(streamAdapterFor(bamlutils.StreamModeStreamWithRaw, true), jsonAliasMethod, jsonInput(), c.emit)

	if got := c.snapshot(); len(got) != 0 {
		t.Fatalf("noise-only stream produced %d event(s), want 0: %+v", len(got), got)
	}
	assertTerminal(t, res, lb, 1)
	// EXACTLY the documented outcome for this scenario. Accepting either final-parse
	// reason would let a regression that changes which one is produced pass silently,
	// and the two are not interchangeable: the DECLINE reason means the native final
	// parser returned its support sentinel for the accumulated text, which is what an
	// empty accumulation does.
	if res.Reason != reasonFinalParseDeclinedToken {
		t.Fatalf("reason = %q, want %q", res.Reason, reasonFinalParseDeclinedToken)
	}
}

// The bounded reason tokens this suite asserts, spelled once.
const (
	reasonFinalParseDeclinedToken = "native_final_parse_declined"
)

// TestStreamUnclosedFinalCompletes proves an UNCLOSED final (a clean EOF mid-object)
// still produces a final through ParseStaticStreamFinal's EOF completion — the
// documented behaviour a claimed stream depends on, since there is no route back.
func TestStreamUnclosedFinalCompletes(t *testing.T) {
	// No [DONE]: a clean upstream EOF with the JSON object left open.
	body := sseRoleOnly + sseChunk(`{"k":1`)
	lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) { writeSSE(w, body, 0) })
	e := newJSONStreamExec(t, lb.baseURL(), nil)
	c := &collector{}
	res := e.Stream(streamAdapterFor(bamlutils.StreamModeStream, false), jsonAliasMethod, jsonInput(), c.emit)
	if res.Disposition != bamlutils.NativeSpineStreamSucceeded {
		t.Fatalf("disposition = %v (stage %q reason %q err %v), want succeeded", res.Disposition, res.Stage, res.Reason, res.Err)
	}
	b, err := json.Marshal(res.Final)
	if err != nil {
		t.Fatalf("marshal final: %v", err)
	}
	if string(b) != `{"k":1}` {
		t.Fatalf("final = %s, want {\"k\":1} (EOF object completion)", b)
	}
	if lb.count() != 1 {
		t.Fatalf("provider request count = %d, want exactly 1", lb.count())
	}
}

// TestStreamPostClaimFaultMatrix injects each post-claim transport/protocol/parse fault
// and asserts ONE terminal result with exactly one provider request and no resend.
func TestStreamPostClaimFaultMatrix(t *testing.T) {
	tr := loadTranscript(t)
	emitted := nativespinejsonfixture.StreamBinding()

	partialDecodeErr := emitted
	partialDecodeErr.DecodePartial = func([]byte) (any, error) { return nil, errors.New("forced partial decode error") }
	// The P1 regression: a DECODER error whose chain contains the PARSER's "no partial
	// for this prefix yet" sentinel. Only the parser's own no-partial outcome is benign,
	// and it is resolved before the decoder runs — so this must still be TERMINAL. A
	// cadence (or a parse closure) that applied errors.Is(ErrDeBAMLParseUnsupported) to
	// the combined parser+decoder error would swallow it into a no-event and the stream
	// would wrongly SUCCEED.
	partialDecodeSentinel := emitted
	partialDecodeSentinel.DecodePartial = func([]byte) (any, error) {
		return nil, fmt.Errorf("decode static alias stream: %w", bamlutils.ErrDeBAMLParseUnsupported)
	}
	partialDecodePanic := emitted
	partialDecodePanic.DecodePartial = func([]byte) (any, error) { panic("forced partial decode panic") }
	finalDecodeErr := emitted
	finalDecodeErr.Unary.DecodeFinal = func([]byte) (any, error) { return nil, errors.New("forced final decode error") }

	type row struct {
		name       string
		binding    bamlutils.NativeSpineStreamBinding
		handler    func(w http.ResponseWriter, r *http.Request)
		wantStage  string
		wantReason string
	}
	rows := []row{
		{
			name:    "provider_non_2xx_preserved",
			binding: emitted,
			handler: func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusTooManyRequests)
				_, _ = w.Write([]byte(`{"error":"slow down"}`))
			},
			wantStage: "provider", wantReason: "provider_error",
		},
		{
			name:    "invalid_content_type",
			binding: emitted,
			handler: func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte(`{"not":"a stream"}`))
			},
			wantStage: "transport", wantReason: "stream_protocol_error",
		},
		{
			name:      "partial_decoder_failure_is_terminal",
			binding:   partialDecodeErr,
			handler:   func(w http.ResponseWriter, r *http.Request) { writeSSE(w, transcriptBody(tr), 0) },
			wantStage: "stream", wantReason: "emit_error",
		},
		{
			name:      "partial_decoder_error_wrapping_the_parser_sentinel_is_terminal",
			binding:   partialDecodeSentinel,
			handler:   func(w http.ResponseWriter, r *http.Request) { writeSSE(w, transcriptBody(tr), 0) },
			wantStage: "stream", wantReason: "emit_error",
		},
		{
			name:      "partial_decoder_panic_is_terminal",
			binding:   partialDecodePanic,
			handler:   func(w http.ResponseWriter, r *http.Request) { writeSSE(w, transcriptBody(tr), 0) },
			wantStage: "stream", wantReason: "panic",
		},
		{
			name:      "final_decoder_failure_is_terminal",
			binding:   finalDecodeErr,
			handler:   func(w http.ResponseWriter, r *http.Request) { writeSSE(w, transcriptBody(tr), 0) },
			wantStage: "decode", wantReason: "carrier_decode_error",
		},
	}

	for _, tc := range rows {
		t.Run(tc.name, func(t *testing.T) {
			lb := newLoopback(t, tc.handler)
			e := newJSONStreamExec(t, lb.baseURL(), nil, tc.binding)
			c := &collector{}
			res := e.Stream(streamAdapterFor(bamlutils.StreamModeStreamWithRaw, false), jsonAliasMethod, jsonInput(), c.emit)

			assertTerminal(t, res, lb, 1)
			if res.Stage != tc.wantStage || res.Reason != tc.wantReason {
				t.Fatalf("(stage, reason) = (%q, %q), want (%q, %q)", res.Stage, res.Reason, tc.wantStage, tc.wantReason)
			}
			if snap := e.Metrics().Snapshot(); snap.Claims != 1 || snap.Failures != 1 || snap.Successes != 0 {
				t.Fatalf("metrics = %+v, want exactly one claim and one failure", snap)
			}
		})
	}
}

// TestStreamMalformedChunkJSONYieldsNoEvent pins the transport's forgiving frame
// semantics on the claimed lane: a frame whose data is not valid JSON carries no
// channel text, so it produces NO public event and does not terminate the stream — the
// surrounding real chunks still stream and the final still parses. (A frame that is not
// well-formed SSE at all is a decoder terminal; that is the truncated-stream row.)
func TestStreamMalformedChunkJSONYieldsNoEvent(t *testing.T) {
	body := sseRoleOnly +
		"data: {not json at all}\n\n" +
		sseChunk(`{"k":1}`) +
		"data: [[[\n\n" +
		sseDone
	lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) { writeSSE(w, body, 0) })
	e := newJSONStreamExec(t, lb.baseURL(), nil)
	c := &collector{}
	res := e.Stream(streamAdapterFor(bamlutils.StreamModeStream, false), jsonAliasMethod, jsonInput(), c.emit)
	if res.Disposition != bamlutils.NativeSpineStreamSucceeded {
		t.Fatalf("disposition = %v (stage %q reason %q err %v), want succeeded", res.Disposition, res.Stage, res.Reason, res.Err)
	}
	b, err := json.Marshal(res.Final)
	if err != nil {
		t.Fatalf("marshal final: %v", err)
	}
	if string(b) != `{"k":1}` {
		t.Fatalf("final = %s, want {\"k\":1} (the malformed frames contribute nothing)", b)
	}
	if got := c.snapshot(); len(got) != 1 {
		t.Fatalf("got %d event(s), want exactly 1 (only the real chunk produces one): %+v", len(got), got)
	}
	if lb.count() != 1 {
		t.Fatalf("provider request count = %d, want exactly 1", lb.count())
	}
}

// TestStreamTruncatedStreamIsTerminal proves a stream cut off MID-FRAME (the connection
// closes before the frame terminator) is a post-claim decoder terminal with exactly one
// provider request — never a resend.
func TestStreamTruncatedStreamIsTerminal(t *testing.T) {
	// notHijackable records, from the PROVIDER goroutine, that the response writer could
	// not be hijacked. It must not call t.Skip there: httptest runs the handler on its
	// own goroutine, where t.Skip only calls runtime.Goexit on THAT goroutine — the test
	// goroutine would carry on into assertTerminal and report a wrong result instead of
	// skipping. The decision is taken below, on the test goroutine.
	var notHijackable atomic.Bool
	lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/event-stream")
		w.WriteHeader(http.StatusOK)
		flusher, _ := w.(http.Flusher)
		// A complete frame, then a frame truncated mid-payload, then hijack the
		// connection and close it abruptly so the client sees a broken stream rather
		// than a clean EOF.
		_, _ = w.Write([]byte(sseChunk(`{"k":1`)))
		_, _ = w.Write([]byte(`data: {"choices":[{"delta":{"content":`))
		if flusher != nil {
			flusher.Flush()
		}
		hj, ok := w.(http.Hijacker)
		if !ok {
			notHijackable.Store(true)
			return
		}
		conn, _, err := hj.Hijack()
		if err != nil {
			t.Errorf("hijack: %v", err)
			return
		}
		_ = conn.Close()
	})
	e := newJSONStreamExec(t, lb.baseURL(), nil)
	c := &collector{}
	res := e.Stream(streamAdapterFor(bamlutils.StreamModeStream, false), jsonAliasMethod, jsonInput(), c.emit)
	if notHijackable.Load() {
		t.Skip("ResponseWriter is not a Hijacker; cannot truncate the stream")
	}
	assertTerminal(t, res, lb, 1)
	if res.Stage != "transport" {
		t.Fatalf("stage = %q, want transport", res.Stage)
	}
}

// TestStreamPreservesProviderStatusAndBody proves the D11 divergence survives the spine
// lane: a non-2xx surfaces as a typed *llmhttp.HTTPError carrying the REAL status and
// the provider-native body, never a normalized envelope.
func TestStreamPreservesProviderStatusAndBody(t *testing.T) {
	const body = `{"error":{"message":"nope","type":"invalid_request_error"}}`
	lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_, _ = w.Write([]byte(body))
	})
	e := newJSONStreamExec(t, lb.baseURL(), nil)
	c := &collector{}
	res := e.Stream(streamAdapterFor(bamlutils.StreamModeStream, false), jsonAliasMethod, jsonInput(), c.emit)
	assertTerminal(t, res, lb, 1)

	var httpErr *llmhttp.HTTPError
	if !errors.As(res.Err, &httpErr) {
		t.Fatalf("terminal error %v (%T) does not carry a typed *llmhttp.HTTPError", res.Err, res.Err)
	}
	if httpErr.StatusCode != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", httpErr.StatusCode)
	}
	if !strings.Contains(httpErr.Body, "invalid_request_error") {
		t.Fatalf("body = %q, want the provider-native body preserved", httpErr.Body)
	}
}

// TestStreamEmitFaultsAfterClaimAreTerminal proves a failing or PANICKING emit callback
// after the claim is terminal, never a decline, with exactly one provider request — and
// that the recovered panic value never reaches the public error.
func TestStreamEmitFaultsAfterClaimAreTerminal(t *testing.T) {
	tr := loadTranscript(t)
	const secret = "forced emit panic"

	t.Run("emit_error", func(t *testing.T) {
		lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) { writeSSE(w, transcriptBody(tr), 0) })
		e := newJSONStreamExec(t, lb.baseURL(), nil)
		boom := errors.New("consumer went away")
		c := &collector{failAt: 1, failWith: boom}
		res := e.Stream(streamAdapterFor(bamlutils.StreamModeStream, false), jsonAliasMethod, jsonInput(), c.emit)
		assertTerminal(t, res, lb, 1)
		if !errors.Is(res.Err, boom) {
			t.Fatalf("terminal error = %v, want the emit failure propagated", res.Err)
		}
	})

	t.Run("emit_panic", func(t *testing.T) {
		lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) { writeSSE(w, transcriptBody(tr), 0) })
		e := newJSONStreamExec(t, lb.baseURL(), nil)
		c := &collector{panicAt: 1}
		res := e.Stream(streamAdapterFor(bamlutils.StreamModeStream, false), jsonAliasMethod, jsonInput(), c.emit)
		assertTerminal(t, res, lb, 1)
		if res.Reason != "panic" {
			t.Fatalf("reason = %q, want the bounded panic token", res.Reason)
		}
		if strings.Contains(res.Err.Error(), secret) {
			t.Fatalf("the recovered panic value leaked into the public error: %v", res.Err)
		}
	})
}

// TestStreamCancellationAfterClaimIsTerminal proves a caller cancellation observed AFTER
// the claim is terminal (never a decline), with exactly one provider request.
func TestStreamCancellationAfterClaimIsTerminal(t *testing.T) {
	release := make(chan struct{})
	lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/event-stream")
		w.WriteHeader(http.StatusOK)
		flusher, _ := w.(http.Flusher)
		_, _ = w.Write([]byte(sseChunk(`{"k":1`)))
		if flusher != nil {
			flusher.Flush()
		}
		<-release
	})
	t.Cleanup(func() { close(release) })

	e := newJSONStreamExec(t, lb.baseURL(), nil)
	ctx, cancel := context.WithCancel(context.Background())
	ad := streamAdapterFor(bamlutils.StreamModeStream, false)
	ad.Context = ctx
	c := &collector{}
	done := make(chan bamlutils.NativeSpineStreamResult, 1)
	go func() { done <- e.Stream(ad, jsonAliasMethod, jsonInput(), c.emit) }()

	// Wait until the first public event proves the claim happened, then cancel. The loop
	// also selects on done: a Stream that returns BEFORE emitting anything (a decline, or
	// a cadence regression that stops emitting) would otherwise burn the whole window and
	// then fail with a message about the timeout instead of the real result.
	deadline := time.After(15 * time.Second)
	for len(c.snapshot()) == 0 {
		select {
		case res := <-done:
			t.Fatalf("Stream returned before emitting any event: disposition=%v stage=%q reason=%q err=%v", res.Disposition, res.Stage, res.Reason, res.Err)
		case <-deadline:
			t.Fatal("no event before the cancellation window elapsed")
		default:
			time.Sleep(5 * time.Millisecond)
		}
	}
	cancel()

	select {
	case res := <-done:
		assertTerminal(t, res, lb, 1)
		if res.Reason != "stream_cancelled" {
			t.Fatalf("reason = %q, want stream_cancelled", res.Reason)
		}
	case <-time.After(20 * time.Second):
		t.Fatal("Stream did not return after cancellation")
	}
}

// TestStreamCancellationAfterCleanCompletionIsTerminal covers the one window a
// cancellation could previously slip through: the request is cancelled AFTER the transport
// completed cleanly but BEFORE the final parse. That is still post-claim — the socket was
// owned and every partial was already delivered — so it must be terminal, not a Succeeded
// result handed to a caller that has already gone away.
//
// The cancel is issued from inside the LAST emit callback, which runs synchronously on the
// stream goroutine while the body is already fully buffered, so RunStream reaches a clean
// EOF and returns no error of its own. Without the post-completion ctx check the executor
// would parse the final and report success.
func TestStreamCancellationAfterCleanCompletionIsTerminal(t *testing.T) {
	tr := loadTranscript(t)
	lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) { writeSSE(w, transcriptBody(tr), 0) })
	e := newJSONStreamExec(t, lb.baseURL(), nil)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	ad := streamAdapterFor(bamlutils.StreamModeStream, false)
	ad.Context = ctx

	want := tr.StructuredCount()
	if want == 0 {
		t.Fatal("the shared transcript emits no structured partial; this row would never cancel")
	}
	seen := 0
	emit := func(bamlutils.NativeSpineStreamEvent) error {
		seen++
		if seen == want {
			cancel()
		}
		return nil
	}

	res := e.Stream(ad, jsonAliasMethod, jsonInput(), emit)
	assertTerminal(t, res, lb, 1)
	if res.Reason != "stream_cancelled" {
		t.Fatalf("(stage, reason) = (%q, %q), want the cancellation terminal", res.Stage, res.Reason)
	}
	if res.Final != nil {
		t.Fatal("a cancelled stream returned a final value")
	}
}

// TestStreamCancellationDuringFinalDecodeIsTerminal closes the last window in the
// post-claim completion path. The transport completes cleanly and the native final parse
// succeeds; the cancellation arrives DURING the emitted final decode — after any check
// placed between RunStream and the parse would already have passed. The single ctx check
// sits after all post-claim work and immediately before the success returns, so this is
// still terminal.
//
// The cancel is issued from inside an injected DecodeFinal that then decodes
// SUCCESSFULLY, so nothing else can produce a terminal outcome: a Succeeded result here
// would mean the window is open.
func TestStreamCancellationDuringFinalDecodeIsTerminal(t *testing.T) {
	tr := loadTranscript(t)
	lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) { writeSSE(w, transcriptBody(tr), 0) })

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	binding := nativespinejsonfixture.StreamBinding()
	inner := binding.Unary.DecodeFinal
	decoded := false
	binding.Unary.DecodeFinal = func(b []byte) (any, error) {
		decoded = true
		cancel()
		return inner(b)
	}
	e := newJSONStreamExec(t, lb.baseURL(), nil, binding)

	ad := streamAdapterFor(bamlutils.StreamModeStream, false)
	ad.Context = ctx
	c := &collector{}
	res := e.Stream(ad, jsonAliasMethod, jsonInput(), c.emit)

	// NON-VACUITY: the run must actually have reached the final decode, or the row would
	// prove nothing about that window.
	if !decoded {
		t.Fatal("the final decoder never ran; the cancellation window under test was not reached")
	}
	assertTerminal(t, res, lb, 1)
	if res.Reason != "stream_cancelled" {
		t.Fatalf("(stage, reason) = (%q, %q), want the cancellation terminal", res.Stage, res.Reason)
	}
	if res.Final != nil {
		t.Fatal("a cancelled stream returned a final value")
	}
}

// TestStreamByteProgressTimeoutsAreIndependent proves the two byte-progress deadlines
// fire independently and are both terminal with exactly one provider request: a
// first-body timeout (headers, then no body byte) and an idle timeout (a body byte, then
// a stall).
func TestStreamByteProgressTimeoutsAreIndependent(t *testing.T) {
	t.Run("first_body_timeout", func(t *testing.T) {
		t.Setenv(llmhttp.EnvVarStreamFirstBodyTimeout, "150ms")
		t.Setenv(llmhttp.EnvVarStreamIdleTimeout, "30s")
		release := make(chan struct{})
		lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "text/event-stream")
			w.WriteHeader(http.StatusOK)
			if f, ok := w.(http.Flusher); ok {
				f.Flush() // headers only; no body byte
			}
			<-release
		})
		t.Cleanup(func() { close(release) })
		e := newJSONStreamExec(t, lb.baseURL(), nil)
		c := &collector{}
		res := e.Stream(streamAdapterFor(bamlutils.StreamModeStream, false), jsonAliasMethod, jsonInput(), c.emit)
		assertTerminal(t, res, lb, 1)
		if res.Reason != "stream_first_body_timeout" {
			t.Fatalf("reason = %q, want stream_first_body_timeout", res.Reason)
		}
	})

	t.Run("idle_timeout", func(t *testing.T) {
		t.Setenv(llmhttp.EnvVarStreamFirstBodyTimeout, "30s")
		t.Setenv(llmhttp.EnvVarStreamIdleTimeout, "150ms")
		release := make(chan struct{})
		lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "text/event-stream")
			w.WriteHeader(http.StatusOK)
			flusher, _ := w.(http.Flusher)
			_, _ = w.Write([]byte(sseChunk(`{"k":1`)))
			if flusher != nil {
				flusher.Flush()
			}
			<-release // first byte arrived, then the stream stalls
		})
		t.Cleanup(func() { close(release) })
		e := newJSONStreamExec(t, lb.baseURL(), nil)
		c := &collector{}
		res := e.Stream(streamAdapterFor(bamlutils.StreamModeStream, false), jsonAliasMethod, jsonInput(), c.emit)
		assertTerminal(t, res, lb, 1)
		if res.Reason != "stream_idle_timeout" {
			t.Fatalf("reason = %q, want stream_idle_timeout", res.Reason)
		}
	})
}

// TestStreamCallAndParseStayOnTheSameExecutor proves the stream executor still serves
// the FROZEN unary surfaces: /call over the same registry and one provider request, and
// a socket-free direct parse.
func TestStreamCallAndParseStayOnTheSameExecutor(t *testing.T) {
	lb := newLoopback(t, func(w http.ResponseWriter, r *http.Request) { okChatCompletion(w, `{"k":1}`) })
	e := newJSONStreamExec(t, lb.baseURL(), nil)

	res := e.Call(newTestAdapter(), jsonAliasMethod, jsonInput())
	if res.Disposition != bamlutils.NativeSpineSucceeded {
		t.Fatalf("Call disposition = %v (err %v), want succeeded", res.Disposition, res.Err)
	}
	if lb.count() != 1 {
		t.Fatalf("Call provider request count = %d, want exactly 1", lb.count())
	}
	before := lb.count()
	if _, err := e.Parse(newTestAdapter(), jsonAliasMethod, `{"k":1}`); err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if _, err := e.ParseStream(newTestAdapter(), jsonAliasMethod, `{"k":1}`); err != nil {
		t.Fatalf("ParseStream: %v", err)
	}
	if lb.count() != before {
		t.Fatalf("a parse route opened a socket: hits %d -> %d", before, lb.count())
	}
}
