//go:build nanollm_integration

package main

import (
	"context"
	"net/http"
	"testing"

	"github.com/invakid404/baml-rest/bamlutils"
	"github.com/invakid404/baml-rest/workerplugin"
)

// e2e_stream_test.go is the M3e-A booted-command acceptance proof: the REAL
// ./cmd/worker-nativeonly binary, dispensed over go-plugin, SERVES /stream and
// /stream-with-raw for the exact five-arm JSON alias against a deterministic loopback
// SSE provider — with the whole public frame transcript compared to the SHARED
// expectation fixture, exactly one upstream request, and exactly one connection.
//
// The expectation fixture is owned and regenerated by internal/nativespinejsonfixture
// from the ROOT-OWNED native static-stream parsers plus the emitted decoders (whose
// byte/event-exactness against stock BAML v0.223 is what the strict per-prefix parser
// differential and the SSE-replay differential establish for this family). This test
// therefore imports NO BAML to compute an expectation at runtime — it reads a checked-in
// table, which is the whole point of the BAML-free artifact.
//
// It is CI-run under the nanollm_integration tag: it generates the deployment registry
// through the production introspect + generator commands and builds the real binary.

// streamFrames drives one CallStream and returns its frames, asserting the RPC opened.
func streamFrames(t *testing.T, bw *bootedWorker, ctx context.Context, input []byte, mode bamlutils.StreamMode) []*workerplugin.StreamResult {
	t.Helper()
	ch, err := bw.worker.CallStream(ctx, nativeOnlyMethod, input, mode)
	if err != nil {
		t.Fatalf("CallStream(mode %d): %v\nstderr:\n%s", mode, err, bw.stderr.String())
	}
	frames := drainFinal(t, ch)
	if len(frames) == 0 {
		t.Fatalf("CallStream(mode %d) produced no frames", mode)
	}
	return frames
}

// TestNativeOnlyWorker_BootStreamTranscript is the acceptance row for both real stream
// modes through the booted artifact.
func TestNativeOnlyWorker_BootStreamTranscript(t *testing.T) {
	tr := loadTranscript(t)
	reasoning := []string{"thinking a", "", "thinking b"}

	for _, tc := range []struct {
		name     string
		mode     bamlutils.StreamMode
		input    []byte
		needsRaw bool
	}{
		{"stream", bamlutils.StreamModeStream, callInput("weather"), false},
		{"stream_with_raw", bamlutils.StreamModeStreamWithRaw, streamCallInputWithReasoning("weather"), true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			hits := setProviderHandler(func(w http.ResponseWriter, r *http.Request) {
				writeSSE(w, transcriptBody(tr, reasoning), 0)
			})
			bw := bootWorker(t)
			frames := streamFrames(t, bw, context.Background(), tc.input, tc.mode)

			// EXACTLY one upstream request and one connection: one claimed transport,
			// no retry, no fallback, no reset/replay.
			if hits() != 1 {
				t.Fatalf("provider request count = %d, want exactly 1", hits())
			}
			if got := providerConns.Load(); got != 1 {
				t.Fatalf("provider connection count = %d, want exactly 1", got)
			}

			// Exactly one FINAL, and it is the last frame.
			finals := 0
			for i, f := range frames {
				if f.Error != nil {
					t.Fatalf("frame %d is an error frame: %v", i, f.Error)
				}
				if f.Kind == workerplugin.StreamResultKindFinal {
					finals++
					if i != len(frames)-1 {
						t.Fatalf("the final frame is at index %d of %d, want last", i, len(frames))
					}
				}
			}
			if finals != 1 {
				t.Fatalf("got %d final frame(s), want exactly 1", finals)
			}
			last := frames[len(frames)-1]
			if string(last.Data) != tr.Final {
				t.Fatalf("final envelope = %s, want %s", last.Data, tr.Final)
			}

			// The STRUCTURED partial frames, in order, are exactly the transcript's
			// emitting deltas — same emit/no-emit decisions, same bytes, same order.
			var structured []string
			var rawOnly int
			for i, f := range frames[:len(frames)-1] {
				if f.Kind != workerplugin.StreamResultKindStream {
					t.Fatalf("frame %d kind = %v, want a stream frame", i, f.Kind)
				}
				if string(f.Data) == "null" {
					rawOnly++
					continue
				}
				structured = append(structured, string(f.Data))
			}
			want := tr.structuredPartials()
			if len(structured) != len(want) {
				t.Fatalf("got %d structured partial frame(s), want %d", len(structured), len(want))
			}
			for i := range want {
				if structured[i] != want[i] {
					t.Fatalf("structured partial frame %d = %s, want %s", i, structured[i], want[i])
				}
			}

			if tc.needsRaw {
				// /stream-with-raw: the raw channel carries the accumulated model text
				// and the reasoning channel the provider's reasoning deltas, both in
				// their original order.
				if rawOnly == 0 {
					t.Fatal("/stream-with-raw produced no raw-only frame for the no-partial delta")
				}
				var raw, reason string
				for _, f := range frames[:len(frames)-1] {
					raw += f.Raw
					reason += f.Reasoning
				}
				if raw != tr.Accumulated {
					t.Fatalf("accumulated per-frame raw = %q, want %q", raw, tr.Accumulated)
				}
				if reason != "thinking athinking b" {
					t.Fatalf("accumulated per-frame reasoning = %q, want %q", reason, "thinking athinking b")
				}
				if last.Raw != tr.Accumulated {
					t.Fatalf("final frame raw = %q, want %q", last.Raw, tr.Accumulated)
				}
			} else {
				// A plain /stream carries NO raw or reasoning anywhere, and the
				// no-partial delta yields no frame at all.
				if rawOnly != 0 {
					t.Fatalf("/stream produced %d raw-only frame(s), want 0", rawOnly)
				}
				for i, f := range frames {
					if f.Raw != "" || f.Reasoning != "" {
						t.Fatalf("frame %d on /stream carries raw=%q reasoning=%q; both must stay empty", i, f.Raw, f.Reasoning)
					}
				}
			}
		})
	}
}

// TestNativeOnlyWorker_BootStreamSurvivesFragmentation proves the booted artifact's
// transport is byte-fragmentation independent, including splits inside a multi-byte
// UTF-8 rune: the same body delivered one byte at a time yields the same final with one
// upstream request.
func TestNativeOnlyWorker_BootStreamSurvivesFragmentation(t *testing.T) {
	const content = `{"k":"héllo→ok"}`
	body := sseRoleOnly + sseChunk(content) + sseDone
	hits := setProviderHandler(func(w http.ResponseWriter, r *http.Request) {
		writeSSE(w, body, 1)
	})
	bw := bootWorker(t)
	frames := streamFrames(t, bw, context.Background(), callInput("weather"), bamlutils.StreamModeStream)

	last := frames[len(frames)-1]
	if last.Kind != workerplugin.StreamResultKindFinal || last.Error != nil {
		t.Fatalf("last frame = (kind %v, err %v), want a clean final", last.Kind, last.Error)
	}
	if string(last.Data) != content {
		t.Fatalf("final envelope = %s, want %s", last.Data, content)
	}
	if hits() != 1 {
		t.Fatalf("provider request count = %d, want exactly 1", hits())
	}
}

// TestNativeOnlyWorker_BootStreamParseIsSocketFree proves the booted artifact serves the
// NATIVE stream parse (`/parse` with stream=true) with zero provider sockets — the
// generated ParseMethod.StreamImpl is non-nil and native, so the request is neither a
// "does not support stream parse" error nor a transport.
func TestNativeOnlyWorker_BootStreamParseIsSocketFree(t *testing.T) {
	hits := setProviderHandler(func(w http.ResponseWriter, r *http.Request) {
		// A stream parse must never reach the provider; surface it loudly if it does.
		w.WriteHeader(http.StatusInternalServerError)
	})
	bw := bootWorker(t)

	res, err := bw.worker.Parse(context.Background(), nativeOnlyMethod, streamParseInput(`{"k":1`))
	if err != nil {
		t.Fatalf("Parse(stream=true): %v\nstderr:\n%s", err, bw.stderr.String())
	}
	// The partial of an unterminated object is the object built so far.
	if got := string(res.Data); got != `{}` && got != `{"k":1}` {
		t.Fatalf("stream-parse envelope = %s, want the native partial for the prefix", got)
	}
	if hits() != 0 {
		t.Fatalf("stream parse opened %d socket(s), want 0", hits())
	}
}

// TestNativeOnlyWorker_BootStreamPostClaimFaultIsTerminal proves a post-claim fault in
// the booted artifact is ONE terminal error frame with exactly one upstream request:
// there is no BAML to fall back to, so a claimed stream never resends.
func TestNativeOnlyWorker_BootStreamPostClaimFaultIsTerminal(t *testing.T) {
	for _, tc := range []struct {
		name    string
		handler func(w http.ResponseWriter, r *http.Request)
	}{
		{
			name: "provider_non_2xx",
			handler: func(w http.ResponseWriter, r *http.Request) {
				http.Error(w, `{"error":"boom"}`, http.StatusInternalServerError)
			},
		},
		{
			name: "invalid_content_type",
			handler: func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte(`{"not":"a stream"}`))
			},
		},
		{
			name: "no_parseable_content",
			handler: func(w http.ResponseWriter, r *http.Request) {
				// Only noise frames: the final parse has nothing to own, which is
				// terminal (never a silent empty success).
				writeSSE(w, sseRoleOnly+sseFinishOnly+sseUsageOnly+sseDone, 0)
			},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			hits := setProviderHandler(tc.handler)
			bw := bootWorker(t)
			ch, err := bw.worker.CallStream(context.Background(), nativeOnlyMethod, callInput("weather"), bamlutils.StreamModeStream)
			if err != nil {
				// A refusal before any frame is also terminal, but it must not have
				// opened a socket more than once.
				if hits() > 1 {
					t.Fatalf("provider request count = %d, want at most 1", hits())
				}
				return
			}
			frames := drainFinal(t, ch)
			errFrames := 0
			for _, f := range frames {
				if f.Error != nil {
					errFrames++
				}
				if f.Kind == workerplugin.StreamResultKindFinal && f.Error == nil {
					t.Fatalf("a post-claim fault produced a successful final frame: %s", f.Data)
				}
			}
			if errFrames != 1 {
				t.Fatalf("got %d error frame(s), want exactly 1 terminal error: %+v", errFrames, frames)
			}
			if hits() != 1 {
				t.Fatalf("provider request count = %d, want exactly 1 (no resend after the claim)", hits())
			}
		})
	}
}

// TestNativeOnlyWorker_BootStreamCallWithRawStillDeclines proves the CLOSED mode set:
// /call-with-raw is outside ClassStaticStream's promise, so it still declines with zero
// provider sockets even though the two real stream modes now serve.
func TestNativeOnlyWorker_BootStreamCallWithRawStillDeclines(t *testing.T) {
	hits := setProviderHandler(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError) // must never be reached
	})
	bw := bootWorker(t)
	before := hits()
	assertCallDeclines(t, bw, context.Background(), nativeOnlyMethod, callInput("x"), bamlutils.StreamModeCallWithRaw)
	if hits() != before {
		t.Fatalf("call-with-raw decline opened a provider socket: hits %d -> %d", before, hits())
	}
}
