// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/invakid404/baml-rest/internal/nativeprompt/testdata/static_oracle/baml_client/types"
)

type build_request struct{}

var Request = &build_request{}

// Build HTTP request for StaticCompletion (returns baml.HTTPRequest)
func (*build_request) StaticCompletion(topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticCompletion: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticCompletion", encoded)
}

// Build HTTP request for StaticCompletionOutputFormat (returns baml.HTTPRequest)
func (*build_request) StaticCompletionOutputFormat(topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticCompletionOutputFormat: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticCompletionOutputFormat", encoded)
}

// Build HTTP request for StaticEnumArgCanonicalEq (returns baml.HTTPRequest)
func (*build_request) StaticEnumArgCanonicalEq(color types.Color, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"color": color, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumArgCanonicalEq: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumArgCanonicalEq", encoded)
}

// Build HTTP request for StaticEnumArgMemberEq (returns baml.HTTPRequest)
func (*build_request) StaticEnumArgMemberEq(color types.Color, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"color": color, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumArgMemberEq: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumArgMemberEq", encoded)
}

// Build HTTP request for StaticEnumCanonicalArgEq (returns baml.HTTPRequest)
func (*build_request) StaticEnumCanonicalArgEq(color types.Color, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"color": color, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumCanonicalArgEq: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumCanonicalArgEq", encoded)
}

// Build HTTP request for StaticEnumCanonicalEq (returns baml.HTTPRequest)
func (*build_request) StaticEnumCanonicalEq(opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumCanonicalEq: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumCanonicalEq", encoded)
}

// Build HTTP request for StaticEnumCanonicalInMemberList (returns baml.HTTPRequest)
func (*build_request) StaticEnumCanonicalInMemberList(opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumCanonicalInMemberList: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumCanonicalInMemberList", encoded)
}

// Build HTTP request for StaticEnumDifferentMemberEq (returns baml.HTTPRequest)
func (*build_request) StaticEnumDifferentMemberEq(opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumDifferentMemberEq: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumDifferentMemberEq", encoded)
}

// Build HTTP request for StaticEnumDisplayAliasEq (returns baml.HTTPRequest)
func (*build_request) StaticEnumDisplayAliasEq(opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumDisplayAliasEq: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumDisplayAliasEq", encoded)
}

// Build HTTP request for StaticEnumMemberArgEq (returns baml.HTTPRequest)
func (*build_request) StaticEnumMemberArgEq(color types.Color, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"color": color, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumMemberArgEq: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumMemberArgEq", encoded)
}

// Build HTTP request for StaticEnumMemberInCanonicalList (returns baml.HTTPRequest)
func (*build_request) StaticEnumMemberInCanonicalList(opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumMemberInCanonicalList: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumMemberInCanonicalList", encoded)
}

// Build HTTP request for StaticEnumReverseCanonicalEq (returns baml.HTTPRequest)
func (*build_request) StaticEnumReverseCanonicalEq(opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumReverseCanonicalEq: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumReverseCanonicalEq", encoded)
}

// Build HTTP request for StaticEnumSameMemberEq (returns baml.HTTPRequest)
func (*build_request) StaticEnumSameMemberEq(opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticEnumSameMemberEq: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticEnumSameMemberEq", encoded)
}

// Build HTTP request for StaticOutputFormat (returns baml.HTTPRequest)
func (*build_request) StaticOutputFormat(topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticOutputFormat: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticOutputFormat", encoded)
}

// Build HTTP request for StaticPrimitiveArgs (returns baml.HTTPRequest)
func (*build_request) StaticPrimitiveArgs(text string, count int64, ratio float64, flag bool, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "count": count, "ratio": ratio, "flag": flag, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticPrimitiveArgs: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticPrimitiveArgs", encoded)
}

// Build HTTP request for StaticRecursiveA (returns baml.HTTPRequest)
func (*build_request) StaticRecursiveA(topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRecursiveA: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRecursiveA", encoded)
}

// Build HTTP request for StaticRecursiveAliasJSON (returns baml.HTTPRequest)
func (*build_request) StaticRecursiveAliasJSON(topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRecursiveAliasJSON: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRecursiveAliasJSON", encoded)
}

// Build HTTP request for StaticRecursiveAliasJsonValue (returns baml.HTTPRequest)
func (*build_request) StaticRecursiveAliasJsonValue(topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRecursiveAliasJsonValue: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRecursiveAliasJsonValue", encoded)
}

// Build HTTP request for StaticRecursiveAliasJsonValueReordered (returns baml.HTTPRequest)
func (*build_request) StaticRecursiveAliasJsonValueReordered(topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRecursiveAliasJsonValueReordered: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRecursiveAliasJsonValueReordered", encoded)
}

// Build HTTP request for StaticRecursiveB (returns baml.HTTPRequest)
func (*build_request) StaticRecursiveB(topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRecursiveB: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRecursiveB", encoded)
}

// Build HTTP request for StaticRecursiveLoop (returns baml.HTTPRequest)
func (*build_request) StaticRecursiveLoop(topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRecursiveLoop: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRecursiveLoop", encoded)
}

// Build HTTP request for StaticRecursiveNode (returns baml.HTTPRequest)
func (*build_request) StaticRecursiveNode(topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRecursiveNode: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRecursiveNode", encoded)
}

// Build HTTP request for StaticRenderEnum (returns baml.HTTPRequest)
func (*build_request) StaticRenderEnum(color types.Color, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"color": color, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRenderEnum: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRenderEnum", encoded)
}

// Build HTTP request for StaticRenderList (returns baml.HTTPRequest)
func (*build_request) StaticRenderList(colors []types.Color, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"colors": colors, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRenderList: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRenderList", encoded)
}

// Build HTTP request for StaticRenderPalette (returns baml.HTTPRequest)
func (*build_request) StaticRenderPalette(palette types.Palette, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"palette": palette, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRenderPalette: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRenderPalette", encoded)
}

// Build HTTP request for StaticRenderPalettes (returns baml.HTTPRequest)
func (*build_request) StaticRenderPalettes(palettes []types.Palette, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"palettes": palettes, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRenderPalettes: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRenderPalettes", encoded)
}

// Build HTTP request for StaticRenderStrings (returns baml.HTTPRequest)
func (*build_request) StaticRenderStrings(tags []string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"tags": tags, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRenderStrings: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRenderStrings", encoded)
}

// Build HTTP request for StaticRoleChat (returns baml.HTTPRequest)
func (*build_request) StaticRoleChat(topic string, count int64, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "count": count, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRoleChat: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(context.Background(), "StaticRoleChat", encoded)
}
