// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/invakid404/baml-rest/internal/nativeprompt/testdata/static_oracle/baml_client/stream_types"
	"github.com/invakid404/baml-rest/internal/nativeprompt/testdata/static_oracle/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.A":                   reflect.TypeOf(types.A{}),
	"STREAM_TYPES.A":            reflect.TypeOf(stream_types.A{}),
	"TYPES.B":                   reflect.TypeOf(types.B{}),
	"STREAM_TYPES.B":            reflect.TypeOf(stream_types.B{}),
	"TYPES.Loop":                reflect.TypeOf(types.Loop{}),
	"STREAM_TYPES.Loop":         reflect.TypeOf(stream_types.Loop{}),
	"TYPES.Node":                reflect.TypeOf(types.Node{}),
	"STREAM_TYPES.Node":         reflect.TypeOf(stream_types.Node{}),
	"TYPES.StaticAnswer":        reflect.TypeOf(types.StaticAnswer{}),
	"STREAM_TYPES.StaticAnswer": reflect.TypeOf(stream_types.StaticAnswer{}),
}
