// Code generated by cmd/hacks (bamlutils-checked-carrier); DO NOT EDIT.

package types

import (
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

	"github.com/invakid404/baml-rest/bamlutils"
)

// StockChecked is stock BAML v0.223.0's own constraint carrier, preserved under a
// distinct name because the generated `Checked` alias now points at the de-BAML
// carrier.
//
// It is what the client's type map registers: stock's reflective CFFI decoder builds a
// checked value by setting a `map[string]shared.Check` into the registered type's
// `Checks` field, which only this shape accepts.
type StockChecked[T any] = baml.Checked[T]

// FromStockChecked converts stock's decoded carrier into the de-BAML one.
//
// NO ORDER IS INVENTED. Stock's carrier is a map, so the declaration order the CFFI
// list carried is already gone by the time this runs; the result therefore carries no
// recorded order and [bamlutils.Checked.MarshalJSON] takes its documented deterministic
// fallback (lexicographic by label) rather than Go's randomised map iteration. That is
// the whole point of the re-point: BAML's own parse of a checked value now serializes
// deterministically too.
func FromStockChecked[T any](in StockChecked[T]) Checked[T] {
	checks := make(map[string]bamlutils.Check, len(in.Checks))
	for label, c := range in.Checks {
		checks[label] = bamlutils.Check{Name: c.Name, Expression: c.Expression, Status: c.Status}
	}
	return Checked[T]{Value: in.Value, Checks: checks}
}

// FromStockCheckedPtr is [FromStockChecked] for the nullable/streaming pointer form. A
// nil input stays nil: an absent partial is not an empty carrier.
func FromStockCheckedPtr[T any](in *StockChecked[T]) *Checked[T] {
	if in == nil {
		return nil
	}
	out := FromStockChecked(*in)
	return &out
}
