// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type A struct {
	Value string `json:"value"`
	B     *B     `json:"b"`
}

func (c *A) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "A" {
		panic(fmt.Sprintf("expected A, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "value":
			c.Value = baml.Decode(valueHolder).Interface().(string)

		case "b":
			c.B = baml.Decode(valueHolder).Interface().(*B)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class A", key))

		}
	}

}

func (c A) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["value"] = c.Value

	fields["b"] = c.B

	return baml.EncodeClass("A", fields, nil)
}

func (c A) BamlTypeName() string {
	return "A"
}

type B struct {
	Value string `json:"value"`
	A     *A     `json:"a"`
}

func (c *B) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "B" {
		panic(fmt.Sprintf("expected B, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "value":
			c.Value = baml.Decode(valueHolder).Interface().(string)

		case "a":
			c.A = baml.Decode(valueHolder).Interface().(*A)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class B", key))

		}
	}

}

func (c B) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["value"] = c.Value

	fields["a"] = c.A

	return baml.EncodeClass("B", fields, nil)
}

func (c B) BamlTypeName() string {
	return "B"
}

type Loop struct {
	Next *Loop `json:"next"`
}

func (c *Loop) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Loop" {
		panic(fmt.Sprintf("expected Loop, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "next":
			c.Next = baml.Decode(valueHolder).Interface().(*Loop)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Loop", key))

		}
	}

}

func (c Loop) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["next"] = c.Next

	return baml.EncodeClass("Loop", fields, nil)
}

func (c Loop) BamlTypeName() string {
	return "Loop"
}

type Node struct {
	Value string `json:"value"`
	Next  *Node  `json:"next"`
}

func (c *Node) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Node" {
		panic(fmt.Sprintf("expected Node, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "value":
			c.Value = baml.Decode(valueHolder).Interface().(string)

		case "next":
			c.Next = baml.Decode(valueHolder).Interface().(*Node)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Node", key))

		}
	}

}

func (c Node) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["value"] = c.Value

	fields["next"] = c.Next

	return baml.EncodeClass("Node", fields, nil)
}

func (c Node) BamlTypeName() string {
	return "Node"
}

type Palette struct {
	Primary Color   `json:"primary"`
	Shades  []Color `json:"shades"`
	Swatch  Swatch  `json:"swatch"`
	Name    string  `json:"name"`
}

func (c *Palette) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Palette" {
		panic(fmt.Sprintf("expected Palette, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "primary":
			c.Primary = baml.Decode(valueHolder).Interface().(Color)

		case "shades":
			c.Shades = baml.Decode(valueHolder).Interface().([]Color)

		case "swatch":
			c.Swatch = baml.Decode(valueHolder).Interface().(Swatch)

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Palette", key))

		}
	}

}

func (c Palette) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["primary"] = c.Primary

	fields["shades"] = c.Shades

	fields["swatch"] = c.Swatch

	fields["name"] = c.Name

	return baml.EncodeClass("Palette", fields, nil)
}

func (c Palette) BamlTypeName() string {
	return "Palette"
}

type StaticAnswer struct {
	Answer     string `json:"answer"`
	Confidence int64  `json:"confidence"`
}

func (c *StaticAnswer) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "StaticAnswer" {
		panic(fmt.Sprintf("expected StaticAnswer, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "answer":
			c.Answer = baml.Decode(valueHolder).Interface().(string)

		case "confidence":
			c.Confidence = baml.Decode(valueHolder).Int()

		default:

			panic(fmt.Sprintf("unexpected field: %s in class StaticAnswer", key))

		}
	}

}

func (c StaticAnswer) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["answer"] = c.Answer

	fields["confidence"] = c.Confidence

	return baml.EncodeClass("StaticAnswer", fields, nil)
}

func (c StaticAnswer) BamlTypeName() string {
	return "StaticAnswer"
}

type Swatch struct {
	Color Color  `json:"color"`
	Label string `json:"label"`
}

func (c *Swatch) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Swatch" {
		panic(fmt.Sprintf("expected Swatch, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "color":
			c.Color = baml.Decode(valueHolder).Interface().(Color)

		case "label":
			c.Label = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Swatch", key))

		}
	}

}

func (c Swatch) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["color"] = c.Color

	fields["label"] = c.Label

	return baml.EncodeClass("Swatch", fields, nil)
}

func (c Swatch) BamlTypeName() string {
	return "Swatch"
}
