// Package nativespinelistfixture is the scalar-LIST input cohort's carrier
// fixture: the emitted hermetic native package for the single admitted method
// whose inputs mix required scalars with required single-level lists of
// non-nullable primitives and whose return is the UNCHANGED exact five-arm `JSON`
// recursive alias (StaticListArgsJSON(topic, tags, counts, ratios, flags) -> JSON).
//
// generated_list_args.go holds the carriers, the reflection-free input projector,
// the strict final/partial decoders, the neutral-executor-driven
// StreamingMethod/ParseMethod builder, and the Binding()/StreamBinding() the
// production runtime consumes. It is EMITTED by
// adapters/common/codegen.EmitNativeStaticStream and regenerated by
// internal/nativespine.TestListArgsCodegenGolden. It imports only
// context/bamlutils/bamlutils/promptdescriptor/stdlib — no baml_client, no BAML
// runtime, no CFFI.
//
// It is the emitted half of the widening's serving proof: the live-oracle
// differentials in internal/nativebody/nanollmprepare/staticserve register THIS
// binding against a spine project built from the SAME .baml corpus
// (internal/nativespine.ListArgsFixtureSources), so the native leg they compare
// against stock BAML is the real generated one rather than a hand-written stand-in.
//
// Unlike internal/nativespinejsonfixture it carries no runtime.go/adapter.go: the
// native-only worker-boot behaviour of this cohort is proven directly against
// spine.NewWorkerRuntime (nativeserve/spine/executor_listinput_test.go), so a
// second pure-Go worker.Runtime here would be an unused copy.
package nativespinelistfixture
