{
 "title": "baml-rest",
 "description": "Process status and runtime metrics published by Go Prometheus client.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bamlrest_go_goroutines, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bamlrest_go_goroutines{job=~\"$job\"}, instance)"
   },
   {
    "name": "process",
    "label": "Process",
    "query": "label_values(bamlrest_go_goroutines{job=~\"$job\", instance=~\"$instance\"}, process)"
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "bamlrest_go_gc_duration_seconds{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}",
       "legendFormat": "{{instance}}/{{process}}: {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "file descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bamlrest_process_open_fds{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}",
       "legendFormat": "{{instance}}/{{process}}"
      }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "deriv(bamlrest_process_open_fds{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{instance}}/{{process}}"
      }
     ]
    }
   ]
  },
  {
   "title": "goroutine stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bamlrest_go_goroutines{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}",
       "legendFormat": "{{instance}}/{{process}}"
      }
     ]
    },
    {
     "title": "OS Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bamlrest_go_threads{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}",
       "legendFormat": "{{instance}}/{{process}}"
      }
     ]
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "alloc bytes allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bamlrest_go_memstats_alloc_bytes{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}",
       "legendFormat": "{{instance}}/{{process}} - bytes allocated"
      }
     ]
    },
    {
     "title": "alloc bytes allocated - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(bamlrest_go_memstats_alloc_bytes{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{instance}}/{{process}} - bytes allocated"
      }
     ]
    },
    {
     "title": "stack in use - bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bamlrest_go_memstats_stack_inuse_bytes{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}",
       "legendFormat": "{{instance}}/{{process}} - stack inuse"
      }
     ]
    },
    {
     "title": "stack in use - bytes - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(bamlrest_go_memstats_stack_inuse_bytes{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{instance}}/{{process}} - stack inuse"
      }
     ]
    },
    {
     "title": "heap in use - bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bamlrest_go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}",
       "legendFormat": "{{instance}}/{{process}} - heap inuse"
      }
     ]
    },
    {
     "title": "heap in use - bytes - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(bamlrest_go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{instance}}/{{process}} - heap inuse"
      }
     ]
    },
    {
     "title": "total alloc bytes allocation rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(bamlrest_go_memstats_alloc_bytes_total{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{instance}}/{{process}} - alloc rate"
      }
     ]
    }
   ]
  },
  {
   "title": "process memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "process resident memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bamlrest_process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}",
       "legendFormat": "{{instance}}/{{process}} - resident"
      }
     ]
    },
    {
     "title": "process resident memory derivative",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(bamlrest_process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{instance}}/{{process}} - resident"
      }
     ]
    },
    {
     "title": "process virtual memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bamlrest_process_virtual_memory_bytes{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}",
       "legendFormat": "{{instance}}/{{process}} - virtual"
      }
     ]
    },
    {
     "title": "process virtual memory derivative",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(bamlrest_process_virtual_memory_bytes{job=~\"$job\", instance=~\"$instance\", process=~\"$process\"}[$interval])",
       "legendFormat": "{{instance}}/{{process}} - virtual"
      }
     ]
    }
   ]
  }
 ]
}