//go:build livecffi

// This file is the M3c LIVE-CFFI oracle (scope §5B, final paragraph). It is
// gated behind the `livecffi` build tag AND the BAML_LIVE_CFFI=1 env var because
// it drives the REAL v0.223 generation + hack pipeline and links the BAML CFFI
// runtime (cgo + the native library) — none of which the ordinary CFFI-free
// verification lanes touch. The frozen-reference differential
// (adapters/common/codegen/nativespine_recursion_differential_test.go) copies the
// generated carrier's JSON methods VERBATIM and is the always-on proof; this
// oracle closes the remaining leg — CFFI materialization -> generated carrier ->
// public JSON — by generating a fresh recursive client and round-tripping a
// finite value through the generated `Parse`.
//
// Run with:
//
//	BAML_LIVE_CFFI=1 CGO_ENABLED=1 go test -tags livecffi -run TestNativeSpineM3cLiveCFFIOracle ./cmd/introspect/
//
// It skips (never fails) when the toolchain is unavailable (no npx, no
// BAML_LIVE_CFFI), so a machine without the BAML native toolchain is unaffected.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/invakid404/baml-rest/cmd/hacks/hacks"
)

const liveCFFIBamlVersion = "0.223.0"

// liveRecursiveBaml is the recursive fixture generated by stock baml-cli. Foo
// returns a structural recursive JSON-value alias; ParseFoo coerces raw text into
// the generated `types.JSON` carrier via CFFI (no LLM call).
const liveRecursiveBaml = `type JSON = string | null | int | float | bool | JSON[] | map<string, JSON>

client<llm> GPT4 {
  provider openai
  options { model "gpt-4o" api_key env.OPENAI_API_KEY }
}

function Foo(text: string) -> JSON {
  client GPT4
  prompt #"{{ text }}"#
}
`

// liveOracleMain is the subprocess entry point: it calls the generated Parse.Foo
// with a finite raw JSON and marshals the returned carrier with sonic (the
// serving serializer), printing the bytes on stdout for the parent to compare.
const liveOracleMain = `package main

import (
	"fmt"
	"os"

	"github.com/bytedance/sonic"
	client "liveoracle/baml_client"
)

func main() {
	out, err := client.Parse.Foo(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, "parse:", err)
		os.Exit(1)
	}
	b, err := sonic.Marshal(out)
	if err != nil {
		fmt.Fprintln(os.Stderr, "marshal:", err)
		os.Exit(1)
	}
	os.Stdout.Write(b)
}
`

func TestNativeSpineM3cLiveCFFIOracle(t *testing.T) {
	if os.Getenv("BAML_LIVE_CFFI") == "" {
		t.Skip("set BAML_LIVE_CFFI=1 to run the live CFFI oracle (needs the BAML native toolchain)")
	}
	npx, err := exec.LookPath("npx")
	if err != nil {
		t.Skip("npx not on PATH; skipping live CFFI oracle")
	}
	repoRoot := gateARepoRoot(t)
	patched := filepath.Join(repoRoot, "dynclient", "baml-patched")
	if _, err := os.Stat(filepath.Join(patched, "go.mod")); err != nil {
		t.Skipf("patched BAML module absent at %s; skipping live CFFI oracle", patched)
	}

	work := t.TempDir()

	// 1) Materialize a temp BAML project (fixture + Go generator block) and
	//    generate the stock client with baml-cli via npx.
	bamlSrc := filepath.Join(work, "baml_src")
	if err := os.MkdirAll(bamlSrc, 0o755); err != nil {
		t.Fatal(err)
	}
	writeLiveFile(t, filepath.Join(bamlSrc, "main.baml"), liveRecursiveBaml)
	generatorBody := fmt.Sprintf(`generator liveoracle_target {
  output_type "go"
  output_dir "../generated"
  version "%s"
  client_package_name "liveoracle"
}
`, liveCFFIBamlVersion)
	writeLiveFile(t, filepath.Join(bamlSrc, "generators.baml"), generatorBody)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	gen := exec.CommandContext(ctx, npx, "-y", "@boundaryml/baml@"+liveCFFIBamlVersion, "generate", "--no-version-check")
	gen.Dir = work
	if out, err := gen.CombinedOutput(); err != nil {
		t.Skipf("baml generate failed (offline / npx unavailable?): %v\n%s", err, out)
	}

	// 2) Run the SAME repository hack/coerce steps production uses (never hand-edit
	//    the generated imports): apply lazy_runtime/context_fix hacks and rewrite
	//    the BAML imports onto the committed patched fork.
	srcClient := filepath.Join(work, "generated", "baml_client")
	if _, err := os.Stat(srcClient); err != nil {
		t.Fatalf("generated baml_client missing at %s: %v", srcClient, err)
	}
	patchedModulePath := "github.com/invakid404/baml-rest/dynclient/baml-patched"
	if err := hacks.ApplyAll(liveCFFIBamlVersion, srcClient); err != nil {
		t.Fatalf("apply generated-client hacks: %v", err)
	}
	if err := hacks.RewriteGeneratedClientBAMLImports(srcClient, patchedModulePath); err != nil {
		t.Fatalf("rewrite generated client imports: %v", err)
	}

	// 3) Lay out a hermetic module: the generated client at ./baml_client, the
	//    subprocess main at ./, and a go.mod derived from the repo root (so the
	//    patched fork, engine and sonic resolve). The client's internal imports use
	//    the "liveoracle" prefix set by client_package_name.
	dstClient := filepath.Join(work, "baml_client")
	if err := copyLiveTree(srcClient, dstClient); err != nil {
		t.Fatalf("stage generated client: %v", err)
	}
	writeLiveFile(t, filepath.Join(work, "main.go"), liveOracleMain)
	writeLiveGoMod(t, work, repoRoot, patched, patchedModulePath)

	// 4) Run the generated Parse over a finite JSON and compare canonically to the
	//    native golden (the SAME value the frozen-reference differential freezes).
	//    Parse's jsonish coercion of clean JSON is the identity, so both native and
	//    the generated carrier round-trip the raw value; canonical equality closes
	//    the CFFI-materialization -> generated-carrier -> JSON loop.
	const raw = `{"a":1,"b":"hello","c":[1,2,3],"d":{"e":["f"]},"g":1.5,"h":null}`
	runCtx, runCancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer runCancel()
	run := exec.CommandContext(runCtx, "go", "run", ".", raw)
	run.Dir = work
	run.Env = append(os.Environ(), "CGO_ENABLED=1", "GOWORK=off", "GOFLAGS=-mod=mod")
	genOut, err := run.CombinedOutput()
	if err != nil {
		t.Fatalf("generated Parse subprocess failed: %v\n%s", err, genOut)
	}

	if !liveCanonicalEqual(t, genOut, []byte(raw)) {
		t.Fatalf("live generated carrier JSON diverges from the round-tripped value\n generated: %s\n raw:       %s", genOut, raw)
	}
}

// liveCanonicalEqual reports whether two JSON documents are equal after
// recursive canonicalization (map key order normalized), the parity relation the
// native lane uses for maps.
func liveCanonicalEqual(t *testing.T, a, b []byte) bool {
	t.Helper()
	var av, bv any
	if err := json.Unmarshal(a, &av); err != nil {
		t.Fatalf("generated output is not JSON: %v (%s)", err, a)
	}
	if err := json.Unmarshal(b, &bv); err != nil {
		t.Fatalf("reference is not JSON: %v (%s)", err, b)
	}
	return reflect.DeepEqual(av, bv)
}

func writeLiveFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func copyLiveTree(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644)
	})
}

// writeLiveGoMod derives the hermetic module's go.mod from the repo root go.mod:
// the module is renamed to "liveoracle", the first-party relative replaces are
// pinned to absolute repo paths, and a replace for the patched fork is ensured so
// the rewritten client imports resolve. The repo go.sum is reused verbatim.
func writeLiveGoMod(t *testing.T, work, repoRoot, patched, patchedModulePath string) {
	t.Helper()
	rootMod, err := os.ReadFile(filepath.Join(repoRoot, "go.mod"))
	if err != nil {
		t.Fatalf("read root go.mod: %v", err)
	}
	lines := strings.Split(string(rootMod), "\n")
	var out []string
	for _, ln := range lines {
		trimmed := strings.TrimSpace(ln)
		switch {
		case strings.HasPrefix(trimmed, "module "):
			out = append(out, "module liveoracle")
		case strings.Contains(ln, "=> ./") || strings.Contains(ln, "=> ../"):
			// Pin a relative first-party replace to an absolute path.
			idx := strings.Index(ln, "=>")
			target := strings.TrimSpace(ln[idx+2:])
			out = append(out, ln[:idx]+"=> "+filepath.Join(repoRoot, target))
		default:
			out = append(out, ln)
		}
	}
	body := strings.Join(out, "\n")
	if !strings.Contains(body, patchedModulePath+" =>") {
		body += "\nreplace " + patchedModulePath + " => " + patched + "\n"
	}
	writeLiveFile(t, filepath.Join(work, "go.mod"), body)
	if sum, err := os.ReadFile(filepath.Join(repoRoot, "go.sum")); err == nil {
		writeLiveFile(t, filepath.Join(work, "go.sum"), string(sum))
	}
}
