package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

// deBAMLHelperTemplate is the callback-based native ctx.output_format
// pre-substitution helper, emitted NEXT TO the generated adapter.go
// whenever the de-BAML dynamic method is wired (Options.DeBAMLDynamicMethod
// set and a BuildRequest closure consumes it). Emitting it from codegen —
// rather than relying on a hand-written file in one package — is what lets
// BOTH the dynclient module AND the production server-side generated
// package get the helper, so BAML_REST_USE_DEBAML is live on the REST
// production path and not just for direct dynclient callers (#536).
//
// The helper depends only on public types: bamlutils (the Adapter,
// DeBAMLConfig, DeBAMLRenderFunc seam) and the per-build BAML types
// package (Baml_Rest_Message / Baml_Rest_ContentPart, fixed by
// cmd/build/dynamic.baml). The render callback is injected by the root
// module — the generated package never imports internal/schema +
// outputformat, so it stays buildable as a standalone module.
//
// {{ }} delimiters do not appear in the body, so text/template is safe;
// the only single-brace token is the "{output_format}" string literal.
const deBAMLHelperTemplate = `// Code generated by codegen; DO NOT EDIT.

package {{.Pkg}}

import (
	"strings"

	bamlutils "{{.InterfacesPkg}}"
	types "{{.TypesPkg}}"
)

// deBAMLRendererGetter is the narrow optional interface the adapter
// implements to expose the native ctx.output_format render callback. The
// root module wires the callback (it owns internal/schema + outputformat);
// the generated package only ever calls it through this public-typed seam,
// so it never imports those root internal packages and stays buildable as
// a standalone module.
type deBAMLRendererGetter interface {
	DeBAMLRenderer() bamlutils.DeBAMLRenderFunc
}

// outputFormatPlaceholder is the literal string placeholder the dynamic
// BAML template replaces with ctx.output_format inside plain-string
// message content (cmd/build/dynamic.baml). The native path replaces the
// same token so string-content messages match BAML's behaviour.
const outputFormatPlaceholder = "{output_format}"

// maybeApplyDeBAMLOutputFormat returns the message slice the dynamic
// BuildRequest closures should hand to BAML's Request/StreamRequest. When
// the de-BAML flag is on and the carried schema renders, it returns a
// COPY of msgs with the output-format markers replaced by the natively-
// rendered block; otherwise it returns msgs unchanged.
//
// It NEVER mutates the input slice or its backing parts/content. The
// caller keeps the original slice for the legacy fallback children
// (legacyStreamChildFn / legacyCallChildFn), which must stay BAML-as-today
// — the native seam lives on the BuildRequest route only (route coupling
// tracked in #537). Returning the input unchanged when nothing is
// rewritten avoids any allocation on the flag-off / no-schema / nil-
// callback / render-error paths.
func maybeApplyDeBAMLOutputFormat(adapter bamlutils.Adapter, msgs []types.Baml_Rest_Message) []types.Baml_Rest_Message {
	if !adapter.DeBAMLConfig().Enabled {
		return msgs
	}
	outputSchema := adapter.DeBAMLOutputSchema()
	if outputSchema == nil {
		return msgs
	}
	getter, ok := adapter.(deBAMLRendererGetter)
	if !ok {
		return msgs
	}
	render := getter.DeBAMLRenderer()
	if render == nil {
		return msgs
	}
	block, err := render(outputSchema)
	if err != nil {
		logDeBAMLFallback(adapter, "render native output_format", err)
		return msgs
	}
	return rewriteOutputFormat(msgs, block)
}

// rewriteOutputFormat returns a copy of msgs with every output-format
// marker replaced by block: a structured output_format content part
// becomes a plain text part carrying the block, and a literal
// "{output_format}" token in string content is replaced. The input slice
// and its backing parts/content are never mutated — only-touched messages
// get a fresh parts slice / content pointer in the returned copy.
func rewriteOutputFormat(msgs []types.Baml_Rest_Message, block string) []types.Baml_Rest_Message {
	out := make([]types.Baml_Rest_Message, len(msgs))
	copy(out, msgs)
	for i := range out {
		m := &out[i]
		switch {
		case m.Parts != nil:
			if !hasOutputFormatPart(*m.Parts) {
				continue
			}
			newParts := make([]types.Baml_Rest_ContentPart, len(*m.Parts))
			copy(newParts, *m.Parts)
			for j := range newParts {
				p := &newParts[j]
				if p.Output_format != nil && *p.Output_format {
					text := block
					p.Text = &text
					p.Output_format = nil
				}
			}
			m.Parts = &newParts
		case m.Content != nil:
			if strings.Contains(*m.Content, outputFormatPlaceholder) {
				replaced := strings.ReplaceAll(*m.Content, outputFormatPlaceholder, block)
				m.Content = &replaced
			}
		}
	}
	return out
}

// hasOutputFormatPart reports whether any part is an output_format marker.
func hasOutputFormatPart(parts []types.Baml_Rest_ContentPart) bool {
	for i := range parts {
		if parts[i].Output_format != nil && *parts[i].Output_format {
			return true
		}
	}
	return false
}

// logDeBAMLFallback records a native-render fallback so the BAML-as-today
// path is observable without a user-facing flag. Best-effort: no logger
// installed means no line, never an error to the caller.
func logDeBAMLFallback(adapter bamlutils.Adapter, stage string, err error) {
	if logger := adapter.Logger(); logger != nil {
		logger.Warn("de-BAML output_format fallback to BAML render", "stage", stage, "err", err.Error())
	}
}
`

// deBAMLHelperData parameterizes deBAMLHelperTemplate. Pkg is the
// generated package name; InterfacesPkg and TypesPkg are the bamlutils
// and per-build BAML types import paths.
type deBAMLHelperData struct {
	Pkg           string
	InterfacesPkg string
	TypesPkg      string
}

// deBAMLHelperPath returns the path the helper is written to: debaml.go
// next to the generated adapter.go.
func deBAMLHelperPath(adapterOutputPath string) string {
	return filepath.Join(filepath.Dir(adapterOutputPath), "debaml.go")
}

// maybeWriteDeBAMLHelper emits debaml.go next to adapter.go when the
// de-BAML call was actually emitted into a BuildRequest closure (set via
// g.emittedDeBAMLCall). It is a no-op otherwise, so generic / customer
// adapters that don't wire the de-BAML method carry no helper.
func (g *generator) maybeWriteDeBAMLHelper() {
	if !g.emittedDeBAMLCall {
		return
	}
	tmpl, err := template.New("debaml").Parse(deBAMLHelperTemplate)
	if err != nil {
		panic(fmt.Sprintf("codegen: parse de-BAML helper template: %v", err))
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, deBAMLHelperData{
		Pkg:           g.pkgs.OutputPkgName,
		InterfacesPkg: g.pkgs.InterfacesPkg,
		TypesPkg:      g.pkgs.GeneratedClientPkg + "/types",
	}); err != nil {
		panic(fmt.Sprintf("codegen: execute de-BAML helper template: %v", err))
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(fmt.Sprintf("codegen: gofmt de-BAML helper: %v\n%s", err, buf.String()))
	}
	if err := os.WriteFile(deBAMLHelperPath(g.pkgs.OutputPath), formatted, 0o644); err != nil {
		panic(fmt.Sprintf("codegen: write de-BAML helper: %v", err))
	}
}
