package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

// De-BAML Slice 8B — generated STATIC no-send admission observer helper.
//
// This file emits debaml_static.go next to the generated adapter.go when the
// generator wired at least one static observe call (g.emittedDeBAMLStaticCall). It
// is the STATIC observe-only twin of codegen_debaml.go's debaml.go helper: it holds
// the method-INDEPENDENT observe helpers the per-method call/parse code calls, so
// the per-method code stays a thin descriptor-lookup + arg-binder while the gate
// (de-BAML flag + installed observer) and the neutral invocation build live here.
//
// The helpers are OBSERVE-ONLY: they run the injected native static admission
// observer (which ALWAYS declines) and DISCARD the result, so BAML's
// Request.<Method> / Parse.<Method> serve every request exactly as today. With the
// de-BAML flag off, or no observer installed, they are a cheap no-op.

// deBAMLStaticHelperTemplate is the source of the generated debaml_static.go. Pkg
// is the generated package name; BamlutilsPkg / PromptDescriptorPkg / LLMHTTPPkg are
// the bamlutils, bamlutils/promptdescriptor, and bamlutils/llmhttp import paths.
const deBAMLStaticHelperTemplate = `// Code generated by codegen; DO NOT EDIT.

package {{.Pkg}}

import (
	"context"
	"fmt"

	bamlutils "{{.BamlutilsPkg}}"
	buildrequest "{{.BuildRequestPkg}}"
	llmhttp "{{.LLMHTTPPkg}}"
	promptdescriptor "{{.PromptDescriptorPkg}}"
)

// nativeStaticObserverGetter is the narrow optional interface the adapter
// implements to expose the installed native STATIC no-send admission observer
// (de-BAML Slice 8B). It is kept off the bamlutils.Adapter interface so test
// doubles need not implement it.
type nativeStaticObserverGetter interface {
	NativeStaticObserver() bamlutils.NativeStaticObserveFunc
}

// deBAMLStaticObserver returns the installed native static observer when the de-BAML
// umbrella flag is on AND an observer is wired (a native worker), else nil — the
// hard-off default that keeps every request byte-identical BAML. The generated
// call/parse seam checks this FIRST, so with the flag off (or no observer) it never
// performs the StaticPromptDescriptor lookup or builds the argument binder: the path
// is the byte-identical, no-lookup BAML path.
func deBAMLStaticObserver(adapter bamlutils.Adapter) bamlutils.NativeStaticObserveFunc {
	if !adapter.DeBAMLConfig().Enabled {
		return nil
	}
	getter, ok := adapter.(nativeStaticObserverGetter)
	if !ok {
		return nil
	}
	return getter.NativeStaticObserver()
}

// maybeObserveDeBAMLStaticFinal runs the de-BAML Slice 8B STATIC unary FINAL no-send
// admission observation for one eligible static /call and DISCARDS the result: the
// observer ALWAYS declines, so BAML's Request.<Method> serves exactly as today. It
// opens no socket and RoundTrips nothing. SENSITIVE: fn/args/buildBAMLRequest carry
// secret material; this never logs, serializes, or emits them.
//
// observe is the ALREADY-RESOLVED, non-nil observer (the caller gated the whole
// descriptor lookup on deBAMLStaticObserver being non-nil, so flag-off never reaches
// here). The caller forwards the ACTUAL selected-route facts (resolved leaf provider,
// selected client override, single-leaf / fallback-chain / round-robin shape, the
// call-with-raw flag, and hasRetry — whether the EFFECTIVE resolved retry policy is
// non-nil) so the observer's conservative gates decline every non-default-route /
// call-with-raw / retrying request TRUTHFULLY rather than recording a false
// would-admit. hasRetry MUST be retryPolicy != nil — the SAME resolved policy that
// flows into CallConfig.RetryPolicy (ResolveStrategyAwareRetryPolicy), so a
// per-request override, a runtime client-registry policy, AND a static introspected
// client policy all decline; adapter.RetryConfig() alone would miss the latter two.
// The rewrite/proxy fact is derived from the adapter here, matching the dynamic seam.
func maybeObserveDeBAMLStaticFinal(
	observe bamlutils.NativeStaticObserveFunc,
	adapter bamlutils.Adapter,
	fn promptdescriptor.Function,
	args map[string]any,
	argOrder []string,
	provider string,
	clientOverride string,
	singleLeaf bool,
	hasFallbackChain bool,
	hasRoundRobin bool,
	hasRetry bool,
	raw bool,
	buildBAMLRequest func(context.Context) (*llmhttp.Request, error),
) {
	// The effective send client (the exact client BAML would send through), whose
	// WouldRewriteOrProxy applies rewrites/proxying at execution time; nil falls back
	// to the default client, exactly as the BuildRequest route resolves it.
	httpClient := adapter.HTTPClient()
	if httpClient == nil {
		httpClient = llmhttp.DefaultClient
	}
	// Build the invocation payload SYNCHRONOUSLY (cheap; captures the already-bound
	// args/descriptor/closures from the request goroutine), then hand it to
	// buildrequest.ObserveStaticFireAndForget, which runs the discarded observation on
	// its OWN goroutine with a LOCAL deferred recover that DROPS any recovered value
	// (never formats/logs it, never uses a process-global recovery handler) and emits
	// only a fixed, payload-free breadcrumb. The observation is best-effort and
	// observe-only (it always declines, opens no socket, RoundTrips nothing), so
	// decoupling it means an observer panic or its full pre-socket work can never block
	// or crash the request goroutine; its result was already discarded, so BAML serves
	// exactly as today.
	inv := bamlutils.NativeStaticInvocation{
		Method:                  fn.Method,
		Descriptor:              fn,
		Args:                    args,
		ArgOrder:                argOrder,
		Mode:                    bamlutils.NativeStaticModeFinal,
		Provider:                provider,
		ClientOverride:          clientOverride,
		SingleLeaf:              singleLeaf,
		HasFallbackChain:        hasFallbackChain,
		HasRoundRobin:           hasRoundRobin,
		HasRequestRetryOverride: hasRetry,
		Raw:                     raw,
		WouldRewriteOrProxy:     httpClient.WouldRewriteOrProxy,
		BuildBAMLRequest:        buildBAMLRequest,
	}
	// Fire-and-forget: the local deferred recover inside ObserveStaticFireAndForget
	// DROPS any recovered value (never logs the descriptor/plan/credential/body
	// payload) — no process-global recovery handler is involved.
	buildrequest.ObserveStaticFireAndForget(observe, inv)
}

// maybeObserveDeBAMLStaticParse runs the de-BAML Slice 8B STATIC PARSE-ONLY no-send
// admission observation for one eligible static /parse and DISCARDS the result: the
// observer ALWAYS declines, so BAML's Parse.<Method> serves exactly as today. It
// measures the Return-Bundle native-final support only — no prompt render, body
// build, or provider plan is involved. observe is the already-resolved, non-nil
// observer (the caller gated the descriptor lookup on it).
func maybeObserveDeBAMLStaticParse(observe bamlutils.NativeStaticObserveFunc, fn promptdescriptor.Function) {
	// Build the invocation synchronously, then hand it to ObserveStaticFireAndForget
	// (same LOCAL payload-dropping deferred-recover dispatch as the final hook) so an
	// observer panic or its pre-socket work can never block or crash the parse request
	// goroutine. The result was already discarded; BAML's Parse serves exactly as today.
	inv := bamlutils.NativeStaticInvocation{
		Method:     fn.Method,
		Descriptor: fn,
		Mode:       bamlutils.NativeStaticModeParseOnly,
		Provider:   fn.Provider,
		SingleLeaf: true,
	}
	// Fire-and-forget with LOCAL, payload-redacted panic containment (see the final
	// hook) — never blocks/crashes the parse request goroutine, never logs the payload.
	buildrequest.ObserveStaticFireAndForget(observe, inv)
}

// nativeStaticServeGetter is the SERVE twin of nativeStaticObserverGetter (de-BAML
// Slice 8C): the narrow optional interface the adapter implements to expose the
// installed native STATIC SERVE implementation. Kept off bamlutils.Adapter.
type nativeStaticServeGetter interface {
	NativeStaticServeComparator() bamlutils.NativeStaticServeFunc
}

// deBAMLStaticServe returns the installed native static serve implementation when the
// de-BAML umbrella flag is on AND a serve callback is wired (a SERVE-profile worker),
// else nil — the hard-off default that keeps every static request byte-identical BAML.
// The generated /call seam checks this FIRST, so with the flag off (or no serve
// callback) it never performs the StaticPromptDescriptor lookup, builds the argument
// binder, or installs a native attempt: the path is the byte-identical BAML path.
func deBAMLStaticServe(adapter bamlutils.Adapter) bamlutils.NativeStaticServeFunc {
	if !adapter.DeBAMLConfig().Enabled {
		return nil
	}
	getter, ok := adapter.(nativeStaticServeGetter)
	if !ok {
		return nil
	}
	return getter.NativeStaticServeComparator()
}

// installNativeStaticCall installs the de-BAML Slice 8C native STATIC SERVE attempt as
// the Slice-1 CallConfig.NativeAttempt for one eligible static /call. When the
// orchestrator runs the attempt it builds the neutral NativeStaticInvocation from the
// selected descriptor + exact args + the ACTUAL selected-route facts (provider /
// clientOverride / include-reasoning / heartbeat / the no-send BAML plan from att),
// calls the injected NativeStaticServeFunc, and maps the tri-state outcome:
//
//   - Succeeded: decode the winning flattened canonical JSON into the method's exact
//     concrete return type via the per-method decodeFinal closure
//     (bamlutils.DecodeStaticFinal[Return]) and serve it with the owned raw/reasoning
//     + winner engine. A decode failure is a POST-CLAIM failure (never a resend).
//   - Declined: PRE-SOCKET decline; the orchestrator runs BAML's Request.<Method> /
//     Parse.<Method> for the same call exactly as today.
//   - Failed: a POST-CLAIM typed failure to the outer policy; never a BAML resend.
//
// serve is the ALREADY-RESOLVED, non-nil serve callback (the caller gated the whole
// descriptor lookup + binder + closure construction on deBAMLStaticServe being
// non-nil, so flag-off never reaches here). bamlOnlyParse is the per-method
// Parse.<Method>-on-the-same-bytes closure (the S5 differential/safety comparator);
// decodeFinal is the per-method concrete-return-type decoder. Both are built by the
// generated /call seam because they reference the method's concrete return type.
//
// SENSITIVE: fn/args/bamlOnlyParse/decodeFinal all carry secret material; this never
// logs, serializes, or emits them.
func installNativeStaticCall(
	cfg *buildrequest.CallConfig,
	serve bamlutils.NativeStaticServeFunc,
	adapter bamlutils.Adapter,
	fn promptdescriptor.Function,
	args map[string]any,
	argOrder []string,
	singleLeaf bool,
	hasFallbackChain bool,
	hasRoundRobin bool,
	hasRetry bool,
	raw bool,
	bamlOnlyParse func(ctx context.Context, rawText string) ([]byte, error),
	decodeFinal func(canonicalJSON []byte) (any, error),
) {
	// The effective send client (the exact client BAML would send through), whose
	// WouldRewriteOrProxy applies rewrites/proxying at execution time; nil falls back
	// to the default client, matching the observe seam + the BuildRequest route.
	httpClient := adapter.HTTPClient()
	if httpClient == nil {
		httpClient = llmhttp.DefaultClient
	}
	// planned_engine="native": a serve callback was installed and native was considered
	// for this static /call (recorded on the OUTCOME frame; empty on every default/BAML/
	// flag-off path so metadata stays byte-identical). Mirrors the dynamic serve seam.
	cfg.PlannedEngine = "native"
	cfg.NativeAttemptEnabled = true
	cfg.NativeAttempt = func(ctx context.Context, att buildrequest.NativeCallAttempt) buildrequest.NativeCallOutcome {
		inv := bamlutils.NativeStaticInvocation{
			Method:                  fn.Method,
			Descriptor:              fn,
			Args:                    args,
			ArgOrder:                argOrder,
			Mode:                    bamlutils.NativeStaticModeFinal,
			Provider:                att.Provider,
			ClientOverride:          att.ClientOverride,
			SingleLeaf:              singleLeaf,
			HasFallbackChain:        hasFallbackChain,
			HasRoundRobin:           hasRoundRobin,
			HasRequestRetryOverride: hasRetry,
			Raw:                     raw,
			IncludeReasoning:        att.IncludeReasoning,
			WouldRewriteOrProxy:     httpClient.WouldRewriteOrProxy,
			BuildBAMLRequest:        att.BuildBAMLRequest,
			BAMLOnlyParse:           bamlOnlyParse,
			SendHeartbeat:           att.SendHeartbeat,
		}
		res := serve(ctx, inv)
		switch res.Disposition {
		case bamlutils.NativeStaticServeSucceeded:
			final, derr := decodeFinal(res.FinalJSON)
			if derr != nil {
				// A post-claim decode failure cannot fall through to a BAML resend;
				// FAIL, retaining the owned raw assistant text as details.raw.
				return buildrequest.FailNativeCallWithRaw(&buildrequest.OutputParseError{Err: derr}, res.Raw)
			}
			outcome := buildrequest.SucceedNativeCall(final, res.Raw, res.Reasoning)
			outcome.WinnerEngine = res.WinnerEngine
			return outcome
		case bamlutils.NativeStaticServeFailed:
			return buildrequest.FailNativeCallWithRaw(res.Err, res.RawDiagnostic)
		case bamlutils.NativeStaticServeDeclined:
			return buildrequest.DeclineNativeCall(
				buildrequest.NativeDeclineStage(res.Stage),
				buildrequest.NativeDeclineReason(res.Reason),
			)
		default:
			// Out-of-contract disposition (the result is public + integer-backed): it
			// CANNOT assert "no socket", so fail closed rather than risk a hidden second
			// same-call BAML send. Unreachable for the closed NativeStaticServe* set.
			return buildrequest.FailNativeCall(
				fmt.Errorf("native static serve returned unknown disposition %d", res.Disposition),
			)
		}
	}
}

// nativeStaticShadowGetter is the Stage-1 SHADOW twin of nativeStaticServeGetter
// (de-BAML Slice 8C): the narrow optional interface the adapter implements to expose
// the installed native static SHADOW comparator. Kept off bamlutils.Adapter.
type nativeStaticShadowGetter interface {
	NativeStaticShadowComparator() bamlutils.NativeStaticShadowFunc
}

// deBAMLStaticShadow returns the installed native static SHADOW comparator when the
// de-BAML umbrella flag is on AND a shadow callback is wired (a SHADOW-profile
// worker), else nil. The generated /call seam resolves serve FIRST, then shadow, so
// the shadow runs only when no serve callback is installed. Flag-off (or no shadow
// callback) is a single cheap type-assertion returning nil — byte-identical BAML.
func deBAMLStaticShadow(adapter bamlutils.Adapter) bamlutils.NativeStaticShadowFunc {
	if !adapter.DeBAMLConfig().Enabled {
		return nil
	}
	getter, ok := adapter.(nativeStaticShadowGetter)
	if !ok {
		return nil
	}
	return getter.NativeStaticShadowComparator()
}

// installNativeStaticShadow installs the de-BAML Slice 8C Stage-1 SHADOW comparison as
// the Slice-1 CallConfig.NativeAttempt for one eligible static /call. The comparison
// ALWAYS DECLINES so BAML remains the SOLE sender; on a full plan match it threads an
// OnResponse continuation onto the declined outcome (OnResponseShadow) that the
// orchestrator invokes with BAML's already-fetched bytes — native then compares its
// translate/extract/static-SAP/typed-decode against BAML's parse of the SAME bytes
// with ZERO native sends. bamlOnlyParse is the per-method Parse.<Method> comparator;
// decodeFinal is the per-method concrete-return-type decoder (used for the typed-
// result facet). Both are built by the generated seam (they reference the method's
// return type). shadow is the ALREADY-RESOLVED, non-nil comparator.
//
// SENSITIVE: fn/args/bamlOnlyParse/decodeFinal carry secret material; never logged.
func installNativeStaticShadow(
	cfg *buildrequest.CallConfig,
	shadow bamlutils.NativeStaticShadowFunc,
	adapter bamlutils.Adapter,
	fn promptdescriptor.Function,
	args map[string]any,
	argOrder []string,
	singleLeaf bool,
	hasFallbackChain bool,
	hasRoundRobin bool,
	hasRetry bool,
	raw bool,
	bamlOnlyParse func(ctx context.Context, rawText string) ([]byte, error),
	decodeFinal func(canonicalJSON []byte) (any, error),
) {
	httpClient := adapter.HTTPClient()
	if httpClient == nil {
		httpClient = llmhttp.DefaultClient
	}
	// planned_engine="native": native was CONSIDERED (shadow) for this static /call.
	cfg.PlannedEngine = "native"
	cfg.NativeAttemptEnabled = true
	cfg.NativeAttempt = func(ctx context.Context, att buildrequest.NativeCallAttempt) buildrequest.NativeCallOutcome {
		inv := bamlutils.NativeStaticInvocation{
			Method:                  fn.Method,
			Descriptor:              fn,
			Args:                    args,
			ArgOrder:                argOrder,
			Mode:                    bamlutils.NativeStaticModeFinal,
			Provider:                att.Provider,
			ClientOverride:          att.ClientOverride,
			SingleLeaf:              singleLeaf,
			HasFallbackChain:        hasFallbackChain,
			HasRoundRobin:           hasRoundRobin,
			HasRequestRetryOverride: hasRetry,
			Raw:                     raw,
			IncludeReasoning:        att.IncludeReasoning,
			WouldRewriteOrProxy:     httpClient.WouldRewriteOrProxy,
			BuildBAMLRequest:        att.BuildBAMLRequest,
			BAMLOnlyParse:           bamlOnlyParse,
			DecodeNativeFinal:       decodeFinal,
		}
		res := shadow(ctx, inv)
		// The shadow ALWAYS declines so BAML serves; thread OnResponse onto the declined
		// outcome so the orchestrator runs the same-response comparison over BAML's
		// captured bytes AFTER BAML serves. Native NEVER sends.
		outcome := buildrequest.DeclineNativeCall(
			buildrequest.NativeDeclineStage(res.Stage),
			buildrequest.NativeDeclineReason(res.Reason),
		)
		outcome.OnResponseShadow = res.OnResponse
		return outcome
	}
}
`

// deBAMLStaticHelperData parameterizes deBAMLStaticHelperTemplate.
type deBAMLStaticHelperData struct {
	Pkg                 string
	BamlutilsPkg        string
	BuildRequestPkg     string
	PromptDescriptorPkg string
	LLMHTTPPkg          string
}

// deBAMLStaticHelperPath returns the path the static helper is written to:
// debaml_static.go next to the generated adapter.go.
func deBAMLStaticHelperPath(adapterOutputPath string) string {
	return filepath.Join(filepath.Dir(adapterOutputPath), "debaml_static.go")
}

// maybeWriteDeBAMLStaticHelper emits debaml_static.go next to adapter.go when a
// static observe call was actually emitted (g.emittedDeBAMLStaticCall). It is a
// no-op otherwise, so generic / customer / pre-0.219 adapters carry no static helper
// and any stale helper a previous generation left is removed.
func (g *generator) maybeWriteDeBAMLStaticHelper() {
	helperPath := deBAMLStaticHelperPath(g.pkgs.OutputPath)
	if !g.emittedDeBAMLStaticCall {
		// No static observe call was emitted, so remove any helper a previous
		// generation left in this directory (mirrors maybeWriteDeBAMLHelper).
		if err := os.Remove(helperPath); err != nil && !os.IsNotExist(err) {
			panic(fmt.Sprintf("codegen: remove stale de-BAML static helper: %v", err))
		}
		return
	}
	tmpl, err := template.New("debaml_static").Parse(deBAMLStaticHelperTemplate)
	if err != nil {
		panic(fmt.Sprintf("codegen: parse de-BAML static helper template: %v", err))
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, deBAMLStaticHelperData{
		Pkg:                 g.pkgs.OutputPkgName,
		BamlutilsPkg:        g.pkgs.InterfacesPkg,
		BuildRequestPkg:     g.pkgs.BuildRequestPkg,
		PromptDescriptorPkg: g.pkgs.InterfacesPkg + "/promptdescriptor",
		LLMHTTPPkg:          g.pkgs.LLMHTTPPkg,
	}); err != nil {
		panic(fmt.Sprintf("codegen: execute de-BAML static helper template: %v", err))
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(fmt.Sprintf("codegen: gofmt de-BAML static helper: %v\n%s", err, buf.String()))
	}
	if err := os.WriteFile(helperPath, formatted, 0o644); err != nil {
		panic(fmt.Sprintf("codegen: write de-BAML static helper: %v", err))
	}
}
