package codegen

import (
	"strings"
	"testing"

	"github.com/invakid404/baml-rest/bamlutils/projectdescriptor"
	sd "github.com/invakid404/baml-rest/bamlutils/schemadescriptor"
)

// nativespine_stream_test.go is the M3e-A emitter unit proof: for a ClassStaticStream
// method the emitter produces TWO carrier aliases over ONE union implementation, the
// two DISTINCT decoders (final = value carrier, partial = pointer carrier), a
// StreamBinding that embeds the unary Binding, a CLOSED three-mode BuildMethod, a
// non-nil ParseMethod.StreamImpl, and a MakeStreamOutput whose pointer level is the
// stream carrier itself — never a pointer to it.
//
// The BEHAVIORAL half of the proof (event -> StreamResult mapping, raw-only frames,
// typed-nil preservation, frozen /call dispatch, terminal wrapping) lives with the
// real emitted fixture in internal/nativespinejsonfixture, which drives this exact
// output against a fake stream executor.

// streamJSONAliasMethod is the exact five-arm `JSON` recursive alias — the ONLY family
// debaml.SupportsNativeStaticStreamBundle admits, and therefore the only shape that is
// ever stamped ClassStaticStream: `int | string | bool | JSON[] | map<string, JSON>`.
func streamJSONAliasMethod() projectdescriptor.Method {
	return projectdescriptor.Method{
		Name:  "StaticRecursiveAliasJSON",
		Class: projectdescriptor.ClassStaticStream,
		Return: sd.Bundle{
			Version: sd.Version, Method: "StaticRecursiveAliasJSON", Target: recAlias("JSON"),
			StructuralRecursiveAliases: []sd.RecursiveAliasDef{
				{Name: "JSON", Target: recUnion(false,
					recPrim(sd.PrimitiveInt), recPrim(sd.PrimitiveString), recPrim(sd.PrimitiveBool),
					recList(recAlias("JSON")), recStrMap(recAlias("JSON")),
				)},
			},
		},
	}
}

// emitStreamDeterministic emits m twice through the stream emitter and requires
// byte-identical source, returning it.
func emitStreamDeterministic(t *testing.T, m projectdescriptor.Method, pkg string) string {
	t.Helper()
	src, err := EmitNativeStaticStream(m, NativeSpineOptions{PackageName: pkg})
	if err != nil {
		t.Fatalf("EmitNativeStaticStream: %v", err)
	}
	src2, err := EmitNativeStaticStream(m, NativeSpineOptions{PackageName: pkg})
	if err != nil {
		t.Fatal(err)
	}
	if string(src) != string(src2) {
		t.Fatal("EmitNativeStaticStream is not deterministic")
	}
	return string(src)
}

// TestEmitNativeStaticStreamCarriersAndBinding pins the whole emitted stream surface.
func TestEmitNativeStaticStreamCarriersAndBinding(t *testing.T) {
	src := emitStreamDeterministic(t, streamJSONAliasMethod(), "streampkg")

	for _, want := range []string{
		// The generated-by header names the STREAM emitter, so a stale regeneration is
		// visible in the committed file itself.
		"// Code generated by adapters/common/codegen EmitNativeStaticStream; DO NOT EDIT.",
		// TWO aliases over ONE union implementation: the FINAL value carrier and the
		// STREAM pointer carrier (BAML v0.223's types.JSON vs stream_types.JSON).
		"type OutputJson = OutputUnion1",
		"type OutputJsonStream = *OutputUnion1",
		// Exactly one union implementation is emitted — the stream alias is not a
		// second one and not an `any` fallback.
		"type OutputUnion1 struct",
		// The two decoders are DISTINCT and instantiated with the matching carrier.
		"return bamlutils.DecodeStaticAliasFinal[OutputJson](canonicalJSON)",
		"return bamlutils.DecodeStaticAliasStream[OutputJsonStream](canonicalJSON)",
		// MakeStreamOutput's pointer level, stated as a typed local so the compiler
		// checks it: an OutputJsonStream, NOT a **OutputUnion1.
		"var v OutputJsonStream = new(OutputJson)",
		"MakeStreamOutput: makeStreamOutput,",
		// StreamBinding EMBEDS the unary Binding — one projector, one final decoder.
		"func StreamBinding() bamlutils.NativeSpineStreamBinding {",
		"Unary:         Binding(),",
		"DecodePartial: decodePartial,",
		// The CLOSED three-mode switch.
		"case bamlutils.StreamModeCall:",
		"case bamlutils.StreamModeStream, bamlutils.StreamModeStreamWithRaw:",
		"return nil, fmt.Errorf(\"%w (got mode %d)\", ErrUnsupportedStreamMode, mode)",
		// The stream arms require a stream-capable executor and say so in a typed way.
		"sx, ok := exec.(bamlutils.NativeSpineStreamExecutor)",
		"return nil, errNoStreamExecutor",
		// ParseMethod.StreamImpl is NATIVE and non-nil (the socket-free stream parse).
		"StreamImpl: func(adapter bamlutils.Adapter, raw string) (any, error) {",
		"return sx.ParseStream(adapter, MethodName, raw)",
		// BuildMethod keeps the UNARY parameter type, so the frozen unary registration
		// path and existing generated code keep compiling.
		"func BuildMethod(exec bamlutils.NativeSpineUnaryExecutor) (bamlutils.StreamingMethod, bamlutils.ParseMethod)",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("emitted ClassStaticStream source missing %q", want)
		}
	}

	for _, bad := range []string{
		// The double-pointer carrier is the exact mistake the design calls out.
		"new(OutputJsonStream)",
		"**OutputUnion1",
		// The FINAL must never be decoded through the stream decoder, nor the partial
		// through the final one.
		"DecodeStaticAliasStream[OutputJson]",
		"DecodeStaticAliasFinal[OutputJsonStream]",
		// A stream method must never carry a nil StreamImpl (that is the unary shape).
		"StreamImpl: nil",
	} {
		if strings.Contains(src, bad) {
			t.Errorf("emitted ClassStaticStream source contains forbidden %q", bad)
		}
	}
}

// TestEmitNativeStaticStreamUnaryTailUnchanged proves the two class emitters share one
// core: emitting the SAME return bundle under each class differs ONLY by the streaming
// delta. The carriers, the object codec, the recursion guard, the input projector, the
// final decoder, and Binding() are byte-identical, so a stream method's carrier bytes
// can never drift from a unary method's.
func TestEmitNativeStaticStreamUnaryTailUnchanged(t *testing.T) {
	m := streamJSONAliasMethod()
	streamSrc := emitStreamDeterministic(t, m, "streampkg")

	unary := m
	unary.Class = projectdescriptor.ClassStaticUnary
	unarySrc, err := EmitNativeStaticUnary(unary, NativeSpineOptions{PackageName: "streampkg"})
	if err != nil {
		t.Fatalf("EmitNativeStaticUnary: %v", err)
	}

	// The shared prefix runs from the package clause through the union carrier — every
	// carrier declaration — and must be identical up to the stream alias, which is the
	// first streaming-only declaration.
	const marker = "// OutputJsonStream is the generated STREAM carrier"
	idx := strings.Index(streamSrc, marker)
	if idx < 0 {
		t.Fatalf("stream source has no stream carrier declaration")
	}
	sharedPrefix := streamSrc[:idx]
	// Skip the differing generated-by header line on both sides.
	trimHeader := func(s string) string {
		if i := strings.Index(s, "\n"); i >= 0 {
			return s[i:]
		}
		return s
	}
	if !strings.HasPrefix(trimHeader(string(unarySrc)), trimHeader(sharedPrefix)) {
		t.Error("the ClassStaticStream carrier prefix diverges from the ClassStaticUnary one; the two emitters must share one carrier core")
	}
	// The unary product itself must be untouched by M3e-A.
	for _, bad := range []string{"OutputJsonStream", "StreamBinding", "decodePartial", "makeStreamOutput", "NativeSpineStreamExecutor"} {
		if strings.Contains(string(unarySrc), bad) {
			t.Errorf("ClassStaticUnary emission gained streaming declaration %q", bad)
		}
	}
	if !strings.Contains(string(unarySrc), "StreamImpl: nil") {
		t.Error("ClassStaticUnary emission lost its nil StreamImpl (the unary product must stay frozen)")
	}
}

// TestEmitNativeStaticClassGatesAreExact proves each emitter accepts ONLY its own
// class. A class mix-up would silently emit the wrong capability surface for a
// descriptor — a stream-stamped method with no stream binding, or a unary-stamped one
// that claims a socket for /stream.
func TestEmitNativeStaticClassGatesAreExact(t *testing.T) {
	m := streamJSONAliasMethod()

	if _, err := EmitNativeStaticUnary(m, NativeSpineOptions{PackageName: "p"}); err == nil {
		t.Error("EmitNativeStaticUnary accepted a ClassStaticStream method")
	}
	unary := m
	unary.Class = projectdescriptor.ClassStaticUnary
	if _, err := EmitNativeStaticStream(unary, NativeSpineOptions{PackageName: "p"}); err == nil {
		t.Error("EmitNativeStaticStream accepted a ClassStaticUnary method")
	}
	if _, err := EmitNativeStaticStream(m, NativeSpineOptions{}); err == nil {
		t.Error("EmitNativeStaticStream accepted an empty PackageName")
	}
}

// TestEmitNativeStaticStreamRequiresAliasTarget is the fail-closed backstop for a
// descriptor stamped ClassStaticStream past the population predicate: a return whose
// target is not a structural recursive alias has no carrier this emitter can name, so
// it must ERROR rather than emit a wrong or absent stream carrier.
func TestEmitNativeStaticStreamRequiresAliasTarget(t *testing.T) {
	scalar := projectdescriptor.Method{
		Name:  "Scalar",
		Class: projectdescriptor.ClassStaticStream,
		Return: sd.Bundle{
			Version: sd.Version, Method: "Scalar", Target: recPrim(sd.PrimitiveString),
		},
	}
	_, err := EmitNativeStaticStream(scalar, NativeSpineOptions{PackageName: "p"})
	if err == nil {
		t.Fatal("EmitNativeStaticStream emitted a scalar-return stream method")
	}
	if !strings.Contains(err.Error(), "structural recursive alias return target") {
		t.Fatalf("decline reason %q does not name the missing alias target", err)
	}
}

// TestEmitNativeStaticStreamCarrierCollisionDeclined proves the stream carrier name is
// collision-checked: an alias `JSON` beside a class `JSONStream` would emit two
// declarations of OutputJsonStream, which go/format accepts and the Go compiler
// rejects. Fail closed at emission instead.
func TestEmitNativeStaticStreamCarrierCollisionDeclined(t *testing.T) {
	m := streamJSONAliasMethod()
	m.Return.Classes = []sd.ClassDef{{
		Name:   sd.Name{Name: "JSONStream"},
		Fields: []sd.ClassField{{Name: sd.Name{Name: "v"}, Type: recPrim(sd.PrimitiveString)}},
	}}
	_, err := EmitNativeStaticStream(m, NativeSpineOptions{PackageName: "p"})
	if err == nil {
		t.Fatal("EmitNativeStaticStream emitted a colliding stream carrier")
	}
	if !strings.Contains(err.Error(), "collides") {
		t.Fatalf("decline reason %q does not name the collision", err)
	}
}
