// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
    "encoding/json"
    "fmt"

    baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
    "github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)


type DynamicTestOutput struct {
    
    DynamicProperties map[string]any
}

func (c *DynamicTestOutput) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "DynamicTestOutput" {
		panic(fmt.Sprintf("expected DynamicTestOutput, got %s", typeName.Name))
	}

   
   c.DynamicProperties = make(map[string]any)
   

	
}

func (c DynamicTestOutput) Encode() (*cffi.CFFIValueHolder, error) {
    fields := map[string]any{}
    
    return baml.EncodeClass(c.BamlEncodeName, fields, &c.DynamicProperties)
}

func (c DynamicTestOutput) BamlTypeName() string {
    return "DynamicTestOutput"
}

func (u DynamicTestOutput) BamlEncodeName() *cffi.CFFITypeName {
    return &cffi.CFFITypeName{
        Namespace: cffi.CFFITypeNamespace_TYPES,
        Name:      "DynamicTestOutput",
    }
}

type Resume struct {
    
Name string `json:"name"`
Email string `json:"email"`
Experience []string `json:"experience"`
Skills []string `json:"skills"`
    
}

func (c *Resume) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Resume" {
		panic(fmt.Sprintf("expected Resume, got %s", typeName.Name))
	}

   

	
	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
			switch key {
				
				case "name":
					c.Name = baml.Decode(valueHolder).Interface().(string)
				
				case "email":
					c.Email = baml.Decode(valueHolder).Interface().(string)
				
				case "experience":
					c.Experience = baml.Decode(valueHolder).Interface().([]string)
				
				case "skills":
					c.Skills = baml.Decode(valueHolder).Interface().([]string)
				
		default:
			
			panic(fmt.Sprintf("unexpected field: %s in class Resume", key))
			
		}
	}

}

func (c Resume) Encode() (*cffi.CFFIValueHolder, error) {
    fields := map[string]any{}
    
    fields["name"] = c.Name
    
    fields["email"] = c.Email
    
    fields["experience"] = c.Experience
    
    fields["skills"] = c.Skills
    
    return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Resume) BamlTypeName() string {
    return "Resume"
}

func (u Resume) BamlEncodeName() *cffi.CFFITypeName {
    return &cffi.CFFITypeName{
        Namespace: cffi.CFFITypeNamespace_TYPES,
        Name:      "Resume",
    }
}

type Resume2 struct {
    
Name string `json:"name"`
Email string `json:"email"`
Experience []string `json:"experience"`
Skills []string `json:"skills"`
Maikati Union2Resume3OrResume4 `json:"maikati"`
Bashtati Resume3 `json:"bashtati"`
Sestrati Resume4 `json:"sestrati"`
Dqdoti ChichoTi `json:"dqdoti"`
    
}

func (c *Resume2) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Resume2" {
		panic(fmt.Sprintf("expected Resume2, got %s", typeName.Name))
	}

   

	
	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
			switch key {
				
				case "name":
					c.Name = baml.Decode(valueHolder).Interface().(string)
				
				case "email":
					c.Email = baml.Decode(valueHolder).Interface().(string)
				
				case "experience":
					c.Experience = baml.Decode(valueHolder).Interface().([]string)
				
				case "skills":
					c.Skills = baml.Decode(valueHolder).Interface().([]string)
				
				case "maikati":
					c.Maikati = baml.Decode(valueHolder).Interface().(Union2Resume3OrResume4)
				
				case "bashtati":
					c.Bashtati = baml.Decode(valueHolder).Interface().(Resume3)
				
				case "sestrati":
					c.Sestrati = baml.Decode(valueHolder).Interface().(Resume4)
				
				case "dqdoti":
					c.Dqdoti = baml.Decode(valueHolder).Interface().(ChichoTi)
				
		default:
			
			panic(fmt.Sprintf("unexpected field: %s in class Resume2", key))
			
		}
	}

}

func (c Resume2) Encode() (*cffi.CFFIValueHolder, error) {
    fields := map[string]any{}
    
    fields["name"] = c.Name
    
    fields["email"] = c.Email
    
    fields["experience"] = c.Experience
    
    fields["skills"] = c.Skills
    
    fields["maikati"] = c.Maikati
    
    fields["bashtati"] = c.Bashtati
    
    fields["sestrati"] = c.Sestrati
    
    fields["dqdoti"] = c.Dqdoti
    
    return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Resume2) BamlTypeName() string {
    return "Resume2"
}

func (u Resume2) BamlEncodeName() *cffi.CFFITypeName {
    return &cffi.CFFITypeName{
        Namespace: cffi.CFFITypeNamespace_TYPES,
        Name:      "Resume2",
    }
}

type Resume3 struct {
    
Name string `json:"name"`
Email *string `json:"email"`
Experience []string `json:"experience"`
Skills []string `json:"skills"`
    
}

func (c *Resume3) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Resume3" {
		panic(fmt.Sprintf("expected Resume3, got %s", typeName.Name))
	}

   

	
	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
			switch key {
				
				case "name":
					c.Name = baml.Decode(valueHolder).Interface().(string)
				
				case "email":
					c.Email = baml.Decode(valueHolder).Interface().(*string)
				
				case "experience":
					c.Experience = baml.Decode(valueHolder).Interface().([]string)
				
				case "skills":
					c.Skills = baml.Decode(valueHolder).Interface().([]string)
				
		default:
			
			panic(fmt.Sprintf("unexpected field: %s in class Resume3", key))
			
		}
	}

}

func (c Resume3) Encode() (*cffi.CFFIValueHolder, error) {
    fields := map[string]any{}
    
    fields["name"] = c.Name
    
    fields["email"] = c.Email
    
    fields["experience"] = c.Experience
    
    fields["skills"] = c.Skills
    
    return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Resume3) BamlTypeName() string {
    return "Resume3"
}

func (u Resume3) BamlEncodeName() *cffi.CFFITypeName {
    return &cffi.CFFITypeName{
        Namespace: cffi.CFFITypeNamespace_TYPES,
        Name:      "Resume3",
    }
}

type Resume4 struct {
    
Testis *string `json:"testis"`
    
}

func (c *Resume4) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Resume4" {
		panic(fmt.Sprintf("expected Resume4, got %s", typeName.Name))
	}

   

	
	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
			switch key {
				
				case "testis":
					c.Testis = baml.Decode(valueHolder).Interface().(*string)
				
		default:
			
			panic(fmt.Sprintf("unexpected field: %s in class Resume4", key))
			
		}
	}

}

func (c Resume4) Encode() (*cffi.CFFIValueHolder, error) {
    fields := map[string]any{}
    
    fields["testis"] = c.Testis
    
    return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Resume4) BamlTypeName() string {
    return "Resume4"
}

func (u Resume4) BamlEncodeName() *cffi.CFFITypeName {
    return &cffi.CFFITypeName{
        Namespace: cffi.CFFITypeNamespace_TYPES,
        Name:      "Resume4",
    }
}

