// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
    "encoding/json"
    "fmt"

    baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
    "github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)


type ChichoTi string

const (
    
    ChichoTiLelqTi ChichoTi = "LelqTi"
    ChichoTiStrinkaTi ChichoTi = "StrinkaTi"
)

// Values returns all allowed values for the ChichoTi type.
func (ChichoTi) Values() []ChichoTi {
    return []ChichoTi{
        ChichoTiLelqTi,
        ChichoTiStrinkaTi,
    }
}

// IsValid checks whether the given ChichoTi value is valid.
func (e ChichoTi) IsValid() bool {
  
  for _, v := range e.Values() {
      if e == v {
          return true
      }
  }
  return false
  
}

// MarshalJSON customizes JSON marshaling for ChichoTi.
func (e ChichoTi) MarshalJSON() ([]byte, error) {
    if !e.IsValid() {
        return nil, fmt.Errorf("invalid ChichoTi: %q", e)
    }
    return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for ChichoTi.
func (e *ChichoTi) UnmarshalJSON(data []byte) error {
    var s string
    if err := json.Unmarshal(data, &s); err != nil {
        return err
    }
    *e = ChichoTi(s)
    if !e.IsValid() {
        return fmt.Errorf("invalid ChichoTi: %q", s)
    }
    return nil
}

func (e *ChichoTi) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
    name := holder.Name
    if name.Name != "ChichoTi" && name.Namespace != cffi.CFFITypeNamespace_TYPES {
        panic(fmt.Sprintf("expected types.ChichoTi, got %s.%s", string(name.Namespace.String()), string(name.Name)))
    }
    value := holder.Value
    *e = ChichoTi(value)
}

func (e ChichoTi) Encode() (*cffi.CFFIValueHolder, error) {
    return baml.EncodeEnum(e.BamlEncodeName, string(e), false)
}

func (e ChichoTi) BamlTypeName() string {
    return "ChichoTi"
}

func (u ChichoTi) BamlEncodeName() *cffi.CFFITypeName {
    return &cffi.CFFITypeName{
        Name:      "ChichoTi",
        Namespace: cffi.CFFITypeNamespace_TYPES,
    }
}

