//go:build integration

package testutil

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"text/template"

	"github.com/invakid404/baml-rest/internal/artifactprofile"
)

// De-BAML serving cutover S2 — the harness's half of the container-build
// provenance gate.
//
// This is the test that would have caught the regression outright. The S2
// artifact-ID provenance keys were added to cmd/build's renderer of
// cmd/build/Dockerfile.tmpl and not to THIS one, and Go's text/template renders a
// missing map key as the literal `<no value>` without erroring. Every integration
// image was therefore built with `ENV ARTIFACT_SOURCE_BUNDLE_DIGEST="<no value>"`,
// artifactattest correctly refused it, and all ~25 integration jobs failed at
// container setup — the only lane that builds an image, and the last one to run.
//
// It needs no Docker: rendering the template with this harness's own map is
// enough, and that is precisely the step that was wrong. `go test
// -tags=integration -run Provenance ./integration/testutil/` runs it in seconds.
//
// The sibling gate in cmd/build covers cmd/build's renderer and build.sh's
// rejection of an unrendered value.

var provenanceDigestRe = regexp.MustCompile(`ENV ARTIFACT_SOURCE_BUNDLE_DIGEST="([^"]*)"`)
var provenanceRevisionRe = regexp.MustCompile(`ENV ARTIFACT_SOURCE_REVISION="([^"]*)"`)

// syntheticBAMLSource materialises the smallest BAML source tree
// detectProtocGenGoVersion can read: one .pb.go carrying the generator comment it
// parses. It exists so the BAML-SOURCE template branch can be rendered here
// without a real BAML checkout — and so the shared constructor runs its REAL
// protoc detection rather than a stub, which keeps that branch's coverage honest.
func syntheticBAMLSource(t *testing.T, version string) string {
	t.Helper()
	root := t.TempDir()
	pbDir := filepath.Join(root, "engine", "language_client_go", "pkg", "cffi")
	if err := os.MkdirAll(pbDir, 0o755); err != nil {
		t.Fatalf("create synthetic BAML source: %v", err)
	}
	body := "// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\n//\tprotoc-gen-go " + version + "\n\npackage cffi\n"
	if err := os.WriteFile(filepath.Join(pbDir, "runtime.pb.go"), []byte(body), 0o644); err != nil {
		t.Fatalf("write synthetic .pb.go: %v", err)
	}
	// Fail loudly if the fixture ever stops satisfying the real detector, rather
	// than letting the BAML-source cases silently fall back to an empty version.
	got, err := detectProtocGenGoVersion(root)
	if err != nil {
		t.Fatalf("the synthetic BAML source no longer satisfies detectProtocGenGoVersion: %v", err)
	}
	if got != version {
		t.Fatalf("synthetic BAML source yields protoc version %q, want %q", got, version)
	}
	return root
}

// renderHarnessDockerfile renders the shared template through the harness's REAL
// template data.
//
// It builds that data with dockerfileTemplateDataFor — the SAME constructor
// createBAMLRestBuildContext uses — rather than assembling the struct itself.
// This gate exists because a template key nobody supplies renders as the literal
// `<no value>` and only fails inside a container build; a gate that maintained
// its own copy of the struct would be blind to exactly that, since a
// production-only field would be a field the copy never had. One constructor
// means one place to forget a field, and this notices.
func renderHarnessDockerfile(t *testing.T, opts SetupOptions) string {
	t.Helper()

	raw, err := getDockerfileTemplate()
	if err != nil {
		t.Fatalf("get Dockerfile template: %v", err)
	}
	tmpl, err := template.New("dockerfile").Parse(string(raw))
	if err != nil {
		t.Fatalf("parse Dockerfile template: %v", err)
	}

	data, err := dockerfileTemplateDataFor(opts)
	if err != nil {
		t.Fatalf("dockerfileTemplateDataFor: %v", err)
	}

	var out bytes.Buffer
	if err := tmpl.Execute(&out, data.toMap()); err != nil {
		t.Fatalf("execute Dockerfile template: %v", err)
	}
	return out.String()
}

// TestHarnessDockerfileSuppliesArtifactProvenance is the gate: the harness's own
// renderer must leave NO template key unrendered and must emit a real 16-hex
// bundle digest, for every option shape the matrix builds.
//
// Deleting either provenance field from dockerfileTemplateData.toMap — the exact
// omission that broke the matrix — fails this immediately.
func TestHarnessDockerfileSuppliesArtifactProvenance(t *testing.T) {
	const syntheticProtoc = "v1.36.12"
	bamlSrc := syntheticBAMLSource(t, syntheticProtoc)

	for _, tc := range []struct {
		name   string
		opts   SetupOptions
		protoc string
	}{
		{name: "default", opts: SetupOptions{BAMLVersion: "0.223.0", AdapterVersion: "v0.219.0"}},
		{name: "unary", opts: SetupOptions{BAMLVersion: "0.223.0", AdapterVersion: "v0.219.0", UnaryServer: true}},
		{name: "in-process", opts: SetupOptions{BAMLVersion: "0.223.0", AdapterVersion: "v0.219.0", InProcess: true}},
		// The BAML-SOURCE branches. They carry a bare `{{ .protocGenGoVersion }}`
		// the default branch never renders, so without these cases dropping that
		// key from toMap left this whole suite green while the source-build matrix
		// path would have emitted `<no value>`.
		{
			name:   "baml-source (cargo cffi stage)",
			opts:   SetupOptions{BAMLVersion: "0.223.0", AdapterVersion: "v0.219.0", BAMLSource: bamlSrc},
			protoc: syntheticProtoc,
		},
		{
			name: "baml-source (prebuilt cffi)",
			opts: SetupOptions{
				BAMLVersion: "0.223.0", AdapterVersion: "v0.219.0",
				BAMLSource: bamlSrc, PrebuiltCffiDir: "/synthetic/prebuilt",
			},
			protoc: syntheticProtoc,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			rendered := renderHarnessDockerfile(t, tc.opts)

			// No key anywhere may be unrendered, not just the provenance pair: a
			// future template key this harness forgets fails here rather than in a
			// container build at the end of the matrix.
			if strings.Contains(rendered, "<no value>") {
				for _, line := range strings.Split(rendered, "\n") {
					if strings.Contains(line, "<no value>") {
						t.Errorf("Dockerfile line renders a template key this harness did not supply: %s", line)
					}
				}
				t.FailNow()
			}

			m := provenanceDigestRe.FindStringSubmatch(rendered)
			if m == nil {
				t.Fatal("rendered Dockerfile has no ARTIFACT_SOURCE_BUNDLE_DIGEST ENV line")
			}
			if err := artifactprofile.ValidateArtifactID(m[1]); err != nil {
				t.Errorf("ENV ARTIFACT_SOURCE_BUNDLE_DIGEST=%q is not a valid artifact ID: %v; build.sh will refuse it and the image build will fail", m[1], err)
			}

			r := provenanceRevisionRe.FindStringSubmatch(rendered)
			if r == nil {
				t.Fatal("rendered Dockerfile has no ARTIFACT_SOURCE_REVISION ENV line")
			}
			// This harness builds from embedded sources and has no release
			// revision, so it declares the explicit sentinel — a DECLARED absence,
			// which artifactattest accepts, unlike a missing template key.
			if r[1] != artifactprofile.ProvenanceUnset {
				t.Errorf("ENV ARTIFACT_SOURCE_REVISION=%q, want the explicit %q sentinel", r[1], artifactprofile.ProvenanceUnset)
			}

			// Non-vacuity for the BAML-source cases: the cargo-cffi variant is the
			// one that actually interpolates the protoc version, so prove that
			// branch rendered rather than assuming the case selected it.
			if tc.opts.BAMLSource != "" && tc.opts.PrebuiltCffiDir == "" {
				if !strings.Contains(rendered, "protoc-gen-go@"+tc.protoc) {
					t.Errorf("the BAML-source branch did not render the protoc-gen-go interpolation; this case is not exercising it")
				}
			}
		})
	}
}

// TestHarnessBAMLSourceBranchNeedsProtocVersion is the mutation control for the
// branch the suite previously never rendered: dropping protocGenGoVersion from
// the harness's map must produce `<no value>` on the BAML-source branch, so the
// coverage the cases above add is real rather than incidental.
func TestHarnessBAMLSourceBranchNeedsProtocVersion(t *testing.T) {
	const syntheticProtoc = "v1.36.12"
	data, err := dockerfileTemplateDataFor(SetupOptions{
		BAMLVersion: "0.223.0", AdapterVersion: "v0.219.0",
		BAMLSource: syntheticBAMLSource(t, syntheticProtoc),
	})
	if err != nil {
		t.Fatalf("dockerfileTemplateDataFor: %v", err)
	}
	args := data.toMap()
	delete(args, "protocGenGoVersion")

	raw, err := getDockerfileTemplate()
	if err != nil {
		t.Fatalf("get Dockerfile template: %v", err)
	}
	tmpl, err := template.New("dockerfile").Parse(string(raw))
	if err != nil {
		t.Fatalf("parse Dockerfile template: %v", err)
	}
	var out bytes.Buffer
	if err := tmpl.Execute(&out, args); err != nil {
		t.Fatalf("execute Dockerfile template: %v", err)
	}
	if !strings.Contains(out.String(), "<no value>") {
		t.Fatal("dropping protocGenGoVersion on the BAML-source branch did not render \"<no value>\"; this gate's premise no longer holds")
	}
}

// TestHarnessBundleDigestDescribesTheShippedSources keeps the digest honest: it
// must be computed over the same embedded trees createBAMLRestBuildContext copies
// into the image, and it must be stable across renders.
func TestHarnessBundleDigestDescribesTheShippedSources(t *testing.T) {
	_, first, err := artifactProvenanceForImage()
	if err != nil {
		t.Fatalf("artifactProvenanceForImage: %v", err)
	}
	_, second, err := artifactProvenanceForImage()
	if err != nil {
		t.Fatalf("artifactProvenanceForImage: %v", err)
	}
	if first != second {
		t.Fatalf("the harness bundle digest is not deterministic: %q then %q", first, second)
	}
	if err := artifactprofile.ValidateArtifactID(first); err != nil {
		t.Fatalf("the harness bundle digest is not a valid artifact ID: %v", err)
	}
}
