// Package nativespinefixture is the M1 pure-Go native runtime fixture for the
// codegen spine (codegen-spine scope §4). It holds:
//
//   - generated_greeting.go — the carriers, neutral Executor interface, and
//     StreamingMethod/ParseMethod builder EMITTED by
//     adapters/common/codegen.EmitNativeStaticUnary from the neutral
//     projectdescriptor for the fixture's one admitted static-unary method. It is
//     committed as a golden and regenerated by
//     internal/nativespine.TestNativeSpineCodegenGolden. It imports only
//     bamlutils — no baml_client, no BAML runtime, no CFFI.
//   - runtime.go — the pure-Go NativeRuntime satisfying worker.Runtime.
//   - adapter.go — a pure-Go bamlutils.Adapter (no CFFI-bound generated adapter).
//
// The behavioral tests drive the existing worker.Runtime contract with fake
// executor + adapter (no socket, no pool, no parser-ownership collision), and an
// import-graph test asserts the package links no BAML/CFFI. Production
// rootruntime selection is unchanged; generated BAML stays the default.
package nativespinefixture
