// Code generated by adapters/common/codegen EmitNativeStaticUnary; DO NOT EDIT.

package nativespinefixture

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/invakid404/baml-rest/bamlutils"
	"github.com/invakid404/baml-rest/bamlutils/promptdescriptor"
)

// MethodName is the canonical BAML method this file serves.
const MethodName = "Greet"

// GreetInput is the typed input carrier (no CFFI codecs).
type GreetInput struct {
	Name   string `json:"name"`
	Formal bool   `json:"formal"`
}

// OutputGreeting is a generated output carrier.
type OutputGreeting struct {
	Text   string
	Formal bool
}

// MarshalJSON emits OutputGreeting with each field under its canonical BAML key.
func (v OutputGreeting) MarshalJSON() ([]byte, error) {
	return nativeSpineMarshalObject([]nativeSpineField{
		{"text", v.Text},
		{"formal", v.Formal},
	})
}

// UnmarshalJSON reads OutputGreeting from each field's canonical BAML key.
func (v *OutputGreeting) UnmarshalJSON(data []byte) error {
	return nativeSpineUnmarshalObject(data, map[string]any{
		"text":   &v.Text,
		"formal": &v.Formal,
	})
}

// ErrUnsupportedStreamMode is the stable decline returned when a mode other than
// unary final-call (StreamModeCall) is requested. M1 admits only unary call.
var ErrUnsupportedStreamMode = fmt.Errorf("nativespine: method %q supports only unary final-call (StreamModeCall)", MethodName)

// finalResult is a minimal bamlutils.StreamResult carrying one final value; the
// worker stream bridge marshals Final() into the output envelope.
type finalResult struct{ final any }

func (r finalResult) Kind() bamlutils.StreamResultKind { return bamlutils.StreamResultKindFinal }
func (r finalResult) Stream() any                      { return nil }
func (r finalResult) Final() any                       { return r.final }
func (r finalResult) Error() error                     { return nil }
func (r finalResult) Raw() string                      { return "" }
func (r finalResult) Reasoning() string                { return "" }
func (r finalResult) Reset() bool                      { return false }
func (r finalResult) Metadata() *bamlutils.Metadata    { return nil }
func (r finalResult) Release()                         {}

// errorResult is a minimal bamlutils.StreamResult carrying an executor error; the
// worker stream bridge classifies Error() into the error envelope.
type errorResult struct{ err error }

func (r errorResult) Kind() bamlutils.StreamResultKind { return bamlutils.StreamResultKindError }
func (r errorResult) Stream() any                      { return nil }
func (r errorResult) Final() any                       { return nil }
func (r errorResult) Error() error                     { return r.err }
func (r errorResult) Raw() string                      { return "" }
func (r errorResult) Reasoning() string                { return "" }
func (r errorResult) Reset() bool                      { return false }
func (r errorResult) Metadata() *bamlutils.Metadata    { return nil }
func (r errorResult) Release()                         {}

// BuildMethod returns the StreamingMethod and ParseMethod registrations for
// MethodName, driven by exec (a neutral bamlutils.NativeSpineUnaryExecutor). The
// StreamingMethod admits unary call mode only and declines every other mode with
// ErrUnsupportedStreamMode; neither closure makes a BAML request or parse call. The
// adapter (a bamlutils.Adapter embeds context.Context) is passed as the executor
// call context so a cancelled request is observed inside the executor. A succeeded
// result is delivered as one final frame; a pre-socket decline or a terminal
// failed-after-claim result as one error frame carrying its typed error — both flow
// through the existing worker stream bridge and envelope. The module never falls
// back: an outer composite executor (if any) intercepts a matched pre-socket decline
// BEFORE this closure sees it, so this module knows nothing about any oracle.
func BuildMethod(exec bamlutils.NativeSpineUnaryExecutor) (bamlutils.StreamingMethod, bamlutils.ParseMethod) {
	sm := bamlutils.StreamingMethod{
		MakeInput:        func() any { return new(GreetInput) },
		MakeOutput:       func() any { return new(OutputGreeting) },
		MakeStreamOutput: func() any { return new(OutputGreeting) },
		Impl: func(adapter bamlutils.Adapter, input any) (<-chan bamlutils.StreamResult, error) {
			if adapter.StreamMode() != bamlutils.StreamModeCall {
				return nil, fmt.Errorf("%w (got mode %d)", ErrUnsupportedStreamMode, adapter.StreamMode())
			}
			// Run the executor off the caller goroutine so a slow Call does not block
			// the stream bridge, and observe the adapter context (bamlutils.Adapter
			// embeds context.Context) so a cancelled request stops waiting to deliver.
			ch := make(chan bamlutils.StreamResult, 1)
			go func() {
				defer close(ch)
				var res bamlutils.StreamResult
				out := exec.Call(adapter, MethodName, input)
				if out.Disposition == bamlutils.NativeSpineSucceeded {
					res = finalResult{final: out.Final}
				} else {
					// A pre-socket decline (typed capability decline) or a terminal
					// failed-after-claim: both surface as one error frame. Never a resend.
					res = errorResult{err: out.Err}
				}
				select {
				case ch <- res:
				case <-adapter.Done():
				}
			}()
			return ch, nil
		},
	}
	pm := bamlutils.ParseMethod{
		MakeOutput: func() any { return new(OutputGreeting) },
		Impl: func(adapter bamlutils.Adapter, raw string) (any, error) {
			return exec.Parse(adapter, MethodName, raw)
		},
		StreamImpl: nil,
	}
	return sm, pm
}

// nativeSpineField is one output field: its exact BAML wire key and value.
type nativeSpineField struct {
	key string
	val any
}

// nativeSpineEncode marshals v with HTML escaping DISABLED, matching the serving
// serializer (worker serves final results via sonic.Marshal == sonic ConfigDefault,
// whose EscapeHTML is false). encoding/json's package default escapes '<', '>', '&'
// to </>/&, which would make a string field like "<x>" diverge from
// the bytes BAML actually serves. Go maps still emit in sorted-key order here
// (encoding/json sorts), which is the native lane's documented canonical order.
func nativeSpineEncode(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	// Encoder.Encode appends a trailing newline; the codec assembles the object
	// by hand, so strip it.
	out := buf.Bytes()
	if n := len(out); n > 0 && out[n-1] == '\n' {
		out = out[:n-1]
	}
	return out, nil
}

// nativeSpineMarshalObject renders fields as a JSON object in declaration order,
// writing each field under its exact wire key — including keys Go struct tags
// cannot express ("-", "", names with commas). Every key and value is encoded
// with nativeSpineEncode (HTML escaping off) so the bytes match the serving path.
func nativeSpineMarshalObject(fields []nativeSpineField) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteByte('{')
	for i, f := range fields {
		if i > 0 {
			buf.WriteByte(',')
		}
		k, err := nativeSpineEncode(f.key)
		if err != nil {
			return nil, err
		}
		buf.Write(k)
		buf.WriteByte(':')
		v, err := nativeSpineEncode(f.val)
		if err != nil {
			return nil, err
		}
		buf.Write(v)
	}
	buf.WriteByte('}')
	return buf.Bytes(), nil
}

// nativeSpineUnmarshalObject reads each destination pointer from its exact wire
// key. A missing key leaves the destination at its zero value.
func nativeSpineUnmarshalObject(data []byte, dst map[string]any) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for key, ptr := range dst {
		rm, ok := raw[key]
		if !ok {
			continue
		}
		if err := json.Unmarshal(rm, ptr); err != nil {
			return err
		}
	}
	return nil
}

// projectInput lowers the typed input carrier into the ordered projected
// argument vector (exact type assertions, direct fields, canonical BAML names as
// literals — no reflection, JSON round-trip, or map iteration).
func projectInput(input any) ([]promptdescriptor.ArgumentValue, error) {
	in, ok := input.(*GreetInput)
	if !ok {
		return nil, fmt.Errorf("nativespine: %s: input has Go type %T, want *GreetInput", MethodName, input)
	}
	_ = in
	values := make([]promptdescriptor.ArgumentValue, 0, 2)
	values = append(values, promptdescriptor.ArgumentValue{Name: "name", Value: promptdescriptor.StaticValue{Kind: promptdescriptor.StaticString, String: in.Name}})
	values = append(values, promptdescriptor.ArgumentValue{Name: "formal", Value: promptdescriptor.StaticValue{Kind: promptdescriptor.StaticBool, Bool: in.Formal}})
	return values, nil
}

// decodeFinal strictly decodes the native canonical JSON into the emitted output
// carrier via the proven bamlutils core (NO generated BAML, NO CFFI).
func decodeFinal(canonicalJSON []byte) (any, error) {
	return bamlutils.DecodeStaticFinal[OutputGreeting](canonicalJSON)
}

// Binding returns the neutral per-method registration the production runtime
// consumes: MethodName plus the reflection-free projector and strict decoder,
// both resolved here at registration time (non-nil).
func Binding() bamlutils.NativeSpineUnaryBinding {
	return bamlutils.NativeSpineUnaryBinding{
		Method:       MethodName,
		ProjectInput: projectInput,
		DecodeFinal:  decodeFinal,
	}
}
