// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/invakid404/baml-rest/internal/nativeprompt/testdata/staticserve_fixture/baml_client/types"
)

func StaticCompletion(ctx context.Context, topic string, opts ...CallOptionFunc) (string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "StaticCompletion", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		if result.Error != nil {
			return "", result.Error
		}

		casted := (result.Data).(string)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "StaticCompletion", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		for result := range channel {
			if result.Error != nil {
				return "", result.Error
			}

			if result.HasData {
				return result.Data.(string), nil
			}
		}

		return "", fmt.Errorf("No data returned from stream")
	}
}

func StaticCompletionOutputFormat(ctx context.Context, topic string, opts ...CallOptionFunc) (types.StaticAnswer, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "StaticCompletionOutputFormat", encoded, callOpts.onTick)
		if err != nil {
			return types.StaticAnswer{}, err
		}

		if result.Error != nil {
			return types.StaticAnswer{}, result.Error
		}

		casted := (result.Data).(types.StaticAnswer)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "StaticCompletionOutputFormat", encoded, callOpts.onTick)
		if err != nil {
			return types.StaticAnswer{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.StaticAnswer{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.StaticAnswer), nil
			}
		}

		return types.StaticAnswer{}, fmt.Errorf("No data returned from stream")
	}
}

func StaticOutputFormat(ctx context.Context, topic string, opts ...CallOptionFunc) (types.StaticAnswer, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "StaticOutputFormat", encoded, callOpts.onTick)
		if err != nil {
			return types.StaticAnswer{}, err
		}

		if result.Error != nil {
			return types.StaticAnswer{}, result.Error
		}

		casted := (result.Data).(types.StaticAnswer)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "StaticOutputFormat", encoded, callOpts.onTick)
		if err != nil {
			return types.StaticAnswer{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.StaticAnswer{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.StaticAnswer), nil
			}
		}

		return types.StaticAnswer{}, fmt.Errorf("No data returned from stream")
	}
}

func StaticPrimitiveArgs(ctx context.Context, text string, count int64, ratio float64, flag bool, opts ...CallOptionFunc) (string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "count": count, "ratio": ratio, "flag": flag},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "StaticPrimitiveArgs", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		if result.Error != nil {
			return "", result.Error
		}

		casted := (result.Data).(string)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "StaticPrimitiveArgs", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		for result := range channel {
			if result.Error != nil {
				return "", result.Error
			}

			if result.HasData {
				return result.Data.(string), nil
			}
		}

		return "", fmt.Errorf("No data returned from stream")
	}
}

func StaticRoleChat(ctx context.Context, topic string, count int64, opts ...CallOptionFunc) (string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic, "count": count},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "StaticRoleChat", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		if result.Error != nil {
			return "", result.Error
		}

		casted := (result.Data).(string)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "StaticRoleChat", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		for result := range channel {
			if result.Error != nil {
				return "", result.Error
			}

			if result.HasData {
				return result.Data.(string), nil
			}
		}

		return "", fmt.Errorf("No data returned from stream")
	}
}
