// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/invakid404/baml-rest/internal/nativeprompt/testdata/staticserve_fixture/baml_client/types"
)

type parse struct{}

var Parse = &parse{}

// / Parse version of StaticCompletion (Takes in string and returns string)
func (*parse) StaticCompletion(ctx context.Context, text string, opts ...CallOptionFunc) (string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs:	map[string]any{"text": text, "stream": false},
		Env:	getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticCompletion: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "StaticCompletion", encoded)
	if err != nil {
		return "", err
	}

	casted := (result).(string)

	return casted, nil
}

// / Parse version of StaticCompletionOutputFormat (Takes in string and returns types.StaticAnswer)
func (*parse) StaticCompletionOutputFormat(ctx context.Context, text string, opts ...CallOptionFunc) (types.StaticAnswer, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs:	map[string]any{"text": text, "stream": false},
		Env:	getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticCompletionOutputFormat: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "StaticCompletionOutputFormat", encoded)
	if err != nil {
		return types.StaticAnswer{}, err
	}

	casted := (result).(types.StaticAnswer)

	return casted, nil
}

// / Parse version of StaticOutputFormat (Takes in string and returns types.StaticAnswer)
func (*parse) StaticOutputFormat(ctx context.Context, text string, opts ...CallOptionFunc) (types.StaticAnswer, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs:	map[string]any{"text": text, "stream": false},
		Env:	getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticOutputFormat: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "StaticOutputFormat", encoded)
	if err != nil {
		return types.StaticAnswer{}, err
	}

	casted := (result).(types.StaticAnswer)

	return casted, nil
}

// / Parse version of StaticPrimitiveArgs (Takes in string and returns string)
func (*parse) StaticPrimitiveArgs(ctx context.Context, text string, opts ...CallOptionFunc) (string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs:	map[string]any{"text": text, "stream": false},
		Env:	getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticPrimitiveArgs: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "StaticPrimitiveArgs", encoded)
	if err != nil {
		return "", err
	}

	casted := (result).(string)

	return casted, nil
}

// / Parse version of StaticRoleChat (Takes in string and returns string)
func (*parse) StaticRoleChat(ctx context.Context, text string, opts ...CallOptionFunc) (string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs:	map[string]any{"text": text, "stream": false},
		Env:	getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRoleChat: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(ctx, "StaticRoleChat", encoded)
	if err != nil {
		return "", err
	}

	casted := (result).(string)

	return casted, nil
}
