// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type build_request struct{}

var Request = &build_request{}

// Build HTTP request for StaticCompletion (returns baml.HTTPRequest)
func (*build_request) StaticCompletion(ctx context.Context, topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs:	map[string]any{"topic": topic, "stream": false},
		Env:	getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticCompletion: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(ctx, "StaticCompletion", encoded)
}

// Build HTTP request for StaticCompletionOutputFormat (returns baml.HTTPRequest)
func (*build_request) StaticCompletionOutputFormat(ctx context.Context, topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs:	map[string]any{"topic": topic, "stream": false},
		Env:	getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticCompletionOutputFormat: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(ctx, "StaticCompletionOutputFormat", encoded)
}

// Build HTTP request for StaticOutputFormat (returns baml.HTTPRequest)
func (*build_request) StaticOutputFormat(ctx context.Context, topic string, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs:	map[string]any{"topic": topic, "stream": false},
		Env:	getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticOutputFormat: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(ctx, "StaticOutputFormat", encoded)
}

// Build HTTP request for StaticPrimitiveArgs (returns baml.HTTPRequest)
func (*build_request) StaticPrimitiveArgs(ctx context.Context, text string, count int64, ratio float64, flag bool, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs:	map[string]any{"text": text, "count": count, "ratio": ratio, "flag": flag, "stream": false},
		Env:	getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticPrimitiveArgs: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(ctx, "StaticPrimitiveArgs", encoded)
}

// Build HTTP request for StaticRoleChat (returns baml.HTTPRequest)
func (*build_request) StaticRoleChat(ctx context.Context, topic string, count int64, opts ...CallOptionFunc) (baml.HTTPRequest, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs:	map[string]any{"topic": topic, "count": count, "stream": false},
		Env:	getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: StaticRoleChat: %w", err)
		panic(wrapped_err)
	}

	return bamlRuntime.BuildRequest(ctx, "StaticRoleChat", encoded)
}
