// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/invakid404/baml-rest/internal/debaml/testdata/constraint_oracle/baml_client/types"
)

func Batch_boolfFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_boolf, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_boolfFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_boolf{}, err
		}

		if result.Error != nil {
			return types.Batch_boolf{}, result.Error
		}

		casted := (result.Data).(types.Batch_boolf)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_boolfFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_boolf{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_boolf{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_boolf), nil
			}
		}

		return types.Batch_boolf{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_booltFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_boolt, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_booltFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_boolt{}, err
		}

		if result.Error != nil {
			return types.Batch_boolt{}, result.Error
		}

		casted := (result.Data).(types.Batch_boolt)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_booltFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_boolt{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_boolt{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_boolt), nil
			}
		}

		return types.Batch_boolt{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_clsFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_cls, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_clsFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_cls{}, err
		}

		if result.Error != nil {
			return types.Batch_cls{}, result.Error
		}

		casted := (result.Data).(types.Batch_cls)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_clsFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_cls{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_cls{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_cls), nil
			}
		}

		return types.Batch_cls{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_constFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_const, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_constFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_const{}, err
		}

		if result.Error != nil {
			return types.Batch_const{}, result.Error
		}

		casted := (result.Data).(types.Batch_const)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_constFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_const{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_const{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_const), nil
			}
		}

		return types.Batch_const{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_enumFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_enum, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_enumFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_enum{}, err
		}

		if result.Error != nil {
			return types.Batch_enum{}, result.Error
		}

		casted := (result.Data).(types.Batch_enum)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_enumFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_enum{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_enum{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_enum), nil
			}
		}

		return types.Batch_enum{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_f20Fn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_f20, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_f20Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_f20{}, err
		}

		if result.Error != nil {
			return types.Batch_f20{}, result.Error
		}

		casted := (result.Data).(types.Batch_f20)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_f20Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_f20{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_f20{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_f20), nil
			}
		}

		return types.Batch_f20{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_f25Fn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_f25, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_f25Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_f25{}, err
		}

		if result.Error != nil {
			return types.Batch_f25{}, result.Error
		}

		casted := (result.Data).(types.Batch_f25)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_f25Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_f25{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_f25{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_f25), nil
			}
		}

		return types.Batch_f25{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_int0Fn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_int0, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_int0Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_int0{}, err
		}

		if result.Error != nil {
			return types.Batch_int0{}, result.Error
		}

		casted := (result.Data).(types.Batch_int0)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_int0Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_int0{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_int0{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_int0), nil
			}
		}

		return types.Batch_int0{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_int7Fn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_int7, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_int7Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_int7{}, err
		}

		if result.Error != nil {
			return types.Batch_int7{}, result.Error
		}

		casted := (result.Data).(types.Batch_int7)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_int7Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_int7{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_int7{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_int7), nil
			}
		}

		return types.Batch_int7{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_intnegFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_intneg, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_intnegFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_intneg{}, err
		}

		if result.Error != nil {
			return types.Batch_intneg{}, result.Error
		}

		casted := (result.Data).(types.Batch_intneg)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_intnegFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_intneg{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_intneg{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_intneg), nil
			}
		}

		return types.Batch_intneg{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_listFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_list, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_listFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_list{}, err
		}

		if result.Error != nil {
			return types.Batch_list{}, result.Error
		}

		casted := (result.Data).(types.Batch_list)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_listFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_list{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_list{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_list), nil
			}
		}

		return types.Batch_list{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_listbigFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_listbig, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_listbigFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_listbig{}, err
		}

		if result.Error != nil {
			return types.Batch_listbig{}, result.Error
		}

		casted := (result.Data).(types.Batch_listbig)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_listbigFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_listbig{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_listbig{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_listbig), nil
			}
		}

		return types.Batch_listbig{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_listeFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_liste, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_listeFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_liste{}, err
		}

		if result.Error != nil {
			return types.Batch_liste{}, result.Error
		}

		casted := (result.Data).(types.Batch_liste)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_listeFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_liste{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_liste{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_liste), nil
			}
		}

		return types.Batch_liste{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_listfFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_listf, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_listfFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_listf{}, err
		}

		if result.Error != nil {
			return types.Batch_listf{}, result.Error
		}

		casted := (result.Data).(types.Batch_listf)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_listfFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_listf{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_listf{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_listf), nil
			}
		}

		return types.Batch_listf{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_listsFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_lists, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_listsFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_lists{}, err
		}

		if result.Error != nil {
			return types.Batch_lists{}, result.Error
		}

		casted := (result.Data).(types.Batch_lists)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_listsFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_lists{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_lists{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_lists), nil
			}
		}

		return types.Batch_lists{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_liststr2Fn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_liststr2, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_liststr2Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_liststr2{}, err
		}

		if result.Error != nil {
			return types.Batch_liststr2{}, result.Error
		}

		casted := (result.Data).(types.Batch_liststr2)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_liststr2Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_liststr2{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_liststr2{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_liststr2), nil
			}
		}

		return types.Batch_liststr2{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_mapFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_map, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_mapFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_map{}, err
		}

		if result.Error != nil {
			return types.Batch_map{}, result.Error
		}

		casted := (result.Data).(types.Batch_map)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_mapFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_map{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_map{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_map), nil
			}
		}

		return types.Batch_map{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_nullFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_null, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_nullFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_null{}, err
		}

		if result.Error != nil {
			return types.Batch_null{}, result.Error
		}

		casted := (result.Data).(types.Batch_null)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_nullFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_null{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_null{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_null), nil
			}
		}

		return types.Batch_null{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_strFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_str, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_strFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_str{}, err
		}

		if result.Error != nil {
			return types.Batch_str{}, result.Error
		}

		casted := (result.Data).(types.Batch_str)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_strFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_str{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_str{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_str), nil
			}
		}

		return types.Batch_str{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_streFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_stre, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_streFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_stre{}, err
		}

		if result.Error != nil {
			return types.Batch_stre{}, result.Error
		}

		casted := (result.Data).(types.Batch_stre)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_streFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_stre{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_stre{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_stre), nil
			}
		}

		return types.Batch_stre{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_strexactFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_strexact, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_strexactFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_strexact{}, err
		}

		if result.Error != nil {
			return types.Batch_strexact{}, result.Error
		}

		casted := (result.Data).(types.Batch_strexact)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_strexactFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_strexact{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_strexact{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_strexact), nil
			}
		}

		return types.Batch_strexact{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_strnumFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_strnum, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_strnumFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_strnum{}, err
		}

		if result.Error != nil {
			return types.Batch_strnum{}, result.Error
		}

		casted := (result.Data).(types.Batch_strnum)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_strnumFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_strnum{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_strnum{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_strnum), nil
			}
		}

		return types.Batch_strnum{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_strnumsmFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_strnumsm, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_strnumsmFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_strnumsm{}, err
		}

		if result.Error != nil {
			return types.Batch_strnumsm{}, result.Error
		}

		casted := (result.Data).(types.Batch_strnumsm)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_strnumsmFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_strnumsm{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_strnumsm{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_strnumsm), nil
			}
		}

		return types.Batch_strnumsm{}, fmt.Errorf("No data returned from stream")
	}
}

func Batch_struFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Batch_stru, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Batch_struFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_stru{}, err
		}

		if result.Error != nil {
			return types.Batch_stru{}, result.Error
		}

		casted := (result.Data).(types.Batch_stru)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Batch_struFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Batch_stru{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Batch_stru{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Batch_stru), nil
			}
		}

		return types.Batch_stru{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_divzeroFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_divzero, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_divzeroFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_divzero{}, err
		}

		if result.Error != nil {
			return types.Iso_divzero{}, result.Error
		}

		casted := (result.Data).(types.Iso_divzero)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_divzeroFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_divzero{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_divzero{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_divzero), nil
			}
		}

		return types.Iso_divzero{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_f_length_intFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_f_length_int, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_f_length_intFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_length_int{}, err
		}

		if result.Error != nil {
			return types.Iso_f_length_int{}, result.Error
		}

		casted := (result.Data).(types.Iso_f_length_int)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_f_length_intFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_length_int{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_f_length_int{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_f_length_int), nil
			}
		}

		return types.Iso_f_length_int{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_f_length_noneFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_f_length_none, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_f_length_noneFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_length_none{}, err
		}

		if result.Error != nil {
			return types.Iso_f_length_none{}, result.Error
		}

		casted := (result.Data).(types.Iso_f_length_none)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_f_length_noneFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_length_none{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_f_length_none{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_f_length_none), nil
			}
		}

		return types.Iso_f_length_none{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_f_length_undefinedFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_f_length_undefined, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_f_length_undefinedFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_length_undefined{}, err
		}

		if result.Error != nil {
			return types.Iso_f_length_undefined{}, result.Error
		}

		casted := (result.Data).(types.Iso_f_length_undefined)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_f_length_undefinedFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_length_undefined{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_f_length_undefined{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_f_length_undefined), nil
			}
		}

		return types.Iso_f_length_undefined{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_f_regex_noargFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_f_regex_noarg, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_f_regex_noargFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_regex_noarg{}, err
		}

		if result.Error != nil {
			return types.Iso_f_regex_noarg{}, result.Error
		}

		casted := (result.Data).(types.Iso_f_regex_noarg)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_f_regex_noargFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_regex_noarg{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_f_regex_noarg{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_f_regex_noarg), nil
			}
		}

		return types.Iso_f_regex_noarg{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_f_splitFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_f_split, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_f_splitFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_split{}, err
		}

		if result.Error != nil {
			return types.Iso_f_split{}, result.Error
		}

		casted := (result.Data).(types.Iso_f_split)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_f_splitFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_split{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_f_split{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_f_split), nil
			}
		}

		return types.Iso_f_split{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_f_sum_attr_kwargFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_f_sum_attr_kwarg, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_f_sum_attr_kwargFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_sum_attr_kwarg{}, err
		}

		if result.Error != nil {
			return types.Iso_f_sum_attr_kwarg{}, result.Error
		}

		casted := (result.Data).(types.Iso_f_sum_attr_kwarg)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_f_sum_attr_kwargFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_sum_attr_kwarg{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_f_sum_attr_kwarg{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_f_sum_attr_kwarg), nil
			}
		}

		return types.Iso_f_sum_attr_kwarg{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_f_sum_mapFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_f_sum_map, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_f_sum_mapFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_sum_map{}, err
		}

		if result.Error != nil {
			return types.Iso_f_sum_map{}, result.Error
		}

		casted := (result.Data).(types.Iso_f_sum_map)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_f_sum_mapFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_sum_map{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_f_sum_map{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_f_sum_map), nil
			}
		}

		return types.Iso_f_sum_map{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_f_sum_str_argFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_f_sum_str_arg, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_f_sum_str_argFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_sum_str_arg{}, err
		}

		if result.Error != nil {
			return types.Iso_f_sum_str_arg{}, result.Error
		}

		casted := (result.Data).(types.Iso_f_sum_str_arg)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_f_sum_str_argFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_sum_str_arg{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_f_sum_str_arg{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_f_sum_str_arg), nil
			}
		}

		return types.Iso_f_sum_str_arg{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_f_unknownFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_f_unknown, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_f_unknownFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_unknown{}, err
		}

		if result.Error != nil {
			return types.Iso_f_unknown{}, result.Error
		}

		casted := (result.Data).(types.Iso_f_unknown)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_f_unknownFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_unknown{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_f_unknown{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_f_unknown), nil
			}
		}

		return types.Iso_f_unknown{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_f_urlencodeFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_f_urlencode, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_f_urlencodeFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_urlencode{}, err
		}

		if result.Error != nil {
			return types.Iso_f_urlencode{}, result.Error
		}

		casted := (result.Data).(types.Iso_f_urlencode)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_f_urlencodeFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_f_urlencode{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_f_urlencode{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_f_urlencode), nil
			}
		}

		return types.Iso_f_urlencode{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_fn_cyclerFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_fn_cycler, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_fn_cyclerFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_fn_cycler{}, err
		}

		if result.Error != nil {
			return types.Iso_fn_cycler{}, result.Error
		}

		casted := (result.Data).(types.Iso_fn_cycler)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_fn_cyclerFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_fn_cycler{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_fn_cycler{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_fn_cycler), nil
			}
		}

		return types.Iso_fn_cycler{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_fn_joinerFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_fn_joiner, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_fn_joinerFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_fn_joiner{}, err
		}

		if result.Error != nil {
			return types.Iso_fn_joiner{}, result.Error
		}

		casted := (result.Data).(types.Iso_fn_joiner)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_fn_joinerFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_fn_joiner{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_fn_joiner{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_fn_joiner), nil
			}
		}

		return types.Iso_fn_joiner{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_fn_lipsumFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_fn_lipsum, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_fn_lipsumFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_fn_lipsum{}, err
		}

		if result.Error != nil {
			return types.Iso_fn_lipsum{}, result.Error
		}

		casted := (result.Data).(types.Iso_fn_lipsum)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_fn_lipsumFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_fn_lipsum{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_fn_lipsum{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_fn_lipsum), nil
			}
		}

		return types.Iso_fn_lipsum{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_fn_unknownFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_fn_unknown, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_fn_unknownFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_fn_unknown{}, err
		}

		if result.Error != nil {
			return types.Iso_fn_unknown{}, result.Error
		}

		casted := (result.Data).(types.Iso_fn_unknown)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_fn_unknownFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_fn_unknown{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_fn_unknown{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_fn_unknown), nil
			}
		}

		return types.Iso_fn_unknown{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_num_pow_oversizedFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_num_pow_oversized, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_num_pow_oversizedFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_num_pow_oversized{}, err
		}

		if result.Error != nil {
			return types.Iso_num_pow_oversized{}, result.Error
		}

		casted := (result.Data).(types.Iso_num_pow_oversized)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_num_pow_oversizedFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_num_pow_oversized{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_num_pow_oversized{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_num_pow_oversized), nil
			}
		}

		return types.Iso_num_pow_oversized{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_op_floordiv_zeroFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_op_floordiv_zero, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_op_floordiv_zeroFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_op_floordiv_zero{}, err
		}

		if result.Error != nil {
			return types.Iso_op_floordiv_zero{}, result.Error
		}

		casted := (result.Data).(types.Iso_op_floordiv_zero)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_op_floordiv_zeroFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_op_floordiv_zero{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_op_floordiv_zero{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_op_floordiv_zero), nil
			}
		}

		return types.Iso_op_floordiv_zero{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_op_rem_zeroFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_op_rem_zero, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_op_rem_zeroFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_op_rem_zero{}, err
		}

		if result.Error != nil {
			return types.Iso_op_rem_zero{}, result.Error
		}

		casted := (result.Data).(types.Iso_op_rem_zero)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_op_rem_zeroFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_op_rem_zero{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_op_rem_zero{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_op_rem_zero), nil
			}
		}

		return types.Iso_op_rem_zero{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_op_str_add_numFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_op_str_add_num, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_op_str_add_numFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_op_str_add_num{}, err
		}

		if result.Error != nil {
			return types.Iso_op_str_add_num{}, result.Error
		}

		casted := (result.Data).(types.Iso_op_str_add_num)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_op_str_add_numFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_op_str_add_num{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_op_str_add_num{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_op_str_add_num), nil
			}
		}

		return types.Iso_op_str_add_num{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_pow_computed_neg_exp2Fn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_pow_computed_neg_exp2, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_pow_computed_neg_exp2Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_pow_computed_neg_exp2{}, err
		}

		if result.Error != nil {
			return types.Iso_pow_computed_neg_exp2{}, result.Error
		}

		casted := (result.Data).(types.Iso_pow_computed_neg_exp2)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_pow_computed_neg_exp2Fn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_pow_computed_neg_exp2{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_pow_computed_neg_exp2{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_pow_computed_neg_exp2), nil
			}
		}

		return types.Iso_pow_computed_neg_exp2{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_pow_computed_neg_expFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_pow_computed_neg_exp, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_pow_computed_neg_expFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_pow_computed_neg_exp{}, err
		}

		if result.Error != nil {
			return types.Iso_pow_computed_neg_exp{}, result.Error
		}

		casted := (result.Data).(types.Iso_pow_computed_neg_exp)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_pow_computed_neg_expFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_pow_computed_neg_exp{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_pow_computed_neg_exp{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_pow_computed_neg_exp), nil
			}
		}

		return types.Iso_pow_computed_neg_exp{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_pow_negative_expFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_pow_negative_exp, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_pow_negative_expFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_pow_negative_exp{}, err
		}

		if result.Error != nil {
			return types.Iso_pow_negative_exp{}, result.Error
		}

		casted := (result.Data).(types.Iso_pow_negative_exp)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_pow_negative_expFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_pow_negative_exp{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_pow_negative_exp{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_pow_negative_exp), nil
			}
		}

		return types.Iso_pow_negative_exp{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_pow_paren_neg_expFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_pow_paren_neg_exp, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_pow_paren_neg_expFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_pow_paren_neg_exp{}, err
		}

		if result.Error != nil {
			return types.Iso_pow_paren_neg_exp{}, result.Error
		}

		casted := (result.Data).(types.Iso_pow_paren_neg_exp)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_pow_paren_neg_expFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_pow_paren_neg_exp{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_pow_paren_neg_exp{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_pow_paren_neg_exp), nil
			}
		}

		return types.Iso_pow_paren_neg_exp{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_py_num_methodFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_py_num_method, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_py_num_methodFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_py_num_method{}, err
		}

		if result.Error != nil {
			return types.Iso_py_num_method{}, result.Error
		}

		casted := (result.Data).(types.Iso_py_num_method)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_py_num_methodFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_py_num_method{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_py_num_method{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_py_num_method), nil
			}
		}

		return types.Iso_py_num_method{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_t_containingFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_t_containing, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_t_containingFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_t_containing{}, err
		}

		if result.Error != nil {
			return types.Iso_t_containing{}, result.Error
		}

		casted := (result.Data).(types.Iso_t_containing)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_t_containingFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_t_containing{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_t_containing{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_t_containing), nil
			}
		}

		return types.Iso_t_containing{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_t_unknownFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_t_unknown, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_t_unknownFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_t_unknown{}, err
		}

		if result.Error != nil {
			return types.Iso_t_unknown{}, result.Error
		}

		casted := (result.Data).(types.Iso_t_unknown)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_t_unknownFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_t_unknown{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_t_unknown{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_t_unknown), nil
			}
		}

		return types.Iso_t_unknown{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_this_int0_bareFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_this_int0_bare, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_this_int0_bareFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_int0_bare{}, err
		}

		if result.Error != nil {
			return types.Iso_this_int0_bare{}, result.Error
		}

		casted := (result.Data).(types.Iso_this_int0_bare)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_this_int0_bareFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_int0_bare{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_this_int0_bare{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_this_int0_bare), nil
			}
		}

		return types.Iso_this_int0_bare{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_this_int_bareFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_this_int_bare, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_this_int_bareFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_int_bare{}, err
		}

		if result.Error != nil {
			return types.Iso_this_int_bare{}, result.Error
		}

		casted := (result.Data).(types.Iso_this_int_bare)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_this_int_bareFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_int_bare{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_this_int_bare{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_this_int_bare), nil
			}
		}

		return types.Iso_this_int_bare{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_this_map_lastFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_this_map_last, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_this_map_lastFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_map_last{}, err
		}

		if result.Error != nil {
			return types.Iso_this_map_last{}, result.Error
		}

		casted := (result.Data).(types.Iso_this_map_last)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_this_map_lastFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_map_last{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_this_map_last{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_this_map_last), nil
			}
		}

		return types.Iso_this_map_last{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_this_map_sumFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_this_map_sum, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_this_map_sumFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_map_sum{}, err
		}

		if result.Error != nil {
			return types.Iso_this_map_sum{}, result.Error
		}

		casted := (result.Data).(types.Iso_this_map_sum)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_this_map_sumFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_map_sum{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_this_map_sum{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_this_map_sum), nil
			}
		}

		return types.Iso_this_map_sum{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_this_null_bareFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_this_null_bare, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_this_null_bareFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_null_bare{}, err
		}

		if result.Error != nil {
			return types.Iso_this_null_bare{}, result.Error
		}

		casted := (result.Data).(types.Iso_this_null_bare)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_this_null_bareFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_null_bare{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_this_null_bare{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_this_null_bare), nil
			}
		}

		return types.Iso_this_null_bare{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_this_str_splitFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_this_str_split, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_this_str_splitFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_str_split{}, err
		}

		if result.Error != nil {
			return types.Iso_this_str_split{}, result.Error
		}

		casted := (result.Data).(types.Iso_this_str_split)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_this_str_splitFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_str_split{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_this_str_split{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_this_str_split), nil
			}
		}

		return types.Iso_this_str_split{}, fmt.Errorf("No data returned from stream")
	}
}

func Iso_this_stre_bareFn(ctx context.Context, topic string, opts ...CallOptionFunc) (types.Iso_this_stre_bare, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"topic": topic},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "Iso_this_stre_bareFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_stre_bare{}, err
		}

		if result.Error != nil {
			return types.Iso_this_stre_bare{}, result.Error
		}

		casted := (result.Data).(types.Iso_this_stre_bare)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "Iso_this_stre_bareFn", encoded, callOpts.onTick)
		if err != nil {
			return types.Iso_this_stre_bare{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Iso_this_stre_bare{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Iso_this_stre_bare), nil
			}
		}

		return types.Iso_this_stre_bare{}, fmt.Errorf("No data returned from stream")
	}
}
