// Code generated by internal/debaml/bamlunicode/cmd/gen; DO NOT EDIT.
//
// BAML compatibility profile 0.223.0
//   case + properties : Rust std Unicode 17.0.0 (rustc 1.93.0)
//   normalization     : unicode-normalization 0.1.24 -> Unicode 16.0.0
// generator-revision  : 2
// source              : cmd/gen (compatibility profile + UCD input/output digests)

package bamlunicode

// Manifest is the machine-readable provenance record for the generated
// tables; the mirrored testdata/manifest.json carries the same data. The CI
// drift guard re-derives the discovered fields from BAML source and re-hashes
// the inputs/outputs, failing on any mismatch.
var Manifest = ProfileManifest{
	BAMLVersion:                 "0.223.0",
	BAMLSourceCommit:            "85247f452fe202300ec38d41fdc4035ea3020983",
	RustcVersion:                "1.93.0",
	RustcCommit:                 "254b59607d4417e9dffbc307138ae5c86280fe4c",
	RustStdUnicodeVersion:       "17.0.0",
	NormalizationCrate:          "unicode-normalization",
	NormalizationCrateVersion:   "0.1.24",
	NormalizationCrateChecksum:  "5033c97c4262335cded6d6fc3e5c18ab755e1a3dc96376350f3d8e9f009ad956",
	NormalizationUnicodeVersion: "16.0.0",
	MatchStringPath:             "engine/baml-lib/jsonish/src/deserializer/coercer/match_string.rs",
	MatchStringFingerprint:      "6ced35949641470658930d60787d128f9ccf5bb9b058a2606b64c81f54d1d228",
	ReleaseWorkflowPath:         ".github/workflows/build-cli-release.reusable.yaml",
	ReleaseWorkflowFingerprint:  "1aa156be43a455693245aad57be996673f03384f8045589550837ab6ef6c1ad2",
	SetupRustActionPath:         ".github/actions/setup-rust/action.yml",
	SetupRustActionFingerprint:  "31bdf1bf41065f8b1e429ffeef768b97d63ae7f5196be094c498057cadfcdfa3",
	GeneratorRevision:           "2",
	Inputs: []ManifestFile{
		{UnicodeVersion: "17.0.0", Name: "UnicodeData.txt", URL: "https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt", SHA256: "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c"},
		{UnicodeVersion: "17.0.0", Name: "SpecialCasing.txt", URL: "https://www.unicode.org/Public/17.0.0/ucd/SpecialCasing.txt", SHA256: "efc25faf19de21b92c1194c111c932e03d2a5eaf18194e33f1156e96de4c9588"},
		{UnicodeVersion: "17.0.0", Name: "DerivedCoreProperties.txt", URL: "https://www.unicode.org/Public/17.0.0/ucd/DerivedCoreProperties.txt", SHA256: "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08"},
		{UnicodeVersion: "17.0.0", Name: "PropList.txt", URL: "https://www.unicode.org/Public/17.0.0/ucd/PropList.txt", SHA256: "130dcddcaadaf071008bdfce1e7743e04fdfbc910886f017d9f9ac931d8c64dd"},
		{UnicodeVersion: "16.0.0", Name: "UnicodeData.txt", URL: "https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt", SHA256: "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f"},
		{UnicodeVersion: "16.0.0", Name: "NormalizationTest.txt", URL: "https://www.unicode.org/Public/16.0.0/ucd/NormalizationTest.txt", SHA256: "d811971453e7075e1ad56fb1b301eece5aa80757b81f6156e74a1bfb3ae5ceb1"},
		{UnicodeVersion: "16.0.0", Name: "DerivedNormalizationProps.txt", URL: "https://www.unicode.org/Public/16.0.0/ucd/DerivedNormalizationProps.txt", SHA256: "4d4c03892dea9146d674b686e495df2d55a28d071ac474041d73518f887abddc"},
	},
	Archives: []ManifestArchive{
		{UnicodeVersion: "17.0.0", URL: "https://www.unicode.org/Public/17.0.0/ucd/UCD.zip", SHA256: "2066d1909b2ea93916ce092da1c0ee4808ea3ef8407c94b4f14f5b7eb263d28e"},
		{UnicodeVersion: "16.0.0", URL: "https://www.unicode.org/Public/zipped/16.0.0/UCD.zip", SHA256: "c86dd81f2b14a43b0cc064aa5f89aa7241386801e35c59c7984e579832634eb2"},
	},
	Outputs: []ManifestFile{
		{Name: "lower_17_0_0_gen.go", SHA256: "d66460d6e816058a962e25b2a2ab3289619a304b957fc9b0a36f67ca6b67fb8b"},
		{Name: "marks_16_0_0_gen.go", SHA256: "8fd1ade1ec65b8b68f885a1bd3d1515dbcc1539d438a5186dbd6abe5b93ca736"},
		{Name: "nfkd_16_0_0_gen.go", SHA256: "1b625eea6915eebb12ec169024faf08cd586e4dbf5106a7e2b20cd74f85fc6de"},
		{Name: "props_17_0_0_gen.go", SHA256: "db8d245b05171613403fbdc12a456367eb179f7e73d07e100caabdbe7502de2c"},
	},
}
