// Package nativespinejsonfixture is the ExecBridge-U1 real-population carrier
// fixture: the emitted hermetic native package for the single admitted static-unary
// method whose return is the EXACT proven direct five-arm `JSON` recursive alias
// (StaticRecursiveAliasJSON(topic) -> JSON). It holds:
//
//   - generated_json_alias.go — the carriers (OutputJson / OutputUnion1), the
//     reflection-free scalar input projector, the strict DecodeStaticAliasFinal
//     decoder, the neutral-executor-driven StreamingMethod/ParseMethod builder, and
//     the Binding() the production runtime consumes. EMITTED by
//     adapters/common/codegen.EmitNativeStaticUnary and regenerated by
//     internal/nativespine.TestJSONAliasCodegenGolden. It imports only
//     context/bamlutils/bamlutils/promptdescriptor/stdlib — no baml_client, no BAML
//     runtime, no CFFI.
//   - runtime.go — the pure-Go NativeRuntime satisfying worker.Runtime.
//   - adapter.go — a pure-Go bamlutils.Adapter (no CFFI-bound generated adapter).
//
// It is the emitted half of the ExecBridge-U1 real-population proof: the production
// spine executor (nativeserve/spine) drives it against a real loopback OpenAI-
// compatible provider through worker.Handler, with no generated BAML or CFFI on the
// emitted/runtime path. Production rootruntime selection is unchanged (default-deny).
package nativespinejsonfixture
