// Code generated by adapters/common/codegen EmitNativeStaticStream; DO NOT EDIT.

package nativespinejsonfixture

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/invakid404/baml-rest/bamlutils"
	"github.com/invakid404/baml-rest/bamlutils/promptdescriptor"
)

// MethodName is the canonical BAML method this file serves.
const MethodName = "StaticRecursiveAliasJSON"

// StaticRecursiveAliasJsonInput is the typed input carrier (no CFFI codecs).
type StaticRecursiveAliasJsonInput struct {
	Topic string `json:"topic"`
}

// OutputJson is a generated structural recursive alias carrier.
type OutputJson = OutputUnion1

// OutputJsonStream is the generated STREAM carrier for the method's return: the
// POINTER/partial twin of the final value alias above (BAML v0.223's
// stream_types.<T> vs types.<T>). It shares the ONE union implementation —
// only the pointer level differs — and is never an `any` fallback.
type OutputJsonStream = *OutputUnion1

// OutputUnion1 is a generated output union carrier: a discriminated value
// holding exactly one arm, reproducing BAML v0.223 generated-carrier JSON behavior.
type OutputUnion1 struct {
	variant  string
	variant0 *int64
	variant1 *string
	variant2 *bool
	variant3 *[]OutputJson
	variant4 *map[string]OutputJson
}

// MarshalJSON emits the selected arm; an unset/unknown discriminator errors.
func (u OutputUnion1) MarshalJSON() ([]byte, error) {
	if err := nativeSpineCheckAcyclic(u); err != nil {
		return nil, err
	}
	switch u.variant {
	case "v0":
		return json.Marshal(u.variant0)
	case "v1":
		return json.Marshal(u.variant1)
	case "v2":
		return json.Marshal(u.variant2)
	case "v3":
		return json.Marshal(u.variant3)
	case "v4":
		return json.Marshal(u.variant4)
	}
	return nil, fmt.Errorf("nativespine: OutputUnion1: invalid union variant %q", u.variant)
}

// UnmarshalJSON tries arms sequentially in descriptor order, first-success
// (BAML v0.223 generated-carrier parity: no value checks; same-base arms are ambiguous).
func (u *OutputUnion1) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &u.variant0); err == nil {
		u.variant = "v0"
		return nil
	}
	u.variant0 = nil
	if err := json.Unmarshal(data, &u.variant1); err == nil {
		u.variant = "v1"
		return nil
	}
	u.variant1 = nil
	if err := json.Unmarshal(data, &u.variant2); err == nil {
		u.variant = "v2"
		return nil
	}
	u.variant2 = nil
	if err := json.Unmarshal(data, &u.variant3); err == nil {
		u.variant = "v3"
		return nil
	}
	u.variant3 = nil
	if err := json.Unmarshal(data, &u.variant4); err == nil {
		u.variant = "v4"
		return nil
	}
	u.variant4 = nil
	return fmt.Errorf("nativespine: OutputUnion1: no union variant matched: %s", string(data))
}

// OutputUnion1NewVariant0 constructs OutputUnion1 holding arm 0.
func OutputUnion1NewVariant0(v int64) OutputUnion1 {
	return OutputUnion1{variant: "v0", variant0: &v}
}

// SetVariant0 selects arm 0, clearing the others.
func (u *OutputUnion1) SetVariant0(v int64) {
	u.variant = "v0"
	u.variant0 = &v
	u.variant1 = nil
	u.variant2 = nil
	u.variant3 = nil
	u.variant4 = nil
}

// IsVariant0 reports whether arm 0 is selected.
func (u *OutputUnion1) IsVariant0() bool { return u.variant == "v0" }

// AsVariant0 returns the arm-0 pointer, or nil when another arm is selected.
func (u *OutputUnion1) AsVariant0() *int64 {
	if u.variant != "v0" {
		return nil
	}
	return u.variant0
}

// OutputUnion1NewVariant1 constructs OutputUnion1 holding arm 1.
func OutputUnion1NewVariant1(v string) OutputUnion1 {
	return OutputUnion1{variant: "v1", variant1: &v}
}

// SetVariant1 selects arm 1, clearing the others.
func (u *OutputUnion1) SetVariant1(v string) {
	u.variant = "v1"
	u.variant1 = &v
	u.variant0 = nil
	u.variant2 = nil
	u.variant3 = nil
	u.variant4 = nil
}

// IsVariant1 reports whether arm 1 is selected.
func (u *OutputUnion1) IsVariant1() bool { return u.variant == "v1" }

// AsVariant1 returns the arm-1 pointer, or nil when another arm is selected.
func (u *OutputUnion1) AsVariant1() *string {
	if u.variant != "v1" {
		return nil
	}
	return u.variant1
}

// OutputUnion1NewVariant2 constructs OutputUnion1 holding arm 2.
func OutputUnion1NewVariant2(v bool) OutputUnion1 {
	return OutputUnion1{variant: "v2", variant2: &v}
}

// SetVariant2 selects arm 2, clearing the others.
func (u *OutputUnion1) SetVariant2(v bool) {
	u.variant = "v2"
	u.variant2 = &v
	u.variant0 = nil
	u.variant1 = nil
	u.variant3 = nil
	u.variant4 = nil
}

// IsVariant2 reports whether arm 2 is selected.
func (u *OutputUnion1) IsVariant2() bool { return u.variant == "v2" }

// AsVariant2 returns the arm-2 pointer, or nil when another arm is selected.
func (u *OutputUnion1) AsVariant2() *bool {
	if u.variant != "v2" {
		return nil
	}
	return u.variant2
}

// OutputUnion1NewVariant3 constructs OutputUnion1 holding arm 3.
func OutputUnion1NewVariant3(v []OutputJson) OutputUnion1 {
	return OutputUnion1{variant: "v3", variant3: &v}
}

// SetVariant3 selects arm 3, clearing the others.
func (u *OutputUnion1) SetVariant3(v []OutputJson) {
	u.variant = "v3"
	u.variant3 = &v
	u.variant0 = nil
	u.variant1 = nil
	u.variant2 = nil
	u.variant4 = nil
}

// IsVariant3 reports whether arm 3 is selected.
func (u *OutputUnion1) IsVariant3() bool { return u.variant == "v3" }

// AsVariant3 returns the arm-3 pointer, or nil when another arm is selected.
func (u *OutputUnion1) AsVariant3() *[]OutputJson {
	if u.variant != "v3" {
		return nil
	}
	return u.variant3
}

// OutputUnion1NewVariant4 constructs OutputUnion1 holding arm 4.
func OutputUnion1NewVariant4(v map[string]OutputJson) OutputUnion1 {
	return OutputUnion1{variant: "v4", variant4: &v}
}

// SetVariant4 selects arm 4, clearing the others.
func (u *OutputUnion1) SetVariant4(v map[string]OutputJson) {
	u.variant = "v4"
	u.variant4 = &v
	u.variant0 = nil
	u.variant1 = nil
	u.variant2 = nil
	u.variant3 = nil
}

// IsVariant4 reports whether arm 4 is selected.
func (u *OutputUnion1) IsVariant4() bool { return u.variant == "v4" }

// AsVariant4 returns the arm-4 pointer, or nil when another arm is selected.
func (u *OutputUnion1) AsVariant4() *map[string]OutputJson {
	if u.variant != "v4" {
		return nil
	}
	return u.variant4
}

// ErrUnsupportedStreamMode is the stable decline returned for a public mode outside
// the ClassStaticStream set. The admitted set is CLOSED: unary final-call
// (StreamModeCall), /stream (StreamModeStream), and /stream-with-raw
// (StreamModeStreamWithRaw). /call-with-raw and every unknown mode decline BEFORE any
// stream execution — the native static call-with-raw envelope is not proven.
var ErrUnsupportedStreamMode = fmt.Errorf("nativespine: method %q supports only unary final-call (StreamModeCall), stream (StreamModeStream), and stream-with-raw (StreamModeStreamWithRaw)", MethodName)

// errNoStreamExecutor is the typed LOCAL CONFIGURATION error returned when a
// stream-capable method is driven by a unary-only executor. The native-only runtime
// always supplies a bamlutils.NativeSpineStreamExecutor, so this is a wiring bug — it
// is raised before any stream execution and is never a transport outcome.
var errNoStreamExecutor = fmt.Errorf("nativespine: method %q requires a bamlutils.NativeSpineStreamExecutor; the injected executor is unary-only", MethodName)

// streamResultBuffer bounds the per-request result channel. Partials are delivered
// NON-BLOCKING (a full buffer drops the partial, exactly as the shared orchestrator
// cadence does) so a slow consumer can never stall the upstream provider read.
const streamResultBuffer = 16

// streamResult is a minimal bamlutils.StreamResult carrying one cadence-decided public
// event: a structured partial (Stream()), the per-delta raw/reasoning channels, or
// both. A raw-only event carries a nil partial, which the worker stream bridge
// marshals exactly as the BAML lane's raw-only partial does.
type streamResult struct {
	partial   any
	raw       string
	reasoning string
}

func (r streamResult) Kind() bamlutils.StreamResultKind { return bamlutils.StreamResultKindStream }
func (r streamResult) Stream() any                      { return r.partial }
func (r streamResult) Final() any                       { return nil }
func (r streamResult) Error() error                     { return nil }
func (r streamResult) Raw() string                      { return r.raw }
func (r streamResult) Reasoning() string                { return r.reasoning }
func (r streamResult) Reset() bool                      { return false }
func (r streamResult) Metadata() *bamlutils.Metadata    { return nil }
func (r streamResult) Release()                         {}

// finalResult is a minimal bamlutils.StreamResult carrying one final value plus the
// accumulated raw/reasoning channels; the worker stream bridge marshals Final() into
// the output envelope. Raw/reasoning are populated only for a raw-wanted mode, matching
// the shared orchestrator's emitFinal.
type finalResult struct {
	final     any
	raw       string
	reasoning string
}

func (r finalResult) Kind() bamlutils.StreamResultKind { return bamlutils.StreamResultKindFinal }
func (r finalResult) Stream() any                      { return nil }
func (r finalResult) Final() any                       { return r.final }
func (r finalResult) Error() error                     { return nil }
func (r finalResult) Raw() string                      { return r.raw }
func (r finalResult) Reasoning() string                { return r.reasoning }
func (r finalResult) Reset() bool                      { return false }
func (r finalResult) Metadata() *bamlutils.Metadata    { return nil }
func (r finalResult) Release()                         {}

// errorResult is a minimal bamlutils.StreamResult carrying an executor error plus any
// raw the claimed lane had accumulated before the fault (the worker bridge attaches it
// as details.raw). The worker stream bridge classifies Error() into the error envelope.
type errorResult struct {
	err error
	raw string
}

func (r errorResult) Kind() bamlutils.StreamResultKind { return bamlutils.StreamResultKindError }
func (r errorResult) Stream() any                      { return nil }
func (r errorResult) Final() any                       { return nil }
func (r errorResult) Error() error                     { return r.err }
func (r errorResult) Raw() string                      { return r.raw }
func (r errorResult) Reasoning() string                { return "" }
func (r errorResult) Reset() bool                      { return false }
func (r errorResult) Metadata() *bamlutils.Metadata    { return nil }
func (r errorResult) Release()                         {}

// makeStreamOutput allocates the STREAM carrier: a value of type OutputJsonStream
// — the POINTER union — never a pointer TO the stream alias (which would be a double
// pointer and would decode/marshal wrongly). The explicit typed local is the
// compile-time statement of that pointer level.
func makeStreamOutput() any {
	var v OutputJsonStream = new(OutputJson)
	return v
}

// runUnaryCall drives the FROZEN unary executor Call off the caller goroutine and
// delivers exactly one frame: the final on success, or the typed error of a pre-socket
// decline / terminal failed-after-claim. Byte-for-byte the ClassStaticUnary behavior.
func runUnaryCall(exec bamlutils.NativeSpineUnaryExecutor, adapter bamlutils.Adapter, input any) (<-chan bamlutils.StreamResult, error) {
	ch := make(chan bamlutils.StreamResult, 1)
	go func() {
		defer close(ch)
		var res bamlutils.StreamResult
		out := exec.Call(adapter, MethodName, input)
		if out.Disposition == bamlutils.NativeSpineSucceeded {
			res = finalResult{final: out.Final}
		} else {
			// A pre-socket decline (typed capability decline) or a terminal
			// failed-after-claim: both surface as one error frame. Never a resend.
			res = errorResult{err: out.Err}
		}
		select {
		case ch <- res:
		case <-adapter.Done():
		}
	}()
	return ch, nil
}

// runStream drives ONE claimed native stream off the caller goroutine. The executor
// owns the claim and the cadence: this closure only shapes each event into a
// bamlutils.StreamResult and delivers it.
//
// Delivery semantics mirror the shared orchestrator cadence exactly: a partial is
// NON-BLOCKING (dropped when the buffer is full, so the provider read never stalls) and
// returns an error ONLY on cancellation; the single terminal frame is
// blocking-or-cancel. needsRaw gates the raw/reasoning channels, so a plain /stream
// carries none — the same rule emitFinal applies on the BAML lane.
func runStream(exec bamlutils.NativeSpineStreamExecutor, adapter bamlutils.Adapter, input any, needsRaw bool) (<-chan bamlutils.StreamResult, error) {
	ch := make(chan bamlutils.StreamResult, streamResultBuffer)
	go func() {
		defer close(ch)
		emit := func(ev bamlutils.NativeSpineStreamEvent) error {
			if !ev.HasPartial && !needsRaw {
				// A raw-only event on a plain /stream carries NO public content: no
				// structured partial, and the raw/reasoning channels are suppressed for
				// this mode. Delivering it would put a contentless frame on the wire,
				// which the BAML lane never emits. Drop it here rather than shaping an
				// empty streamResult.
				return nil
			}
			r := streamResult{}
			if ev.HasPartial {
				r.partial = ev.Partial
			}
			if needsRaw {
				r.raw = ev.Raw
				r.reasoning = ev.Reasoning
			}
			select {
			case ch <- r:
			case <-adapter.Done():
				return adapter.Err()
			default:
				// Buffer full: drop this partial rather than coupling the upstream read
				// to downstream backpressure (the legacy cadence's documented behavior).
			}
			return nil
		}
		out := exec.Stream(adapter, MethodName, input, emit)
		var res bamlutils.StreamResult
		if out.Disposition == bamlutils.NativeSpineSucceeded {
			f := finalResult{final: out.Final}
			if needsRaw {
				f.raw = out.Raw
				f.reasoning = out.Reasoning
			}
			res = f
		} else {
			// A pre-socket decline or a TERMINAL post-claim failure: both surface as one
			// error frame carrying the typed error (and any accumulated raw diagnostic).
			// There is no retry, no fallback, and no second attempt.
			res = errorResult{err: out.Err, raw: out.RawDiagnostic}
		}
		select {
		case ch <- res:
		case <-adapter.Done():
		}
	}()
	return ch, nil
}

// BuildMethod returns the StreamingMethod and ParseMethod registrations for
// MethodName, driven by exec (a neutral bamlutils.NativeSpineUnaryExecutor). The
// parameter type stays the UNARY executor so this module keeps compiling against the
// frozen contract and the unary registration path is unchanged; the two real streaming
// modes type-assert it up to bamlutils.NativeSpineStreamExecutor and return the typed
// local configuration error errNoStreamExecutor if a caller supplied a unary-only one.
// Neither closure makes a BAML request or parse call. The adapter (a bamlutils.Adapter
// embeds context.Context) is passed as the executor call context so a cancelled request
// is observed inside the executor. The module never falls back: an outer composite
// executor (if any) intercepts a matched pre-socket decline BEFORE these closures see
// it, so this module knows nothing about any oracle.
func BuildMethod(exec bamlutils.NativeSpineUnaryExecutor) (bamlutils.StreamingMethod, bamlutils.ParseMethod) {
	sm := bamlutils.StreamingMethod{
		MakeInput:        func() any { return new(StaticRecursiveAliasJsonInput) },
		MakeOutput:       func() any { return new(OutputJson) },
		MakeStreamOutput: makeStreamOutput,
		Impl: func(adapter bamlutils.Adapter, input any) (<-chan bamlutils.StreamResult, error) {
			// CLOSED mode switch. /call-with-raw and every unknown mode decline here,
			// before any stream execution and before any executor is even consulted.
			switch mode := adapter.StreamMode(); mode {
			case bamlutils.StreamModeCall:
				return runUnaryCall(exec, adapter, input)
			case bamlutils.StreamModeStream, bamlutils.StreamModeStreamWithRaw:
				sx, ok := exec.(bamlutils.NativeSpineStreamExecutor)
				if !ok {
					return nil, errNoStreamExecutor
				}
				return runStream(sx, adapter, input, mode.NeedsRaw())
			default:
				return nil, fmt.Errorf("%w (got mode %d)", ErrUnsupportedStreamMode, mode)
			}
		},
	}
	pm := bamlutils.ParseMethod{
		MakeOutput: func() any { return new(OutputJson) },
		Impl: func(adapter bamlutils.Adapter, raw string) (any, error) {
			return exec.Parse(adapter, MethodName, raw)
		},
		// StreamImpl is the SOCKET-FREE stream parse: the native static-stream partial
		// parse + the emitted pointer-carrier decode. It opens no client and no socket.
		StreamImpl: func(adapter bamlutils.Adapter, raw string) (any, error) {
			sx, ok := exec.(bamlutils.NativeSpineStreamExecutor)
			if !ok {
				return nil, errNoStreamExecutor
			}
			return sx.ParseStream(adapter, MethodName, raw)
		},
	}
	return sm, pm
}

// nativeSpineCheckAcyclic reports an error if v's in-memory Go value graph
// contains a pointer/slice/map cycle. A recursive carrier's custom MarshalJSON
// recurses without the ordinary encoder's cycle tracking, so a user-built cycle
// would recurse until the stack overflows; this bounded PER-CALL reflection pass
// runs before the real marshal (finite values pass it untouched, so their bytes
// are unchanged) and turns a cycle into a marshal error.
func nativeSpineCheckAcyclic(v any) error {
	return nativeSpineWalkAcyclic(reflect.ValueOf(v), map[[2]uintptr]bool{})
}

// nativeSpineWalkAcyclic walks rv, tracking the indirection nodes on the CURRENT
// path in active (add on enter, remove on leave — stack semantics, so a shared
// node reachable twice via siblings is fine and only a genuine ancestor cycle
// errors). A node's key mirrors encoding/json's ptrSeen: a pointer or map by its
// address alone, and a slice by (data pointer, len) so a sub-slice that shares its
// parent's start address is NOT a false cycle. It reads unexported carrier fields
// structurally (never via Interface(), which reflect forbids on them).
func nativeSpineWalkAcyclic(rv reflect.Value, active map[[2]uintptr]bool) error {
	switch rv.Kind() {
	case reflect.Pointer:
		if rv.IsNil() {
			return nil
		}
		k := [2]uintptr{rv.Pointer(), 0}
		if active[k] {
			return fmt.Errorf("nativespine: encountered a cycle")
		}
		active[k] = true
		err := nativeSpineWalkAcyclic(rv.Elem(), active)
		delete(active, k)
		return err
	case reflect.Interface:
		if rv.IsNil() {
			return nil
		}
		return nativeSpineWalkAcyclic(rv.Elem(), active)
	case reflect.Slice:
		if rv.IsNil() || rv.Len() == 0 {
			return nil
		}
		k := [2]uintptr{rv.Pointer(), uintptr(rv.Len())}
		if active[k] {
			return fmt.Errorf("nativespine: encountered a cycle")
		}
		active[k] = true
		for i := 0; i < rv.Len(); i++ {
			if err := nativeSpineWalkAcyclic(rv.Index(i), active); err != nil {
				delete(active, k)
				return err
			}
		}
		delete(active, k)
		return nil
	case reflect.Array:
		for i := 0; i < rv.Len(); i++ {
			if err := nativeSpineWalkAcyclic(rv.Index(i), active); err != nil {
				return err
			}
		}
		return nil
	case reflect.Map:
		if rv.IsNil() || rv.Len() == 0 {
			return nil
		}
		k := [2]uintptr{rv.Pointer(), 0}
		if active[k] {
			return fmt.Errorf("nativespine: encountered a cycle")
		}
		active[k] = true
		iter := rv.MapRange()
		for iter.Next() {
			if err := nativeSpineWalkAcyclic(iter.Value(), active); err != nil {
				delete(active, k)
				return err
			}
		}
		delete(active, k)
		return nil
	case reflect.Struct:
		for i := 0; i < rv.NumField(); i++ {
			if err := nativeSpineWalkAcyclic(rv.Field(i), active); err != nil {
				return err
			}
		}
		return nil
	default:
		return nil
	}
}

// projectInput lowers the typed input carrier into the ordered projected
// argument vector (exact type assertions, direct fields, canonical BAML names as
// literals — no reflection, JSON round-trip, or map iteration).
func projectInput(input any) ([]promptdescriptor.ArgumentValue, error) {
	in, ok := input.(*StaticRecursiveAliasJsonInput)
	if !ok {
		return nil, fmt.Errorf("nativespine: %s: input has Go type %T, want *StaticRecursiveAliasJsonInput", MethodName, input)
	}
	_ = in
	values := make([]promptdescriptor.ArgumentValue, 0, 1)
	values = append(values, promptdescriptor.ArgumentValue{Name: "topic", Value: promptdescriptor.StaticValue{Kind: promptdescriptor.StaticString, String: in.Topic}})
	return values, nil
}

// decodeFinal strictly decodes the native canonical JSON into the emitted output
// carrier via the proven bamlutils core (NO generated BAML, NO CFFI).
func decodeFinal(canonicalJSON []byte) (any, error) {
	return bamlutils.DecodeStaticAliasFinal[OutputJson](canonicalJSON)
}

// Binding returns the neutral per-method registration the production runtime
// consumes: MethodName plus the reflection-free projector and strict decoder,
// both resolved here at registration time (non-nil).
func Binding() bamlutils.NativeSpineUnaryBinding {
	return bamlutils.NativeSpineUnaryBinding{
		Method:       MethodName,
		ProjectInput: projectInput,
		DecodeFinal:  decodeFinal,
	}
}

// decodePartial strictly decodes the native canonical PARTIAL JSON into the
// emitted STREAM (pointer) carrier via the proven bamlutils core (NO generated
// BAML, NO CFFI). The FINAL of a stream uses decodeFinal — a stream final has the
// ordinary final value-union type, so the two decoders are never interchangeable.
func decodePartial(canonicalJSON []byte) (any, error) {
	return bamlutils.DecodeStaticAliasStream[OutputJsonStream](canonicalJSON)
}

// StreamBinding returns the neutral per-method STREAM registration the production
// native-only runtime consumes. Unary is the SAME Binding() the unary lane
// registers — embedding it (rather than supplying a second projector/final
// decoder) is what makes drift between the two lanes impossible. Both callbacks
// are resolved here at registration time (non-nil).
func StreamBinding() bamlutils.NativeSpineStreamBinding {
	return bamlutils.NativeSpineStreamBinding{
		Unary:         Binding(),
		DecodePartial: decodePartial,
	}
}
