package nativespinejsonfixture

import (
	"context"
	"encoding/json"
	"errors"
	"reflect"
	"testing"
	"time"

	"github.com/invakid404/baml-rest/bamlutils"
)

// stream_test.go is the M3e-A BEHAVIORAL proof of the emitted ClassStaticStream
// carrier: what the generated BuildMethod does with each public mode, how a cadence
// event becomes a bamlutils.StreamResult, and that the stream carrier's pointer level
// is the stream alias itself. It drives the REAL emitted source (regenerated by
// internal/nativespine.TestJSONAliasCodegenGolden) against a fake stream executor, so
// it opens no socket and links no BAML/CFFI.

// fakeStreamExec is a scripted bamlutils.NativeSpineStreamExecutor. It records what the
// generated closures asked of it and replays a canned event/result script.
type fakeStreamExec struct {
	calls     []string
	events    []bamlutils.NativeSpineStreamEvent
	result    bamlutils.NativeSpineStreamResult
	unary     bamlutils.NativeSpineUnaryResult
	parseOut  any
	parseErr  error
	streamOut any
	streamErr error
	sawStream bool
}

func (f *fakeStreamExec) Call(_ context.Context, method string, _ any) bamlutils.NativeSpineUnaryResult {
	f.calls = append(f.calls, "Call:"+method)
	return f.unary
}

func (f *fakeStreamExec) Parse(_ context.Context, method string, _ string) (any, error) {
	f.calls = append(f.calls, "Parse:"+method)
	return f.parseOut, f.parseErr
}

func (f *fakeStreamExec) Stream(_ context.Context, method string, _ any, emit bamlutils.NativeSpineStreamEmit) bamlutils.NativeSpineStreamResult {
	f.calls = append(f.calls, "Stream:"+method)
	f.sawStream = true
	for _, ev := range f.events {
		if err := emit(ev); err != nil {
			break
		}
	}
	return f.result
}

func (f *fakeStreamExec) ParseStream(_ context.Context, method string, _ string) (any, error) {
	f.calls = append(f.calls, "ParseStream:"+method)
	return f.streamOut, f.streamErr
}

var _ bamlutils.NativeSpineStreamExecutor = (*fakeStreamExec)(nil)

// unaryOnlyExec implements ONLY the frozen unary contract — the wiring mistake the
// generated stream arms must reject with a typed local error rather than a panic.
type unaryOnlyExec struct{}

func (unaryOnlyExec) Call(context.Context, string, any) bamlutils.NativeSpineUnaryResult {
	return bamlutils.SucceededSpineResult(nil)
}
func (unaryOnlyExec) Parse(context.Context, string, string) (any, error) { return nil, nil }

var _ bamlutils.NativeSpineUnaryExecutor = unaryOnlyExec{}

// jsonCarrier builds the STREAM (pointer) carrier — what a PARTIAL and the socket-free
// stream parse carry.
func jsonCarrier(t *testing.T, raw string) OutputJsonStream {
	t.Helper()
	v, err := bamlutils.DecodeStaticAliasStream[OutputJsonStream]([]byte(raw))
	if err != nil {
		t.Fatalf("decode stream carrier %s: %v", raw, err)
	}
	return v
}

// jsonFinalCarrier builds the FINAL (value) carrier — what production actually puts on a
// success, because the executor decodes a stream's final through the EMBEDDED unary
// DecodeFinal (DecodeStaticAliasFinal[OutputJson]), never the partial decoder. Using the
// stream carrier for a final assertion would let a stream implementation forward the wrong
// carrier type and still pass.
func jsonFinalCarrier(t *testing.T, raw string) OutputJson {
	t.Helper()
	v, err := bamlutils.DecodeStaticAliasFinal[OutputJson]([]byte(raw))
	if err != nil {
		t.Fatalf("decode final carrier %s: %v", raw, err)
	}
	return v
}

func adapterFor(mode bamlutils.StreamMode) *fixtureAdapter {
	a := newFixtureAdapter(context.Background())
	a.SetStreamMode(mode)
	return a
}

// drain collects every frame the generated Impl produced, in order.
func drain(t *testing.T, ch <-chan bamlutils.StreamResult) []bamlutils.StreamResult {
	t.Helper()
	var out []bamlutils.StreamResult
	for r := range ch {
		out = append(out, r)
	}
	return out
}

// TestMakeStreamOutputIsTheStreamCarrier is the pointer-level proof the design singles
// out: MakeStreamOutput must produce an OutputJsonStream (== *OutputUnion1), NOT a
// pointer TO the stream alias (**OutputUnion1). A double pointer would still compile
// and would then decode and marshal wrongly.
func TestMakeStreamOutputIsTheStreamCarrier(t *testing.T) {
	sm, pm := BuildMethod(&fakeStreamExec{})

	got := sm.MakeStreamOutput()
	if _, ok := got.(OutputJsonStream); !ok {
		t.Fatalf("MakeStreamOutput returned %T, want OutputJsonStream", got)
	}
	// Stated twice on purpose: once through the alias (which a future re-aliasing
	// would follow) and once through the concrete pointer level (which it would not).
	if _, ok := got.(*OutputUnion1); !ok {
		t.Fatalf("MakeStreamOutput returned %T, want *OutputUnion1", got)
	}
	if _, isDouble := got.(**OutputUnion1); isDouble {
		t.Fatal("MakeStreamOutput returned a pointer TO the stream alias (**OutputUnion1)")
	}
	if reflect.TypeOf(got) != reflect.TypeOf(OutputJsonStream(nil)) {
		t.Fatalf("MakeStreamOutput type %v is not the stream carrier type %v", reflect.TypeOf(got), reflect.TypeOf(OutputJsonStream(nil)))
	}

	// The FINAL carriers stay the VALUE union: a stream method still serves /call and
	// /parse through the final carrier, so the two levels must not converge.
	if _, ok := sm.MakeOutput().(*OutputJson); !ok {
		t.Fatalf("MakeOutput returned %T, want *OutputJson (the final value carrier)", sm.MakeOutput())
	}
	if _, ok := pm.MakeOutput().(*OutputJson); !ok {
		t.Fatalf("ParseMethod.MakeOutput returned %T, want *OutputJson", pm.MakeOutput())
	}
	if pm.StreamImpl == nil {
		t.Fatal("ParseMethod.StreamImpl is nil; a ClassStaticStream method must expose the socket-free stream parse")
	}
}

// TestBuildMethodModeSwitchIsClosed pins the CLOSED public-mode switch: /call routes to
// the frozen unary Call, both real stream modes route to Stream, and /call-with-raw
// plus any unknown mode decline BEFORE any executor dispatch.
func TestBuildMethodModeSwitchIsClosed(t *testing.T) {
	t.Run("call_dispatches_unary", func(t *testing.T) {
		f := &fakeStreamExec{unary: bamlutils.SucceededSpineResult(jsonFinalCarrier(t, `{"k":1}`))}
		sm, _ := BuildMethod(f)
		ch, err := sm.Impl(adapterFor(bamlutils.StreamModeCall), &StaticRecursiveAliasJsonInput{Topic: "x"})
		if err != nil {
			t.Fatalf("Impl(call): %v", err)
		}
		frames := drain(t, ch)
		if len(frames) != 1 || frames[0].Kind() != bamlutils.StreamResultKindFinal {
			t.Fatalf("call produced %d frame(s), want one final: %+v", len(frames), frames)
		}
		if f.sawStream {
			t.Error("/call reached the STREAM executor path")
		}
		if !reflect.DeepEqual(f.calls, []string{"Call:" + MethodName}) {
			t.Errorf("executor calls = %v, want exactly one unary Call", f.calls)
		}
	})

	for _, mode := range []bamlutils.StreamMode{bamlutils.StreamModeStream, bamlutils.StreamModeStreamWithRaw} {
		t.Run("stream_mode_dispatches_stream", func(t *testing.T) {
			f := &fakeStreamExec{result: bamlutils.SucceededSpineStreamResult(jsonFinalCarrier(t, `{"k":1}`), "", "")}
			sm, _ := BuildMethod(f)
			ch, err := sm.Impl(adapterFor(mode), &StaticRecursiveAliasJsonInput{Topic: "x"})
			if err != nil {
				t.Fatalf("Impl(mode %d): %v", mode, err)
			}
			drain(t, ch)
			if !f.sawStream {
				t.Errorf("mode %d did not reach the stream executor", mode)
			}
		})
	}

	for _, mode := range []bamlutils.StreamMode{bamlutils.StreamModeCallWithRaw, bamlutils.StreamMode(42)} {
		t.Run("unsupported_mode_declines_before_dispatch", func(t *testing.T) {
			f := &fakeStreamExec{}
			sm, _ := BuildMethod(f)
			_, err := sm.Impl(adapterFor(mode), &StaticRecursiveAliasJsonInput{Topic: "x"})
			if err == nil {
				t.Fatalf("mode %d was admitted", mode)
			}
			if !errors.Is(err, ErrUnsupportedStreamMode) {
				t.Fatalf("mode %d error %v does not wrap ErrUnsupportedStreamMode", mode, err)
			}
			if len(f.calls) != 0 {
				t.Errorf("mode %d reached the executor (%v) before declining", mode, f.calls)
			}
		})
	}
}

// TestStreamEventsMapToFrames pins the event -> StreamResult mapping for both stream
// modes: structured partials carry the pointer carrier, raw-only events carry no
// partial, and raw/reasoning are gated by the public mode exactly as the shared
// orchestrator's emitFinal gates the final's channels.
func TestStreamEventsMapToFrames(t *testing.T) {
	partial := jsonCarrier(t, `{"k":1}`)
	final := jsonFinalCarrier(t, `{"k":1,"done":true}`)
	events := []bamlutils.NativeSpineStreamEvent{
		{HasPartial: true, Partial: partial, Raw: `{"k":1}`, Reasoning: "why"},
		{HasPartial: false, Raw: `,"done"`, Reasoning: "more"},
	}

	t.Run("stream_without_raw", func(t *testing.T) {
		f := &fakeStreamExec{events: events, result: bamlutils.SucceededSpineStreamResult(final, "accumulated", "reasoned")}
		sm, _ := BuildMethod(f)
		ch, err := sm.Impl(adapterFor(bamlutils.StreamModeStream), &StaticRecursiveAliasJsonInput{Topic: "x"})
		if err != nil {
			t.Fatalf("Impl: %v", err)
		}
		frames := drain(t, ch)
		// The raw-only event is DROPPED on a plain /stream: it has no structured partial
		// and its raw/reasoning channels are suppressed for this mode, so forwarding it
		// would put a contentless frame on the wire that the BAML lane never emits.
		if len(frames) != 2 {
			t.Fatalf("got %d frames, want 1 structured partial + 1 final (the raw-only event carries no public content on /stream): %+v", len(frames), frames)
		}
		if frames[0].Kind() != bamlutils.StreamResultKindStream {
			t.Fatalf("frame 0 kind = %v, want stream", frames[0].Kind())
		}
		if frames[0].Raw() != "" || frames[0].Reasoning() != "" {
			t.Errorf("frame 0 on a plain /stream carries raw=%q reasoning=%q; both must stay empty", frames[0].Raw(), frames[0].Reasoning())
		}
		if got := frames[0].Stream(); !reflect.DeepEqual(got, partial) {
			t.Errorf("structured partial = %#v, want the emitted stream carrier", got)
		}
		// No frame may be contentless: a stream frame with neither a partial nor raw is
		// exactly the spurious empty event this mode must not produce.
		for i, fr := range frames {
			if fr.Kind() == bamlutils.StreamResultKindStream && fr.Stream() == nil && fr.Raw() == "" && fr.Reasoning() == "" {
				t.Errorf("frame %d is a contentless stream frame", i)
			}
		}
		if frames[1].Kind() != bamlutils.StreamResultKindFinal {
			t.Fatalf("last frame kind = %v, want final", frames[1].Kind())
		}
		if frames[1].Raw() != "" || frames[1].Reasoning() != "" {
			t.Errorf("final on a plain /stream carries raw=%q reasoning=%q; both must stay empty", frames[1].Raw(), frames[1].Reasoning())
		}
		if !reflect.DeepEqual(frames[1].Final(), final) {
			t.Errorf("final = %#v, want the FINAL value carrier", frames[1].Final())
		}
		// The TYPE matters independently of the value: production decodes a stream's
		// final through the embedded unary DecodeFinal, so the frame must carry the VALUE
		// carrier. A stream impl that forwarded the pointer carrier would still compare
		// equal against a pointer-carrier expectation, which is why the expectation above
		// is built with jsonFinalCarrier.
		if _, ok := frames[1].Final().(OutputJson); !ok {
			t.Errorf("final has Go type %T, want the FINAL value carrier OutputJson", frames[1].Final())
		}
		if _, isStream := frames[1].Final().(OutputJsonStream); isStream {
			t.Error("final carries the STREAM (pointer) carrier; a stream final has the ordinary value-union type")
		}
	})

	t.Run("stream_with_raw", func(t *testing.T) {
		f := &fakeStreamExec{events: events, result: bamlutils.SucceededSpineStreamResult(final, "accumulated", "reasoned")}
		sm, _ := BuildMethod(f)
		ch, err := sm.Impl(adapterFor(bamlutils.StreamModeStreamWithRaw), &StaticRecursiveAliasJsonInput{Topic: "x"})
		if err != nil {
			t.Fatalf("Impl: %v", err)
		}
		frames := drain(t, ch)
		if len(frames) != 3 {
			t.Fatalf("got %d frames, want 2 partials + 1 final", len(frames))
		}
		if frames[0].Raw() != `{"k":1}` || frames[0].Reasoning() != "why" {
			t.Errorf("structured frame raw/reasoning = (%q, %q), want the per-delta channels", frames[0].Raw(), frames[0].Reasoning())
		}
		if frames[1].Stream() != nil || frames[1].Raw() != `,"done"` || frames[1].Reasoning() != "more" {
			t.Errorf("raw-only frame = (%#v, %q, %q), want a partial-less raw/reasoning delta", frames[1].Stream(), frames[1].Raw(), frames[1].Reasoning())
		}
		if frames[2].Raw() != "accumulated" || frames[2].Reasoning() != "reasoned" {
			t.Errorf("final raw/reasoning = (%q, %q), want the accumulated channels", frames[2].Raw(), frames[2].Reasoning())
		}
		if _, ok := frames[2].Final().(OutputJson); !ok {
			t.Errorf("final has Go type %T, want the FINAL value carrier OutputJson", frames[2].Final())
		}
	})
}

// TestStreamTypedNilPartialIsPresent proves the HasPartial flag is what decides
// presence — not a nil check on the value. A typed-nil carrier is a PRESENT partial
// whose re-marshal is `null`; collapsing it into "no event" would silently drop a
// value for a nullable family.
func TestStreamTypedNilPartialIsPresent(t *testing.T) {
	var typedNil OutputJsonStream
	f := &fakeStreamExec{
		events: []bamlutils.NativeSpineStreamEvent{{HasPartial: true, Partial: typedNil}},
		result: bamlutils.SucceededSpineStreamResult(jsonFinalCarrier(t, `1`), "", ""),
	}
	sm, _ := BuildMethod(f)
	ch, err := sm.Impl(adapterFor(bamlutils.StreamModeStream), &StaticRecursiveAliasJsonInput{Topic: "x"})
	if err != nil {
		t.Fatalf("Impl: %v", err)
	}
	frames := drain(t, ch)
	if len(frames) != 2 {
		t.Fatalf("got %d frames, want one partial + one final", len(frames))
	}
	got := frames[0].Stream()
	if got == nil {
		t.Fatal("a typed-nil partial was collapsed into an untyped nil (no event)")
	}
	if _, ok := got.(OutputJsonStream); !ok {
		t.Fatalf("typed-nil partial has Go type %T, want OutputJsonStream", got)
	}
	b, err := json.Marshal(got)
	if err != nil {
		t.Fatalf("marshal typed-nil carrier: %v", err)
	}
	if string(b) != "null" {
		t.Fatalf("typed-nil carrier marshals to %s, want null", b)
	}
}

// TestStreamTerminalOutcomesAreOneErrorFrame proves BOTH non-success dispositions
// surface as exactly one error frame carrying the typed error — a pre-socket decline
// and a terminal failed-after-claim alike. The native-only artifact has no BAML to
// fall back to, so neither may be retried or resent, and a post-claim failure must
// still carry its accumulated raw diagnostic for details.raw.
func TestStreamTerminalOutcomesAreOneErrorFrame(t *testing.T) {
	declineErr := errors.New("pre-socket decline")
	claimErr := errors.New("terminal after claim")

	cases := []struct {
		name    string
		result  bamlutils.NativeSpineStreamResult
		events  []bamlutils.NativeSpineStreamEvent
		wantErr error
		wantRaw string
	}{
		{
			name:    "declined_pre_socket",
			result:  bamlutils.DeclinedSpineStreamResult(declineErr, "registry", "method_not_registered"),
			wantErr: declineErr,
		},
		{
			name:    "failed_after_claim_carries_raw",
			result:  bamlutils.FailedAfterClaimSpineStreamResult(claimErr, "serve", "transport_error", `{"k":`),
			events:  []bamlutils.NativeSpineStreamEvent{{HasPartial: false, Raw: `{"k":`}},
			wantErr: claimErr,
			wantRaw: `{"k":`,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			f := &fakeStreamExec{events: tc.events, result: tc.result}
			sm, _ := BuildMethod(f)
			ch, err := sm.Impl(adapterFor(bamlutils.StreamModeStreamWithRaw), &StaticRecursiveAliasJsonInput{Topic: "x"})
			if err != nil {
				t.Fatalf("Impl: %v", err)
			}
			frames := drain(t, ch)
			last := frames[len(frames)-1]
			if last.Kind() != bamlutils.StreamResultKindError {
				t.Fatalf("terminal frame kind = %v, want error", last.Kind())
			}
			if !errors.Is(last.Error(), tc.wantErr) {
				t.Fatalf("terminal error = %v, want %v", last.Error(), tc.wantErr)
			}
			if last.Raw() != tc.wantRaw {
				t.Fatalf("terminal raw diagnostic = %q, want %q", last.Raw(), tc.wantRaw)
			}
			if last.Final() != nil {
				t.Error("terminal error frame carries a final value")
			}
			// Exactly ONE executor entry: no second Stream, no fallback to Call.
			if len(f.calls) != 1 || f.calls[0] != "Stream:"+MethodName {
				t.Errorf("executor calls = %v, want exactly one Stream", f.calls)
			}
		})
	}
}

// TestUnaryOnlyExecutorIsRejectedOnStreamRoutes proves a unary-only executor is a
// typed LOCAL CONFIGURATION error on every stream route — never a panic and never a
// silent unary substitution — while /call and the final /parse still work.
func TestUnaryOnlyExecutorIsRejectedOnStreamRoutes(t *testing.T) {
	sm, pm := BuildMethod(unaryOnlyExec{})

	for _, mode := range []bamlutils.StreamMode{bamlutils.StreamModeStream, bamlutils.StreamModeStreamWithRaw} {
		if _, err := sm.Impl(adapterFor(mode), &StaticRecursiveAliasJsonInput{Topic: "x"}); err == nil {
			t.Errorf("mode %d was served by a unary-only executor", mode)
		}
	}
	if _, err := pm.StreamImpl(adapterFor(bamlutils.StreamModeCall), `{"k":1}`); err == nil {
		t.Error("stream parse was served by a unary-only executor")
	}
	// The frozen routes still work.
	if _, err := sm.Impl(adapterFor(bamlutils.StreamModeCall), &StaticRecursiveAliasJsonInput{Topic: "x"}); err != nil {
		t.Errorf("/call under a unary-only executor: %v", err)
	}
	if _, err := pm.Impl(adapterFor(bamlutils.StreamModeCall), `{"k":1}`); err != nil {
		t.Errorf("/parse under a unary-only executor: %v", err)
	}
}

// TestStreamBindingEmbedsTheUnaryBinding proves the stream registration carries the
// SAME final projection as the unary one (embedded, not a second copy) plus its own
// partial decoder, and that the two decoders are wired to the two DIFFERENT carriers.
func TestStreamBindingEmbedsTheUnaryBinding(t *testing.T) {
	sb := StreamBinding()
	if sb.Unary.Method != MethodName {
		t.Fatalf("StreamBinding().Unary.Method = %q, want %q", sb.Unary.Method, MethodName)
	}
	if sb.Unary.ProjectInput == nil || sb.Unary.DecodeFinal == nil || sb.DecodePartial == nil {
		t.Fatal("StreamBinding has a nil callback; all three are resolved at registration time")
	}

	// The embedded unary projection must behave identically to the standalone one.
	want, err := Binding().ProjectInput(&StaticRecursiveAliasJsonInput{Topic: "weather"})
	if err != nil {
		t.Fatalf("Binding().ProjectInput: %v", err)
	}
	got, err := sb.Unary.ProjectInput(&StaticRecursiveAliasJsonInput{Topic: "weather"})
	if err != nil {
		t.Fatalf("StreamBinding().Unary.ProjectInput: %v", err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("embedded projector produced %v, want %v", got, want)
	}

	// DecodeFinal yields the VALUE carrier; DecodePartial the POINTER carrier.
	fin, err := sb.Unary.DecodeFinal([]byte(`{"k":1}`))
	if err != nil {
		t.Fatalf("DecodeFinal: %v", err)
	}
	if _, ok := fin.(OutputJson); !ok {
		t.Fatalf("DecodeFinal produced %T, want OutputJson (the value carrier)", fin)
	}
	part, err := sb.DecodePartial([]byte(`{"k":1}`))
	if err != nil {
		t.Fatalf("DecodePartial: %v", err)
	}
	if _, ok := part.(OutputJsonStream); !ok {
		t.Fatalf("DecodePartial produced %T, want OutputJsonStream (the pointer carrier)", part)
	}
}

// TestParseRoutesAreSocketFreeAndDistinct proves /parse and /parse?stream=true dispatch
// to the two DIFFERENT executor entry points and return the two different carriers.
func TestParseRoutesAreSocketFreeAndDistinct(t *testing.T) {
	f := &fakeStreamExec{
		parseOut:  jsonCarrier(t, `{"k":1}`),
		streamOut: jsonCarrier(t, `{"k":1}`),
	}
	_, pm := BuildMethod(f)
	if _, err := pm.Impl(adapterFor(bamlutils.StreamModeCall), `{"k":1}`); err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if _, err := pm.StreamImpl(adapterFor(bamlutils.StreamModeStream), `{"k":1}`); err != nil {
		t.Fatalf("ParseStream: %v", err)
	}
	want := []string{"Parse:" + MethodName, "ParseStream:" + MethodName}
	if !reflect.DeepEqual(f.calls, want) {
		t.Fatalf("executor calls = %v, want %v", f.calls, want)
	}
	if f.sawStream {
		t.Error("a parse route entered the transport Stream path")
	}
}

// TestDeclineFramesAlwaysCarryANonNilError proves the generated error frame is never
// empty-handed. A decline is delivered to the caller as ONE error frame, so a result
// whose Err was left nil would surface as a terminal failure carrying no error at all —
// the caller sees a failed stream and has nothing to report or classify. The neutral
// constructors substitute a bounded, secret-free sentinel; this pins that the generated
// frame carries it through.
func TestDeclineFramesAlwaysCarryANonNilError(t *testing.T) {
	cases := []struct {
		name   string
		result bamlutils.NativeSpineStreamResult
		want   error
	}{
		{
			name:   "declined_with_nil_err",
			result: bamlutils.DeclinedSpineStreamResult(nil, "registry", "method_not_registered"),
			want:   bamlutils.ErrNativeSpineStreamDeclined,
		},
		{
			name:   "failed_after_claim_with_nil_err",
			result: bamlutils.FailedAfterClaimSpineStreamResult(nil, "serve", "panic", ""),
			want:   bamlutils.ErrNativeSpineStreamFailed,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if tc.result.Err == nil {
				t.Fatal("the constructor left Err nil; every non-success result must carry a bounded error")
			}
			f := &fakeStreamExec{result: tc.result}
			sm, _ := BuildMethod(f)
			ch, err := sm.Impl(adapterFor(bamlutils.StreamModeStream), &StaticRecursiveAliasJsonInput{Topic: "x"})
			if err != nil {
				t.Fatalf("Impl: %v", err)
			}
			frames := drain(t, ch)
			if len(frames) != 1 || frames[0].Kind() != bamlutils.StreamResultKindError {
				t.Fatalf("frames = %+v, want exactly one error frame", frames)
			}
			if frames[0].Error() == nil {
				t.Fatal("the error frame carries a nil error; the caller has nothing to classify")
			}
			if !errors.Is(frames[0].Error(), tc.want) {
				t.Fatalf("frame error = %v, want the bounded sentinel %v", frames[0].Error(), tc.want)
			}
		})
	}
}

// cancelOnEmitExec fills the generated result channel past its buffer and then cancels
// the adapter, so the emit closure faces a FULL buffer and a cancelled context at once.
//
// emitsDone is closed once EVERY emit has returned. The test must wait on it before it
// drains: draining concurrently frees buffer slots, which would let the final send become
// ready alongside <-Done() — and with both ready, select is entitled to choose either, so
// the assertion would be a coin flip rather than a proof.
type cancelOnEmitExec struct {
	unaryOnlyExec
	events    int
	cancel    context.CancelFunc
	emitsDone chan struct{}
	emitErrs  []error
}

func (e *cancelOnEmitExec) Stream(_ context.Context, _ string, _ any, emit bamlutils.NativeSpineStreamEmit) bamlutils.NativeSpineStreamResult {
	// Closed after the loop, so a test that waits on it observes every emitErrs write
	// (the close/receive pair is the happens-before edge that also makes the slice safe
	// to read from the test goroutine).
	defer close(e.emitsDone)
	for i := 0; i < e.events; i++ {
		// Cancel once the buffer is certainly full, so the LAST emit sees BOTH a blocked
		// send and a done context.
		if i == e.events-1 {
			e.cancel()
		}
		e.emitErrs = append(e.emitErrs, emit(bamlutils.NativeSpineStreamEvent{HasPartial: true, Partial: OutputJsonStream(nil)}))
	}
	return bamlutils.SucceededSpineStreamResult(nil, "", "")
}

func (e *cancelOnEmitExec) ParseStream(context.Context, string, string) (any, error) { return nil, nil }

var _ bamlutils.NativeSpineStreamExecutor = (*cancelOnEmitExec)(nil)

// TestFullBufferNeverMasksCancellation pins the emit closure's select semantics: when the
// bounded result channel is FULL and the adapter is cancelled, the send cannot proceed, so
// Go's select cannot choose it and the `default` (drop-the-partial) arm is unreachable —
// `default` is taken ONLY when no other case can proceed. Cancellation therefore always
// wins over the drop path, and the closure returns the context error rather than silently
// dropping a partial and reading one more delta.
func TestFullBufferNeverMasksCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	ad := newFixtureAdapter(ctx)
	ad.SetStreamMode(bamlutils.StreamModeStream)

	// More events than the buffer holds, and NOTHING drains the channel until every emit
	// has returned — so the tail of the run is deterministically the
	// full-buffer-plus-cancelled state.
	exec := &cancelOnEmitExec{
		events:    streamResultBuffer + 4,
		cancel:    cancel,
		emitsDone: make(chan struct{}),
	}
	sm, _ := BuildMethod(exec)
	ch, err := sm.Impl(ad, &StaticRecursiveAliasJsonInput{Topic: "x"})
	if err != nil {
		t.Fatalf("Impl: %v", err)
	}
	// Wait for the scripted emits BEFORE draining. Draining first is what made this
	// racy: it frees slots, so the last send can become ready and select may legally
	// take it instead of <-Done().
	select {
	case <-exec.emitsDone:
	case <-time.After(30 * time.Second):
		t.Fatal("the scripted executor did not finish emitting")
	}

	// NON-VACUITY: the buffer must really have filled, or "cancellation beat the drop
	// path" would be proven with the drop path never reached. Every emit after the
	// buffer's capacity, up to the cancelled one, must have taken the drop arm (nil).
	if len(exec.emitErrs) != exec.events {
		t.Fatalf("recorded %d emit results, want %d", len(exec.emitErrs), exec.events)
	}
	dropped := 0
	for _, e := range exec.emitErrs[:len(exec.emitErrs)-1] {
		if e == nil {
			dropped++
		}
	}
	if dropped != exec.events-1 {
		t.Fatalf("%d of %d pre-cancel emits returned an error; they must all succeed or drop silently", exec.events-1-dropped, exec.events-1)
	}
	if exec.events-1 <= streamResultBuffer {
		t.Fatal("the script never exceeds the channel buffer; the full-buffer path is untested")
	}

	last := exec.emitErrs[len(exec.emitErrs)-1]
	if last == nil {
		t.Fatal("the emit closure dropped a partial on a cancelled adapter with a full buffer; cancellation must win over the drop path")
	}
	if !errors.Is(last, context.Canceled) {
		t.Fatalf("emit returned %v, want the adapter's context error", last)
	}

	drain(t, ch)
}
