package staticservefixture

// Regeneration drift guard for the checked-in de-BAML ctx-first staticserve
// FIXTURE introspection
// (internal/nativeprompt/testdata/staticserve_fixture/introspected/introspected.go).
//
// It is the STATICSERVE twin of the stock oracle's fixture_drift_test
// (internal/nativeprompt/staticoracle): the gated de-BAML static SERVE e2e /
// cutover suites consume the EMITTED introspected fixture, so it MUST stay
// byte-identical to what `go run ./cmd/introspect` produces for the fixture's
// checked-in ctx-first baml_client + baml_src. This guard re-runs the exact
// generation into a temp dir and byte-compares, failing with the regen command
// if drift is detected. It is CGO-free (cmd/introspect parses the baml_client as
// text; it never links the BAML CFFI) and carries no build tag, so it runs in
// the default `go test` suite as part of the codegen-idempotence proof.
//
// The staticserve_fixture baml_client itself (BAML v0.223.0 generate + ctx-first
// hacks) and its generated serve adapter are regenerated by
// scripts/regen-staticserve-fixture.sh; that whole pipeline is proven idempotent
// there (a second run leaves `jj diff` empty). This guard pins the CGO-free
// introspected leg, exactly as the stock oracle guard pins its own.
//
// On mismatch it reports only the byte length, the first differing offset, and
// the regen command — never the differing bytes — so a diagnostic cannot leak
// the fixture's raw prompt/client-literal content.

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
)

func TestStaticserveFixtureIntrospectedNoDrift(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping fixture regeneration (invokes the Go toolchain) in -short mode")
	}
	if _, err := exec.LookPath("go"); err != nil {
		t.Skipf("go toolchain not available: %v", err)
	}

	repoRoot := repoRootFromCaller(t)
	committed := filepath.Join(repoRoot, "internal", "nativeprompt", "testdata", "staticserve_fixture", "introspected", "introspected.go")
	want, err := os.ReadFile(committed)
	if err != nil {
		t.Fatalf("read committed fixture: %v", err)
	}

	outDir := t.TempDir()
	// Same flags scripts/regen-staticserve-fixture.sh uses for the staticserve leg:
	// module-path roots the fixture's baml_client import at its on-disk location so
	// the generated file compiles under CGO in the serve suites; interfaces-pkg
	// roots promptdescriptor/bamlparser/schemadescriptor.
	args := []string{
		"run", "./cmd/introspect",
		"--input-dir", "internal/nativeprompt/testdata/staticserve_fixture/baml_client",
		"--baml-src-dir", "internal/nativeprompt/testdata/staticserve_fixture/baml_src",
		"--output-dir", outDir,
		"--module-path", "github.com/invakid404/baml-rest/internal/nativeprompt/testdata/staticserve_fixture",
		"--interfaces-pkg", "github.com/invakid404/baml-rest/bamlutils",
		"--baml-module-path", "github.com/boundaryml/baml",
	}
	cmd := exec.Command("go", args...)
	cmd.Dir = repoRoot
	cmd.Env = append(os.Environ(), "CGO_ENABLED=0")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("regenerating fixture failed: %v\n%s", err, out)
	}

	got, err := os.ReadFile(filepath.Join(outDir, "introspected.go"))
	if err != nil {
		t.Fatalf("read regenerated fixture: %v", err)
	}

	if !bytes.Equal(got, want) {
		off := firstDiffOffset(got, want)
		t.Fatalf("checked-in staticserve_fixture introspected fixture is STALE (committed %d bytes, regenerated %d bytes, first diff at offset %d).\n"+
			"Regenerate the whole fixture with:\n"+
			"  scripts/regen-staticserve-fixture.sh",
			len(want), len(got), off)
	}
}

func firstDiffOffset(a, b []byte) int {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return i
		}
	}
	return n
}

func repoRootFromCaller(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	// file = <repo>/internal/nativeprompt/staticservefixture/fixture_drift_test.go
	return filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(file))))
}
