// Code generated by cmd/introspect; DO NOT EDIT.

package introspected

import (
	bamlutils "github.com/invakid404/baml-rest/bamlutils"
	bamlparser "github.com/invakid404/baml-rest/bamlutils/bamlparser"
	roundrobin "github.com/invakid404/baml-rest/bamlutils/buildrequest/roundrobin"
	promptdescriptor "github.com/invakid404/baml-rest/bamlutils/promptdescriptor"
	retry "github.com/invakid404/baml-rest/bamlutils/retry"
	schemadescriptor "github.com/invakid404/baml-rest/bamlutils/schemadescriptor"
	bamlclient "github.com/invakid404/baml-rest/internal/nativeprompt/testdata/static_oracle/baml_client"
	typebuilder "github.com/invakid404/baml-rest/internal/nativeprompt/testdata/static_oracle/baml_client/type_builder"
	"os"
)

// Stream is the BAML streaming client instance
var Stream = bamlclient.Stream

// StreamMethods is a map from method name to argument names
var StreamMethods = map[string][]string{"StaticCompletion": []string{"topic"}, "StaticCompletionOutputFormat": []string{"topic"}, "StaticOutputFormat": []string{"topic"}, "StaticPrimitiveArgs": []string{"text", "count", "ratio", "flag"}, "StaticRoleChat": []string{"topic", "count"}}

// SyncMethods maps sync function names to their argument names
var SyncMethods = map[string][]string{"StaticCompletion": []string{"topic"}, "StaticCompletionOutputFormat": []string{"topic"}, "StaticOutputFormat": []string{"topic"}, "StaticPrimitiveArgs": []string{"text", "count", "ratio", "flag"}, "StaticRoleChat": []string{"topic", "count"}}

// SyncFuncs maps sync function names to their function values (for reflection)
var SyncFuncs = map[string]any{"StaticCompletion": bamlclient.StaticCompletion, "StaticCompletionOutputFormat": bamlclient.StaticCompletionOutputFormat, "StaticOutputFormat": bamlclient.StaticOutputFormat, "StaticPrimitiveArgs": bamlclient.StaticPrimitiveArgs, "StaticRoleChat": bamlclient.StaticRoleChat}

// Parse is the parse API for parsing raw LLM responses into final types
var Parse = bamlclient.Parse

// ParseMethods is a set of method names available on Parse
var ParseMethods = map[string]struct{}{"StaticCompletion": {}, "StaticCompletionOutputFormat": {}, "StaticOutputFormat": {}, "StaticPrimitiveArgs": {}, "StaticRoleChat": {}}

// ParseStream is the parse_stream API for parsing raw LLM responses into partial/stream types
var ParseStream = bamlclient.ParseStream

// ParseStreamMethods is a set of method names available on ParseStream
var ParseStreamMethods = map[string]struct{}{"StaticCompletion": {}, "StaticCompletionOutputFormat": {}, "StaticOutputFormat": {}, "StaticPrimitiveArgs": {}, "StaticRoleChat": {}}

// ParseStreamFuncs maps ParseStream method names to their function values (for reflection)
var ParseStreamFuncs = map[string]any{"StaticCompletion": bamlclient.ParseStream.StaticCompletion, "StaticCompletionOutputFormat": bamlclient.ParseStream.StaticCompletionOutputFormat, "StaticOutputFormat": bamlclient.ParseStream.StaticOutputFormat, "StaticPrimitiveArgs": bamlclient.ParseStream.StaticPrimitiveArgs, "StaticRoleChat": bamlclient.ParseStream.StaticRoleChat}

// Request is the BAML Request singleton for building non-streaming HTTP requests
var Request = bamlclient.Request

// RequestFuncs maps Request method names to their function values (for reflection)
var RequestFuncs = map[string]any{"StaticCompletion": bamlclient.Request.StaticCompletion, "StaticCompletionOutputFormat": bamlclient.Request.StaticCompletionOutputFormat, "StaticOutputFormat": bamlclient.Request.StaticOutputFormat, "StaticPrimitiveArgs": bamlclient.Request.StaticPrimitiveArgs, "StaticRoleChat": bamlclient.Request.StaticRoleChat}

// StreamRequest is the BAML StreamRequest singleton for building streaming HTTP requests
var StreamRequest = bamlclient.StreamRequest

// StreamRequestFuncs maps StreamRequest method names to their function values (for reflection)
var StreamRequestFuncs = map[string]any{"StaticCompletion": bamlclient.StreamRequest.StaticCompletion, "StaticCompletionOutputFormat": bamlclient.StreamRequest.StaticCompletionOutputFormat, "StaticOutputFormat": bamlclient.StreamRequest.StaticOutputFormat, "StaticPrimitiveArgs": bamlclient.StreamRequest.StaticPrimitiveArgs, "StaticRoleChat": bamlclient.StreamRequest.StaticRoleChat}

// SupportsWithClient is true when baml_client exposes WithClient(string) (BAML v0.219.0+)
var SupportsWithClient = true

// FunctionClient maps BAML function names to their default client name
var FunctionClient = map[string]string{"StaticCompletion": "StaticOracleClient", "StaticCompletionOutputFormat": "StaticOracleClient", "StaticOutputFormat": "StaticOracleClient", "StaticPrimitiveArgs": "StaticOracleClient", "StaticRoleChat": "StaticOracleClient"}

// FunctionProvider maps BAML function names to their default provider string
var FunctionProvider = map[string]string{"StaticCompletion": "openai", "StaticCompletionOutputFormat": "openai", "StaticOutputFormat": "openai", "StaticPrimitiveArgs": "openai", "StaticRoleChat": "openai"}

// ClientProvider maps BAML client names to their provider strings
var ClientProvider = map[string]string{"EmptyBodyClient": "openai", "EscapedModelClient": "openai", "RichBodyClient": "openai", "StaticOracleClient": "openai"}

// RetryPolicies maps retry policy names to their resolved Policy structs
var RetryPolicies = map[string]*retry.Policy{}

// FunctionRetryPolicy maps BAML function names to their retry policy name
var FunctionRetryPolicy = map[string]string{}

// ClientRetryPolicy maps BAML client names to their declared retry policy name
var ClientRetryPolicy = map[string]string{}

// FallbackChains maps strategy client names to their ordered list of child client names
var FallbackChains = map[string][]string{}

// RoundRobinStart maps baml-roundrobin client names to their configured start index
// Nil when the source defines no baml-roundrobin clients; cmd/serve uses that as the gate
// for provisioning the host-side SharedState server.
var RoundRobinStart map[string]int

// RoundRobinCoordinator holds per-client round-robin counters shared across requests
var RoundRobinCoordinator = roundrobin.NewCoordinatorWithStarts(RoundRobinStart)

// BedrockOptionValue carries one parsed aws-bedrock option value with its provenance preserved.
// Provenance discriminates the value source: "literal" (Literal carries the bare string),
// "env" (EnvVar carries the env var name), or "" (no value declared).
type BedrockOptionValue struct {
	Literal    string
	EnvVar     string
	Provenance string
}

// Resolve returns (value, ok) for this option:
//   - literal provenance: (Literal, true)
//   - env provenance:     os.LookupEnv(EnvVar)
//   - unset:              ("", false)
func (v BedrockOptionValue) Resolve() (string, bool) {
	switch v.Provenance {
	case "literal":
		return v.Literal, true
	case "env":
		return os.LookupEnv(v.EnvVar)
	}
	return "", false
}

// IsSet reports whether the field was declared in the .baml options block,
// irrespective of whether its value resolves to a non-empty string at runtime.
// Codegen uses IsSet to populate BedrockCredentialSelector presence flags so
// declared-but-env-unset credentials are still routed through the resolver's
// static-branch validation (where they fail with a client-scoped error) rather
// than silently falling through to the default AWS credential chain.
// Use Resolve for the value; IsSet for presence.
func (v BedrockOptionValue) IsSet() bool {
	return v.Provenance != ""
}

// BedrockCredentialOptions groups the per-client aws-bedrock credential selectors parsed from .baml
// options (#254 item 2). Resolution precedence (applied by bamlutils/llmhttp.ResolveBedrockCredentials):
//  1. AccessKeyID + SecretAccessKey (+ optional SessionToken) -> static credentials.
//  2. Profile -> shared-config profile load.
//  3. Default chain (none of the above declared).
//
// SECURITY: literal credential values declared inline land in this generated file AND the compiled
// worker binary. That is BAML-parity behavior, documented as an operator footgun. Prefer env.X
// references for any secret material so values stay out of generated artifacts.
type BedrockCredentialOptions struct {
	AccessKeyID     BedrockOptionValue
	SecretAccessKey BedrockOptionValue
	SessionToken    BedrockOptionValue
	Profile         BedrockOptionValue
}

// BedrockClientOptions carries the per-client aws-bedrock options that codegen needs at request-build time
// to override BAML's hardcoded modular Bedrock URL (BAML v0.219 hardcodes
// https://bedrock-runtime.<region>.amazonaws.com and the public Go HTTPRequest surface does not expose
// ClientDetails, so baml-rest carries its own resolved options keyed on client name).
type BedrockClientOptions struct {
	EndpointURL BedrockOptionValue
	Region      BedrockOptionValue
	Credentials BedrockCredentialOptions
}

// BedrockClientOptionsByName maps aws-bedrock client names to their parsed endpoint_url, region,
// and credential-selector options. Codegen looks up the resolved client name here at request-build
// time and dispatches to llmhttp.AttachBedrockAuthForClient with the resolved values.
var BedrockClientOptionsByName = map[string]BedrockClientOptions{}

// StaticPromptDescriptors maps a BAML method name to a factory returning a FRESH
// promptdescriptor.Function on every call (de-BAML Phase 8A, representation only — no
// serving/admission/socket path consumes it). SECURITY: a returned descriptor's raw
// prompt bytes and any inline client literals are baked into this generated file and the
// worker binary; never log / metric-label / %v-format / error-wrap a descriptor or its raw
// fields. Prefer env.X references so secrets stay out of the generated artifact.
var StaticPromptDescriptors = map[string]func() promptdescriptor.Function{"StaticCompletion": func() promptdescriptor.Function {
	return promptdescriptor.Function{
		Args: []promptdescriptor.Argument{promptdescriptor.Argument{
			Name: "topic",
			Type: &bamlparser.TypeExpr{
				Kind:      bamlparser.KindPrimitive,
				Primitive: "string",
				Span: bamlparser.Span{
					Col:   34,
					End:   619,
					Line:  10,
					Start: 613,
				},
			},
		}},
		Client: "StaticOracleClient",
		ClientConfig: promptdescriptor.ClientConfig{
			Model: promptdescriptor.ClientModel{
				Provenance: promptdescriptor.ModelProvenanceLiteral,
				Value:      "fake-static-oracle-model",
			},
			Name:     "StaticOracleClient",
			Present:  true,
			Provider: "openai",
			TransportOptions: []promptdescriptor.ClientOption{promptdescriptor.ClientOption{
				Key: "api_key",
				Value: promptdescriptor.OptionValue{
					Kind:   promptdescriptor.OptionString,
					String: "fake-static-oracle-key",
				},
			}, promptdescriptor.ClientOption{
				Key: "base_url",
				Value: promptdescriptor.OptionValue{
					Kind:   promptdescriptor.OptionString,
					String: "https://static-oracle.invalid/v1",
				},
			}},
		},
		Method:   "StaticCompletion",
		Prompt:   "\n    Write a short, plain note about {{ topic }}.\n  ",
		Provider: "openai",
		Return: schemadescriptor.Bundle{
			Method: "StaticCompletion",
			Target: schemadescriptor.Type{
				Kind:      schemadescriptor.TypePrimitive,
				Primitive: schemadescriptor.PrimitiveString,
			},
			Version: 1,
		},
		Version: 2,
	}
}, "StaticCompletionOutputFormat": func() promptdescriptor.Function {
	return promptdescriptor.Function{
		Args: []promptdescriptor.Argument{promptdescriptor.Argument{
			Name: "topic",
			Type: &bamlparser.TypeExpr{
				Kind:      bamlparser.KindPrimitive,
				Primitive: "string",
				Span: bamlparser.Span{
					Col:   46,
					End:   2385,
					Line:  60,
					Start: 2379,
				},
			},
		}},
		Client: "StaticOracleClient",
		ClientConfig: promptdescriptor.ClientConfig{
			Model: promptdescriptor.ClientModel{
				Provenance: promptdescriptor.ModelProvenanceLiteral,
				Value:      "fake-static-oracle-model",
			},
			Name:     "StaticOracleClient",
			Present:  true,
			Provider: "openai",
			TransportOptions: []promptdescriptor.ClientOption{promptdescriptor.ClientOption{
				Key: "api_key",
				Value: promptdescriptor.OptionValue{
					Kind:   promptdescriptor.OptionString,
					String: "fake-static-oracle-key",
				},
			}, promptdescriptor.ClientOption{
				Key: "base_url",
				Value: promptdescriptor.OptionValue{
					Kind:   promptdescriptor.OptionString,
					String: "https://static-oracle.invalid/v1",
				},
			}},
		},
		Method:   "StaticCompletionOutputFormat",
		Prompt:   "\n    Summarize {{ topic }}.\n    {{ ctx.output_format }}\n  ",
		Provider: "openai",
		Return: schemadescriptor.Bundle{
			Classes: []schemadescriptor.ClassDef{schemadescriptor.ClassDef{
				Fields: []schemadescriptor.ClassField{schemadescriptor.ClassField{
					Name: schemadescriptor.Name{Name: "answer"},
					Type: schemadescriptor.Type{
						Kind:      schemadescriptor.TypePrimitive,
						Primitive: schemadescriptor.PrimitiveString,
					},
				}, schemadescriptor.ClassField{
					Name: schemadescriptor.Name{Name: "confidence"},
					Type: schemadescriptor.Type{
						Kind:      schemadescriptor.TypePrimitive,
						Primitive: schemadescriptor.PrimitiveInt,
					},
				}},
				Mode: schemadescriptor.NonStreaming,
				Name: schemadescriptor.Name{Name: "StaticAnswer"},
			}},
			Method: "StaticCompletionOutputFormat",
			Target: schemadescriptor.Type{
				Kind: schemadescriptor.TypeClass,
				Mode: schemadescriptor.NonStreaming,
				Name: "StaticAnswer",
			},
			Version: 1,
		},
		Version: 2,
	}
}, "StaticOutputFormat": func() promptdescriptor.Function {
	return promptdescriptor.Function{
		Args: []promptdescriptor.Argument{promptdescriptor.Argument{
			Name: "topic",
			Type: &bamlparser.TypeExpr{
				Kind:      bamlparser.KindPrimitive,
				Primitive: "string",
				Span: bamlparser.Span{
					Col:   36,
					End:   2029,
					Line:  49,
					Start: 2023,
				},
			},
		}},
		Client: "StaticOracleClient",
		ClientConfig: promptdescriptor.ClientConfig{
			Model: promptdescriptor.ClientModel{
				Provenance: promptdescriptor.ModelProvenanceLiteral,
				Value:      "fake-static-oracle-model",
			},
			Name:     "StaticOracleClient",
			Present:  true,
			Provider: "openai",
			TransportOptions: []promptdescriptor.ClientOption{promptdescriptor.ClientOption{
				Key: "api_key",
				Value: promptdescriptor.OptionValue{
					Kind:   promptdescriptor.OptionString,
					String: "fake-static-oracle-key",
				},
			}, promptdescriptor.ClientOption{
				Key: "base_url",
				Value: promptdescriptor.OptionValue{
					Kind:   promptdescriptor.OptionString,
					String: "https://static-oracle.invalid/v1",
				},
			}},
		},
		Method:   "StaticOutputFormat",
		Prompt:   "\n    {{ _.role(\"user\") }}\n    Summarize {{ topic }} for me.\n    {{ ctx.output_format }}\n  ",
		Provider: "openai",
		Return: schemadescriptor.Bundle{
			Classes: []schemadescriptor.ClassDef{schemadescriptor.ClassDef{
				Fields: []schemadescriptor.ClassField{schemadescriptor.ClassField{
					Name: schemadescriptor.Name{Name: "answer"},
					Type: schemadescriptor.Type{
						Kind:      schemadescriptor.TypePrimitive,
						Primitive: schemadescriptor.PrimitiveString,
					},
				}, schemadescriptor.ClassField{
					Name: schemadescriptor.Name{Name: "confidence"},
					Type: schemadescriptor.Type{
						Kind:      schemadescriptor.TypePrimitive,
						Primitive: schemadescriptor.PrimitiveInt,
					},
				}},
				Mode: schemadescriptor.NonStreaming,
				Name: schemadescriptor.Name{Name: "StaticAnswer"},
			}},
			Method: "StaticOutputFormat",
			Target: schemadescriptor.Type{
				Kind: schemadescriptor.TypeClass,
				Mode: schemadescriptor.NonStreaming,
				Name: "StaticAnswer",
			},
			Version: 1,
		},
		Version: 2,
	}
}, "StaticPrimitiveArgs": func() promptdescriptor.Function {
	return promptdescriptor.Function{
		Args: []promptdescriptor.Argument{promptdescriptor.Argument{
			Name: "text",
			Type: &bamlparser.TypeExpr{
				Kind:      bamlparser.KindPrimitive,
				Primitive: "string",
				Span: bamlparser.Span{
					Col:   36,
					End:   1079,
					Line:  21,
					Start: 1073,
				},
			},
		}, promptdescriptor.Argument{
			Name: "count",
			Type: &bamlparser.TypeExpr{
				Kind:      bamlparser.KindPrimitive,
				Primitive: "int",
				Span: bamlparser.Span{
					Col:   51,
					End:   1091,
					Line:  21,
					Start: 1088,
				},
			},
		}, promptdescriptor.Argument{
			Name: "ratio",
			Type: &bamlparser.TypeExpr{
				Kind:      bamlparser.KindPrimitive,
				Primitive: "float",
				Span: bamlparser.Span{
					Col:   63,
					End:   1105,
					Line:  21,
					Start: 1100,
				},
			},
		}, promptdescriptor.Argument{
			Name: "flag",
			Type: &bamlparser.TypeExpr{
				Kind:      bamlparser.KindPrimitive,
				Primitive: "bool",
				Span: bamlparser.Span{
					Col:   76,
					End:   1117,
					Line:  21,
					Start: 1113,
				},
			},
		}},
		Client: "StaticOracleClient",
		ClientConfig: promptdescriptor.ClientConfig{
			Model: promptdescriptor.ClientModel{
				Provenance: promptdescriptor.ModelProvenanceLiteral,
				Value:      "fake-static-oracle-model",
			},
			Name:     "StaticOracleClient",
			Present:  true,
			Provider: "openai",
			TransportOptions: []promptdescriptor.ClientOption{promptdescriptor.ClientOption{
				Key: "api_key",
				Value: promptdescriptor.OptionValue{
					Kind:   promptdescriptor.OptionString,
					String: "fake-static-oracle-key",
				},
			}, promptdescriptor.ClientOption{
				Key: "base_url",
				Value: promptdescriptor.OptionValue{
					Kind:   promptdescriptor.OptionString,
					String: "https://static-oracle.invalid/v1",
				},
			}},
		},
		Method:   "StaticPrimitiveArgs",
		Prompt:   "\n    text={{ text }}\n    count={{ count }}\n    ratio={{ ratio }}\n    flag={{ flag }}\n  ",
		Provider: "openai",
		Return: schemadescriptor.Bundle{
			Method: "StaticPrimitiveArgs",
			Target: schemadescriptor.Type{
				Kind:      schemadescriptor.TypePrimitive,
				Primitive: schemadescriptor.PrimitiveString,
			},
			Version: 1,
		},
		Version: 2,
	}
}, "StaticRoleChat": func() promptdescriptor.Function {
	return promptdescriptor.Function{
		Args: []promptdescriptor.Argument{promptdescriptor.Argument{
			Name: "topic",
			Type: &bamlparser.TypeExpr{
				Kind:      bamlparser.KindPrimitive,
				Primitive: "string",
				Span: bamlparser.Span{
					Col:   32,
					End:   1527,
					Line:  34,
					Start: 1521,
				},
			},
		}, promptdescriptor.Argument{
			Name: "count",
			Type: &bamlparser.TypeExpr{
				Kind:      bamlparser.KindPrimitive,
				Primitive: "int",
				Span: bamlparser.Span{
					Col:   47,
					End:   1539,
					Line:  34,
					Start: 1536,
				},
			},
		}},
		Client: "StaticOracleClient",
		ClientConfig: promptdescriptor.ClientConfig{
			Model: promptdescriptor.ClientModel{
				Provenance: promptdescriptor.ModelProvenanceLiteral,
				Value:      "fake-static-oracle-model",
			},
			Name:     "StaticOracleClient",
			Present:  true,
			Provider: "openai",
			TransportOptions: []promptdescriptor.ClientOption{promptdescriptor.ClientOption{
				Key: "api_key",
				Value: promptdescriptor.OptionValue{
					Kind:   promptdescriptor.OptionString,
					String: "fake-static-oracle-key",
				},
			}, promptdescriptor.ClientOption{
				Key: "base_url",
				Value: promptdescriptor.OptionValue{
					Kind:   promptdescriptor.OptionString,
					String: "https://static-oracle.invalid/v1",
				},
			}},
		},
		Method:   "StaticRoleChat",
		Prompt:   "\n    {{ _.role(\"system\") }}\n    You are a concise assistant.\n    {{ _.role(\"user\") }}\n    Tell me about {{ topic }}.\n    {{ _.chat(role=\"assistant\") }}\n    Here are {{ count }} facts.\n  ",
		Provider: "openai",
		Return: schemadescriptor.Bundle{
			Method: "StaticRoleChat",
			Target: schemadescriptor.Type{
				Kind:      schemadescriptor.TypePrimitive,
				Primitive: schemadescriptor.PrimitiveString,
			},
			Version: 1,
		},
		Version: 2,
	}
}}

// StaticPromptDeclines maps a BAML method name to the stable build-time reason it is NOT
// an eligible static prompt descriptor. Disjoint from StaticPromptDescriptors. Every entry
// is a #583 teardown blocker to close, not an accepted permanent fallback.
var StaticPromptDeclines = map[string]string{}

// StaticPromptDescriptor returns a fresh descriptor and true when method has an emitted
// static prompt descriptor; it returns the zero Function and false otherwise (method absent
// or declined). It NEVER manufactures a zero-valued "supported" descriptor: a caller must
// treat !ok as "no native static descriptor; stay on the BAML path".
func StaticPromptDescriptor(method string) (promptdescriptor.Function, bool) {
	factory, ok := StaticPromptDescriptors[method]
	if !ok {
		return promptdescriptor.Function{}, false
	}
	return factory(), true
}

// MediaParams maps function name -> param name -> media kind for parameters that are BAML media types.
var MediaParams = map[string]map[string]bamlutils.MediaKind{}

// TypeBuilder is the generated TypeBuilder type
type TypeBuilder = typebuilder.TypeBuilder

// Type is the BAML type
type Type = typebuilder.Type

// ClassPropertyBuilder is the interface for class property builders
type ClassPropertyBuilder = typebuilder.ClassPropertyBuilder

// EnumValueBuilder is the interface for enum value builders
type EnumValueBuilder = typebuilder.EnumValueBuilder

// NewTypeBuilder creates a new TypeBuilder using the BAML runtime's factory
var NewTypeBuilder = bamlclient.NewTypeBuilder

// Typed is a minimal interface for types that can return a Type
type Typed interface {
	Type() (Type, error)
}

// DynamicClassBuilder is the interface for dynamic classes
type DynamicClassBuilder interface {
	Type() (Type, error)
	AddProperty(name string, fieldType Type) (ClassPropertyBuilder, error)
}

// DynamicEnumBuilder is the interface for dynamic enums
type DynamicEnumBuilder interface {
	Type() (Type, error)
	AddValue(value string) (EnumValueBuilder, error)
}

// DynamicClassAccessor is a function that returns a DynamicClassBuilder for a dynamic class
type DynamicClassAccessor func(*TypeBuilder) (DynamicClassBuilder, error)

// DynamicEnumAccessor is a function that returns a DynamicEnumBuilder for a dynamic enum
type DynamicEnumAccessor func(*TypeBuilder) (DynamicEnumBuilder, error)

// StaticClassAccessor is a function that returns a Typed for a static class
type StaticClassAccessor func(*TypeBuilder) (Typed, error)

// StaticEnumAccessor is a function that returns a Typed for a static enum
type StaticEnumAccessor func(*TypeBuilder) (Typed, error)

// DynamicClasses maps dynamic class names to their accessor functions
var DynamicClasses = map[string]DynamicClassAccessor{}

// StaticClasses maps static class names to their accessor functions
var StaticClasses = map[string]StaticClassAccessor{"StaticAnswer": func(tb *TypeBuilder) (Typed, error) {
	return tb.StaticAnswer()
}}

// DynamicEnums maps dynamic enum names to their accessor functions
var DynamicEnums = map[string]DynamicEnumAccessor{}

// StaticEnums maps static enum names to their accessor functions
var StaticEnums = map[string]StaticEnumAccessor{}

// AllClasses returns all known class names (both dynamic and static)
func AllClasses() []string {
	result := make([]string, 0, len(DynamicClasses)+len(StaticClasses))
	for name := range DynamicClasses {
		result = append(result, name)
	}
	for name := range StaticClasses {
		result = append(result, name)
	}
	return result
}

// AllEnums returns all known enum names (both dynamic and static)
func AllEnums() []string {
	result := make([]string, 0, len(DynamicEnums)+len(StaticEnums))
	for name := range DynamicEnums {
		result = append(result, name)
	}
	for name := range StaticEnums {
		result = append(result, name)
	}
	return result
}

// IsDynamicClass returns true if the class exists and is dynamic
func IsDynamicClass(name string) bool {
	_, ok := DynamicClasses[name]
	return ok
}

// IsDynamicEnum returns true if the enum exists and is dynamic
func IsDynamicEnum(name string) bool {
	_, ok := DynamicEnums[name]
	return ok
}

// ClassExists returns true if a class with this name exists (dynamic or static)
func ClassExists(name string) bool {
	_, dynamic := DynamicClasses[name]
	_, static := StaticClasses[name]
	return dynamic || static
}

// EnumExists returns true if an enum with this name exists (dynamic or static)
func EnumExists(name string) bool {
	_, dynamic := DynamicEnums[name]
	_, static := StaticEnums[name]
	return dynamic || static
}

// GetClassType returns the Type for a class by name
func GetClassType(tb *TypeBuilder, name string) (Type, error) {
	if accessor, ok := DynamicClasses[name]; ok {
		builder, err := accessor(tb)
		if err != nil {
			return nil, err
		}
		return builder.Type()
	}
	if accessor, ok := StaticClasses[name]; ok {
		view, err := accessor(tb)
		if err != nil {
			return nil, err
		}
		return view.Type()
	}
	return nil, nil
}

// GetEnumType returns the Type for an enum by name
func GetEnumType(tb *TypeBuilder, name string) (Type, error) {
	if accessor, ok := DynamicEnums[name]; ok {
		builder, err := accessor(tb)
		if err != nil {
			return nil, err
		}
		return builder.Type()
	}
	if accessor, ok := StaticEnums[name]; ok {
		view, err := accessor(tb)
		if err != nil {
			return nil, err
		}
		return view.Type()
	}
	return nil, nil
}
