// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: workerplugin/proto/worker.proto

package workerplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamResult_Kind int32

const (
	StreamResult_STREAM    StreamResult_Kind = 0
	StreamResult_FINAL     StreamResult_Kind = 1
	StreamResult_ERROR     StreamResult_Kind = 2
	StreamResult_HEARTBEAT StreamResult_Kind = 3 // Signals first byte received from LLM (filtered at pool level)
)

// Enum value maps for StreamResult_Kind.
var (
	StreamResult_Kind_name = map[int32]string{
		0: "STREAM",
		1: "FINAL",
		2: "ERROR",
		3: "HEARTBEAT",
	}
	StreamResult_Kind_value = map[string]int32{
		"STREAM":    0,
		"FINAL":     1,
		"ERROR":     2,
		"HEARTBEAT": 3,
	}
)

func (x StreamResult_Kind) Enum() *StreamResult_Kind {
	p := new(StreamResult_Kind)
	*p = x
	return p
}

func (x StreamResult_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamResult_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_workerplugin_proto_worker_proto_enumTypes[0].Descriptor()
}

func (StreamResult_Kind) Type() protoreflect.EnumType {
	return &file_workerplugin_proto_worker_proto_enumTypes[0]
}

func (x StreamResult_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamResult_Kind.Descriptor instead.
func (StreamResult_Kind) EnumDescriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{1, 0}
}

// Request to call a BAML method
type CallRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MethodName          string                 `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	InputJson           []byte                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`                                  // JSON-encoded input struct (includes __baml_options__ if present)
	EnableRawCollection bool                   `protobuf:"varint,3,opt,name=enable_raw_collection,json=enableRawCollection,proto3" json:"enable_raw_collection,omitempty"` // When true, capture raw LLM response via OnTick/SSE parsing
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *CallRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

func (x *CallRequest) GetEnableRawCollection() bool {
	if x != nil {
		return x.EnableRawCollection
	}
	return false
}

// Streaming result
type StreamResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          StreamResult_Kind      `protobuf:"varint,1,opt,name=kind,proto3,enum=workerplugin.StreamResult_Kind" json:"kind,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // JSON-encoded stream/final data
	Raw           string                 `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`                           // Raw LLM response text (populated on FINAL)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                       // Error message (populated on ERROR)
	Stacktrace    string                 `protobuf:"bytes,5,opt,name=stacktrace,proto3" json:"stacktrace,omitempty"`             // Stacktrace (populated on ERROR, when available)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResult) Reset() {
	*x = StreamResult{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResult) ProtoMessage() {}

func (x *StreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResult.ProtoReflect.Descriptor instead.
func (*StreamResult) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResult) GetKind() StreamResult_Kind {
	if x != nil {
		return x.Kind
	}
	return StreamResult_STREAM
}

func (x *StreamResult) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *StreamResult) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *StreamResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StreamResult) GetStacktrace() string {
	if x != nil {
		return x.Stacktrace
	}
	return ""
}

// Health check
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

// Metrics response - contains serialized Prometheus metrics
type MetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized prometheus MetricFamily protos
	// Use prometheus client_model to deserialize
	MetricFamilies [][]byte `protobuf:"bytes,1,rep,name=metric_families,json=metricFamilies,proto3" json:"metric_families,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsResponse) GetMetricFamilies() [][]byte {
	if x != nil {
		return x.MetricFamilies
	}
	return nil
}

// GC response - contains memory stats before/after GC
type GCResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HeapAllocBefore uint64                 `protobuf:"varint,1,opt,name=heap_alloc_before,json=heapAllocBefore,proto3" json:"heap_alloc_before,omitempty"`
	HeapAllocAfter  uint64                 `protobuf:"varint,2,opt,name=heap_alloc_after,json=heapAllocAfter,proto3" json:"heap_alloc_after,omitempty"`
	HeapReleased    uint64                 `protobuf:"varint,3,opt,name=heap_released,json=heapReleased,proto3" json:"heap_released,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GCResponse) Reset() {
	*x = GCResponse{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCResponse) ProtoMessage() {}

func (x *GCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCResponse.ProtoReflect.Descriptor instead.
func (*GCResponse) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *GCResponse) GetHeapAllocBefore() uint64 {
	if x != nil {
		return x.HeapAllocBefore
	}
	return 0
}

func (x *GCResponse) GetHeapAllocAfter() uint64 {
	if x != nil {
		return x.HeapAllocAfter
	}
	return 0
}

func (x *GCResponse) GetHeapReleased() uint64 {
	if x != nil {
		return x.HeapReleased
	}
	return 0
}

var File_workerplugin_proto_worker_proto protoreflect.FileDescriptor

const file_workerplugin_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x1fworkerplugin/proto/worker.proto\x12\fworkerplugin\"\x81\x01\n" +
	"\vCallRequest\x12\x1f\n" +
	"\vmethod_name\x18\x01 \x01(\tR\n" +
	"methodName\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\fR\tinputJson\x122\n" +
	"\x15enable_raw_collection\x18\x03 \x01(\bR\x13enableRawCollection\"\xe1\x01\n" +
	"\fStreamResult\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.workerplugin.StreamResult.KindR\x04kind\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\x12\x10\n" +
	"\x03raw\x18\x03 \x01(\tR\x03raw\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"stacktrace\x18\x05 \x01(\tR\n" +
	"stacktrace\"7\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06STREAM\x10\x00\x12\t\n" +
	"\x05FINAL\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\r\n" +
	"\tHEARTBEAT\x10\x03\"\a\n" +
	"\x05Empty\"*\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\":\n" +
	"\x0fMetricsResponse\x12'\n" +
	"\x0fmetric_families\x18\x01 \x03(\fR\x0emetricFamilies\"\x87\x01\n" +
	"\n" +
	"GCResponse\x12*\n" +
	"\x11heap_alloc_before\x18\x01 \x01(\x04R\x0fheapAllocBefore\x12(\n" +
	"\x10heap_alloc_after\x18\x02 \x01(\x04R\x0eheapAllocAfter\x12#\n" +
	"\rheap_released\x18\x03 \x01(\x04R\fheapReleased2\x8a\x02\n" +
	"\x06Worker\x12E\n" +
	"\n" +
	"CallStream\x12\x19.workerplugin.CallRequest\x1a\x1a.workerplugin.StreamResult0\x01\x12;\n" +
	"\x06Health\x12\x13.workerplugin.Empty\x1a\x1c.workerplugin.HealthResponse\x12@\n" +
	"\n" +
	"GetMetrics\x12\x13.workerplugin.Empty\x1a\x1d.workerplugin.MetricsResponse\x12:\n" +
	"\tTriggerGC\x12\x13.workerplugin.Empty\x1a\x18.workerplugin.GCResponseB.Z,github.com/invakid404/baml-rest/workerpluginb\x06proto3"

var (
	file_workerplugin_proto_worker_proto_rawDescOnce sync.Once
	file_workerplugin_proto_worker_proto_rawDescData []byte
)

func file_workerplugin_proto_worker_proto_rawDescGZIP() []byte {
	file_workerplugin_proto_worker_proto_rawDescOnce.Do(func() {
		file_workerplugin_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workerplugin_proto_worker_proto_rawDesc), len(file_workerplugin_proto_worker_proto_rawDesc)))
	})
	return file_workerplugin_proto_worker_proto_rawDescData
}

var file_workerplugin_proto_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workerplugin_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_workerplugin_proto_worker_proto_goTypes = []any{
	(StreamResult_Kind)(0),  // 0: workerplugin.StreamResult.Kind
	(*CallRequest)(nil),     // 1: workerplugin.CallRequest
	(*StreamResult)(nil),    // 2: workerplugin.StreamResult
	(*Empty)(nil),           // 3: workerplugin.Empty
	(*HealthResponse)(nil),  // 4: workerplugin.HealthResponse
	(*MetricsResponse)(nil), // 5: workerplugin.MetricsResponse
	(*GCResponse)(nil),      // 6: workerplugin.GCResponse
}
var file_workerplugin_proto_worker_proto_depIdxs = []int32{
	0, // 0: workerplugin.StreamResult.kind:type_name -> workerplugin.StreamResult.Kind
	1, // 1: workerplugin.Worker.CallStream:input_type -> workerplugin.CallRequest
	3, // 2: workerplugin.Worker.Health:input_type -> workerplugin.Empty
	3, // 3: workerplugin.Worker.GetMetrics:input_type -> workerplugin.Empty
	3, // 4: workerplugin.Worker.TriggerGC:input_type -> workerplugin.Empty
	2, // 5: workerplugin.Worker.CallStream:output_type -> workerplugin.StreamResult
	4, // 6: workerplugin.Worker.Health:output_type -> workerplugin.HealthResponse
	5, // 7: workerplugin.Worker.GetMetrics:output_type -> workerplugin.MetricsResponse
	6, // 8: workerplugin.Worker.TriggerGC:output_type -> workerplugin.GCResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workerplugin_proto_worker_proto_init() }
func file_workerplugin_proto_worker_proto_init() {
	if File_workerplugin_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workerplugin_proto_worker_proto_rawDesc), len(file_workerplugin_proto_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workerplugin_proto_worker_proto_goTypes,
		DependencyIndexes: file_workerplugin_proto_worker_proto_depIdxs,
		EnumInfos:         file_workerplugin_proto_worker_proto_enumTypes,
		MessageInfos:      file_workerplugin_proto_worker_proto_msgTypes,
	}.Build()
	File_workerplugin_proto_worker_proto = out.File
	file_workerplugin_proto_worker_proto_goTypes = nil
	file_workerplugin_proto_worker_proto_depIdxs = nil
}
