// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: workerplugin/proto/worker.proto

package workerplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamMode controls how streaming results are processed
type StreamMode int32

const (
	StreamMode_STREAM_MODE_CALL            StreamMode = 0 // final only, no raw, skip partials
	StreamMode_STREAM_MODE_STREAM          StreamMode = 1 // partials + final, no raw
	StreamMode_STREAM_MODE_CALL_WITH_RAW   StreamMode = 2 // final + raw, skip intermediate parsing
	StreamMode_STREAM_MODE_STREAM_WITH_RAW StreamMode = 3 // partials + final + raw
)

// Enum value maps for StreamMode.
var (
	StreamMode_name = map[int32]string{
		0: "STREAM_MODE_CALL",
		1: "STREAM_MODE_STREAM",
		2: "STREAM_MODE_CALL_WITH_RAW",
		3: "STREAM_MODE_STREAM_WITH_RAW",
	}
	StreamMode_value = map[string]int32{
		"STREAM_MODE_CALL":            0,
		"STREAM_MODE_STREAM":          1,
		"STREAM_MODE_CALL_WITH_RAW":   2,
		"STREAM_MODE_STREAM_WITH_RAW": 3,
	}
)

func (x StreamMode) Enum() *StreamMode {
	p := new(StreamMode)
	*p = x
	return p
}

func (x StreamMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamMode) Descriptor() protoreflect.EnumDescriptor {
	return file_workerplugin_proto_worker_proto_enumTypes[0].Descriptor()
}

func (StreamMode) Type() protoreflect.EnumType {
	return &file_workerplugin_proto_worker_proto_enumTypes[0]
}

func (x StreamMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamMode.Descriptor instead.
func (StreamMode) EnumDescriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{0}
}

type StreamResult_Kind int32

const (
	StreamResult_STREAM    StreamResult_Kind = 0
	StreamResult_FINAL     StreamResult_Kind = 1
	StreamResult_ERROR     StreamResult_Kind = 2
	StreamResult_HEARTBEAT StreamResult_Kind = 3 // Signals first byte received from LLM (filtered at pool level)
	StreamResult_METADATA  StreamResult_Kind = 4 // Routing/retry metadata event; data_json holds bamlutils.Metadata JSON
)

// Enum value maps for StreamResult_Kind.
var (
	StreamResult_Kind_name = map[int32]string{
		0: "STREAM",
		1: "FINAL",
		2: "ERROR",
		3: "HEARTBEAT",
		4: "METADATA",
	}
	StreamResult_Kind_value = map[string]int32{
		"STREAM":    0,
		"FINAL":     1,
		"ERROR":     2,
		"HEARTBEAT": 3,
		"METADATA":  4,
	}
)

func (x StreamResult_Kind) Enum() *StreamResult_Kind {
	p := new(StreamResult_Kind)
	*p = x
	return p
}

func (x StreamResult_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamResult_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_workerplugin_proto_worker_proto_enumTypes[1].Descriptor()
}

func (StreamResult_Kind) Type() protoreflect.EnumType {
	return &file_workerplugin_proto_worker_proto_enumTypes[1]
}

func (x StreamResult_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamResult_Kind.Descriptor instead.
func (StreamResult_Kind) EnumDescriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{1, 0}
}

// Request to call a BAML method
type CallRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MethodName string                 `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	InputJson  []byte                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`                                  // JSON-encoded input struct (includes __baml_options__ if present)
	StreamMode StreamMode             `protobuf:"varint,3,opt,name=stream_mode,json=streamMode,proto3,enum=workerplugin.StreamMode" json:"stream_mode,omitempty"` // Controls partial forwarding and raw collection
	// Stable per-request identifier. Used by the worker as the operation_id
	// when calling the host's SharedState.FetchAdd, so retries of the same
	// request observe the same counter value and don't advance the rotation
	// a second time. Empty means the worker should not attempt idempotency
	// caching (legacy callers / tests without a generated request id).
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *CallRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

func (x *CallRequest) GetStreamMode() StreamMode {
	if x != nil {
		return x.StreamMode
	}
	return StreamMode_STREAM_MODE_CALL
}

func (x *CallRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Streaming result
type StreamResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          StreamResult_Kind      `protobuf:"varint,1,opt,name=kind,proto3,enum=workerplugin.StreamResult_Kind" json:"kind,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // JSON-encoded stream/final/metadata data
	Raw           string                 `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`                           // Raw LLM response text (populated on FINAL)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                       // Error message (populated on ERROR)
	Stacktrace    string                 `protobuf:"bytes,5,opt,name=stacktrace,proto3" json:"stacktrace,omitempty"`             // Stacktrace (populated on ERROR, when available)
	Reset_        bool                   `protobuf:"varint,6,opt,name=reset,proto3" json:"reset,omitempty"`                      // When true, client should discard accumulated state (retry occurred)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResult) Reset() {
	*x = StreamResult{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResult) ProtoMessage() {}

func (x *StreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResult.ProtoReflect.Descriptor instead.
func (*StreamResult) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResult) GetKind() StreamResult_Kind {
	if x != nil {
		return x.Kind
	}
	return StreamResult_STREAM
}

func (x *StreamResult) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *StreamResult) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *StreamResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StreamResult) GetStacktrace() string {
	if x != nil {
		return x.Stacktrace
	}
	return ""
}

func (x *StreamResult) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

// Health check
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

// Metrics response - contains serialized Prometheus metrics
type MetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized prometheus MetricFamily protos
	// Use prometheus client_model to deserialize
	MetricFamilies [][]byte `protobuf:"bytes,1,rep,name=metric_families,json=metricFamilies,proto3" json:"metric_families,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsResponse) GetMetricFamilies() [][]byte {
	if x != nil {
		return x.MetricFamilies
	}
	return nil
}

// GC response - contains memory stats before/after GC
type GCResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HeapAllocBefore uint64                 `protobuf:"varint,1,opt,name=heap_alloc_before,json=heapAllocBefore,proto3" json:"heap_alloc_before,omitempty"`
	HeapAllocAfter  uint64                 `protobuf:"varint,2,opt,name=heap_alloc_after,json=heapAllocAfter,proto3" json:"heap_alloc_after,omitempty"`
	HeapReleased    uint64                 `protobuf:"varint,3,opt,name=heap_released,json=heapReleased,proto3" json:"heap_released,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GCResponse) Reset() {
	*x = GCResponse{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCResponse) ProtoMessage() {}

func (x *GCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCResponse.ProtoReflect.Descriptor instead.
func (*GCResponse) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *GCResponse) GetHeapAllocBefore() uint64 {
	if x != nil {
		return x.HeapAllocBefore
	}
	return 0
}

func (x *GCResponse) GetHeapAllocAfter() uint64 {
	if x != nil {
		return x.HeapAllocAfter
	}
	return 0
}

func (x *GCResponse) GetHeapReleased() uint64 {
	if x != nil {
		return x.HeapReleased
	}
	return 0
}

// Request to parse raw LLM output
type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodName    string                 `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	InputJson     []byte                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"` // JSON-encoded input (contains "raw" and optional "__baml_options__")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{6}
}

func (x *ParseRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *ParseRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

// Parse response
type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataJson      []byte                 `protobuf:"bytes,1,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // JSON-encoded parsed result
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                       // Error message (if parsing failed)
	Stacktrace    string                 `protobuf:"bytes,3,opt,name=stacktrace,proto3" json:"stacktrace,omitempty"`             // Stacktrace (if parsing failed, when available)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{7}
}

func (x *ParseResponse) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *ParseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ParseResponse) GetStacktrace() string {
	if x != nil {
		return x.Stacktrace
	}
	return ""
}

// Goroutines request - for getting pprof data from worker
type GetGoroutinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"` // Optional comma-separated filter patterns (case-insensitive)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoroutinesRequest) Reset() {
	*x = GetGoroutinesRequest{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoroutinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoroutinesRequest) ProtoMessage() {}

func (x *GetGoroutinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoroutinesRequest.ProtoReflect.Descriptor instead.
func (*GetGoroutinesRequest) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{8}
}

func (x *GetGoroutinesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// Goroutines response - pprof goroutine data
type GetGoroutinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`         // Total number of goroutines
	MatchCount    int32                  `protobuf:"varint,2,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`         // Number of goroutines matching filter
	MatchedStacks []string               `protobuf:"bytes,3,rep,name=matched_stacks,json=matchedStacks,proto3" json:"matched_stacks,omitempty"` // Stack traces of matching goroutines
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoroutinesResponse) Reset() {
	*x = GetGoroutinesResponse{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoroutinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoroutinesResponse) ProtoMessage() {}

func (x *GetGoroutinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoroutinesResponse.ProtoReflect.Descriptor instead.
func (*GetGoroutinesResponse) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{9}
}

func (x *GetGoroutinesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetGoroutinesResponse) GetMatchCount() int32 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

func (x *GetGoroutinesResponse) GetMatchedStacks() []string {
	if x != nil {
		return x.MatchedStacks
	}
	return nil
}

// Request sent by the host (serve process) to tell a worker where to dial
// back for shared-state RPCs. The broker_id identifies an already-listening
// listener on the host side (go-plugin GRPCBroker).
type AttachSharedStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      uint32                 `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachSharedStateRequest) Reset() {
	*x = AttachSharedStateRequest{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachSharedStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachSharedStateRequest) ProtoMessage() {}

func (x *AttachSharedStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachSharedStateRequest.ProtoReflect.Descriptor instead.
func (*AttachSharedStateRequest) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{10}
}

func (x *AttachSharedStateRequest) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

// Request to atomically add delta to a named counter and return the pre-
// increment value. The counter space is flat; keys are chosen by the caller
// (the worker) and the host stores whatever bytes it receives.
//
// If operation_id is non-empty, the host caches (key, operation_id) ->
// previous and returns the cached value on retries without advancing the
// counter. Empty operation_id disables caching: every call advances.
type FetchAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Delta         uint64                 `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAddRequest) Reset() {
	*x = FetchAddRequest{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAddRequest) ProtoMessage() {}

func (x *FetchAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAddRequest.ProtoReflect.Descriptor instead.
func (*FetchAddRequest) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{11}
}

func (x *FetchAddRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FetchAddRequest) GetDelta() uint64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *FetchAddRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type FetchAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Previous      uint64                 `protobuf:"varint,1,opt,name=previous,proto3" json:"previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAddResponse) Reset() {
	*x = FetchAddResponse{}
	mi := &file_workerplugin_proto_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAddResponse) ProtoMessage() {}

func (x *FetchAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerplugin_proto_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAddResponse.ProtoReflect.Descriptor instead.
func (*FetchAddResponse) Descriptor() ([]byte, []int) {
	return file_workerplugin_proto_worker_proto_rawDescGZIP(), []int{12}
}

func (x *FetchAddResponse) GetPrevious() uint64 {
	if x != nil {
		return x.Previous
	}
	return 0
}

var File_workerplugin_proto_worker_proto protoreflect.FileDescriptor

const file_workerplugin_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x1fworkerplugin/proto/worker.proto\x12\fworkerplugin\"\xa7\x01\n" +
	"\vCallRequest\x12\x1f\n" +
	"\vmethod_name\x18\x01 \x01(\tR\n" +
	"methodName\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\fR\tinputJson\x129\n" +
	"\vstream_mode\x18\x03 \x01(\x0e2\x18.workerplugin.StreamModeR\n" +
	"streamMode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\x85\x02\n" +
	"\fStreamResult\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.workerplugin.StreamResult.KindR\x04kind\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\x12\x10\n" +
	"\x03raw\x18\x03 \x01(\tR\x03raw\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"stacktrace\x18\x05 \x01(\tR\n" +
	"stacktrace\x12\x14\n" +
	"\x05reset\x18\x06 \x01(\bR\x05reset\"E\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06STREAM\x10\x00\x12\t\n" +
	"\x05FINAL\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\r\n" +
	"\tHEARTBEAT\x10\x03\x12\f\n" +
	"\bMETADATA\x10\x04\"\a\n" +
	"\x05Empty\"*\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\":\n" +
	"\x0fMetricsResponse\x12'\n" +
	"\x0fmetric_families\x18\x01 \x03(\fR\x0emetricFamilies\"\x87\x01\n" +
	"\n" +
	"GCResponse\x12*\n" +
	"\x11heap_alloc_before\x18\x01 \x01(\x04R\x0fheapAllocBefore\x12(\n" +
	"\x10heap_alloc_after\x18\x02 \x01(\x04R\x0eheapAllocAfter\x12#\n" +
	"\rheap_released\x18\x03 \x01(\x04R\fheapReleased\"N\n" +
	"\fParseRequest\x12\x1f\n" +
	"\vmethod_name\x18\x01 \x01(\tR\n" +
	"methodName\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\fR\tinputJson\"b\n" +
	"\rParseResponse\x12\x1b\n" +
	"\tdata_json\x18\x01 \x01(\fR\bdataJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"stacktrace\x18\x03 \x01(\tR\n" +
	"stacktrace\".\n" +
	"\x14GetGoroutinesRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\"\x80\x01\n" +
	"\x15GetGoroutinesResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vmatch_count\x18\x02 \x01(\x05R\n" +
	"matchCount\x12%\n" +
	"\x0ematched_stacks\x18\x03 \x03(\tR\rmatchedStacks\"7\n" +
	"\x18AttachSharedStateRequest\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\rR\bbrokerId\"\\\n" +
	"\x0fFetchAddRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x04R\x05delta\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\".\n" +
	"\x10FetchAddResponse\x12\x1a\n" +
	"\bprevious\x18\x01 \x01(\x04R\bprevious*z\n" +
	"\n" +
	"StreamMode\x12\x14\n" +
	"\x10STREAM_MODE_CALL\x10\x00\x12\x16\n" +
	"\x12STREAM_MODE_STREAM\x10\x01\x12\x1d\n" +
	"\x19STREAM_MODE_CALL_WITH_RAW\x10\x02\x12\x1f\n" +
	"\x1bSTREAM_MODE_STREAM_WITH_RAW\x10\x032\xf8\x03\n" +
	"\x06Worker\x12E\n" +
	"\n" +
	"CallStream\x12\x19.workerplugin.CallRequest\x1a\x1a.workerplugin.StreamResult0\x01\x12;\n" +
	"\x06Health\x12\x13.workerplugin.Empty\x1a\x1c.workerplugin.HealthResponse\x12@\n" +
	"\n" +
	"GetMetrics\x12\x13.workerplugin.Empty\x1a\x1d.workerplugin.MetricsResponse\x12:\n" +
	"\tTriggerGC\x12\x13.workerplugin.Empty\x1a\x18.workerplugin.GCResponse\x12@\n" +
	"\x05Parse\x12\x1a.workerplugin.ParseRequest\x1a\x1b.workerplugin.ParseResponse\x12X\n" +
	"\rGetGoroutines\x12\".workerplugin.GetGoroutinesRequest\x1a#.workerplugin.GetGoroutinesResponse\x12P\n" +
	"\x11AttachSharedState\x12&.workerplugin.AttachSharedStateRequest\x1a\x13.workerplugin.Empty2X\n" +
	"\vSharedState\x12I\n" +
	"\bFetchAdd\x12\x1d.workerplugin.FetchAddRequest\x1a\x1e.workerplugin.FetchAddResponseB.Z,github.com/invakid404/baml-rest/workerpluginb\x06proto3"

var (
	file_workerplugin_proto_worker_proto_rawDescOnce sync.Once
	file_workerplugin_proto_worker_proto_rawDescData []byte
)

func file_workerplugin_proto_worker_proto_rawDescGZIP() []byte {
	file_workerplugin_proto_worker_proto_rawDescOnce.Do(func() {
		file_workerplugin_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workerplugin_proto_worker_proto_rawDesc), len(file_workerplugin_proto_worker_proto_rawDesc)))
	})
	return file_workerplugin_proto_worker_proto_rawDescData
}

var file_workerplugin_proto_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_workerplugin_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_workerplugin_proto_worker_proto_goTypes = []any{
	(StreamMode)(0),                  // 0: workerplugin.StreamMode
	(StreamResult_Kind)(0),           // 1: workerplugin.StreamResult.Kind
	(*CallRequest)(nil),              // 2: workerplugin.CallRequest
	(*StreamResult)(nil),             // 3: workerplugin.StreamResult
	(*Empty)(nil),                    // 4: workerplugin.Empty
	(*HealthResponse)(nil),           // 5: workerplugin.HealthResponse
	(*MetricsResponse)(nil),          // 6: workerplugin.MetricsResponse
	(*GCResponse)(nil),               // 7: workerplugin.GCResponse
	(*ParseRequest)(nil),             // 8: workerplugin.ParseRequest
	(*ParseResponse)(nil),            // 9: workerplugin.ParseResponse
	(*GetGoroutinesRequest)(nil),     // 10: workerplugin.GetGoroutinesRequest
	(*GetGoroutinesResponse)(nil),    // 11: workerplugin.GetGoroutinesResponse
	(*AttachSharedStateRequest)(nil), // 12: workerplugin.AttachSharedStateRequest
	(*FetchAddRequest)(nil),          // 13: workerplugin.FetchAddRequest
	(*FetchAddResponse)(nil),         // 14: workerplugin.FetchAddResponse
}
var file_workerplugin_proto_worker_proto_depIdxs = []int32{
	0,  // 0: workerplugin.CallRequest.stream_mode:type_name -> workerplugin.StreamMode
	1,  // 1: workerplugin.StreamResult.kind:type_name -> workerplugin.StreamResult.Kind
	2,  // 2: workerplugin.Worker.CallStream:input_type -> workerplugin.CallRequest
	4,  // 3: workerplugin.Worker.Health:input_type -> workerplugin.Empty
	4,  // 4: workerplugin.Worker.GetMetrics:input_type -> workerplugin.Empty
	4,  // 5: workerplugin.Worker.TriggerGC:input_type -> workerplugin.Empty
	8,  // 6: workerplugin.Worker.Parse:input_type -> workerplugin.ParseRequest
	10, // 7: workerplugin.Worker.GetGoroutines:input_type -> workerplugin.GetGoroutinesRequest
	12, // 8: workerplugin.Worker.AttachSharedState:input_type -> workerplugin.AttachSharedStateRequest
	13, // 9: workerplugin.SharedState.FetchAdd:input_type -> workerplugin.FetchAddRequest
	3,  // 10: workerplugin.Worker.CallStream:output_type -> workerplugin.StreamResult
	5,  // 11: workerplugin.Worker.Health:output_type -> workerplugin.HealthResponse
	6,  // 12: workerplugin.Worker.GetMetrics:output_type -> workerplugin.MetricsResponse
	7,  // 13: workerplugin.Worker.TriggerGC:output_type -> workerplugin.GCResponse
	9,  // 14: workerplugin.Worker.Parse:output_type -> workerplugin.ParseResponse
	11, // 15: workerplugin.Worker.GetGoroutines:output_type -> workerplugin.GetGoroutinesResponse
	4,  // 16: workerplugin.Worker.AttachSharedState:output_type -> workerplugin.Empty
	14, // 17: workerplugin.SharedState.FetchAdd:output_type -> workerplugin.FetchAddResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_workerplugin_proto_worker_proto_init() }
func file_workerplugin_proto_worker_proto_init() {
	if File_workerplugin_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workerplugin_proto_worker_proto_rawDesc), len(file_workerplugin_proto_worker_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_workerplugin_proto_worker_proto_goTypes,
		DependencyIndexes: file_workerplugin_proto_worker_proto_depIdxs,
		EnumInfos:         file_workerplugin_proto_worker_proto_enumTypes,
		MessageInfos:      file_workerplugin_proto_worker_proto_msgTypes,
	}.Build()
	File_workerplugin_proto_worker_proto = out.File
	file_workerplugin_proto_worker_proto_goTypes = nil
	file_workerplugin_proto_worker_proto_depIdxs = nil
}
