// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type StaticAnswer struct {
	Answer     *string `json:"answer"`
	Confidence *int64  `json:"confidence"`
}

func (c *StaticAnswer) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "StaticAnswer" {
		panic(fmt.Sprintf("expected StaticAnswer, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "answer":
			c.Answer = baml.Decode(valueHolder).Interface().(*string)

		case "confidence":
			c.Confidence = baml.Decode(valueHolder).Interface().(*int64)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class StaticAnswer", key))

		}
	}

}

func (c StaticAnswer) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["answer"] = c.Answer

	fields["confidence"] = c.Confidence

	return baml.EncodeClass("StaticAnswer", fields, nil)
}

func (c StaticAnswer) BamlTypeName() string {
	return "StaticAnswer"
}
